### ISSUE TITLE
debian lightdm-xsession `Unable to create default screen recorder`

### ISSUE THREAD

**Issue by daithi-coombes** [phw/peek#103]
Hi,

I am looking to try out peek for showing prototypes of UI's.

My system:
```
cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

echo $DESKTOP_SESSION
lightdm-xsession
```

after downloading and building source (eventually with no errors)
```
configure
make
sudo make install
```

all installs and links well, peek is even registered in desktop as an app. But running it does nothing - also no logs in `/var/log/peek*`. From the `build` directory I can run it and get the following error...

```
cd /opt/peek/build
./peek
Error: Child process exited with code 1
Error: Child process exited with code 1
Unable to create default screen recorder.
```

My thinking is that I need to run peek along with my `X Session`, but not sure how to...
```
peek --display {$putAnswerHere}
```

I'm lost, its that `putAnswerHere` that I think I need? Or maybe `peek` is uncompatable with `lightdm-xsession` and thus can't set a default desktop server? Any help appreciated ;)

**Comment by phw** [comment]
You need either ffmpeg or avconv installed. Peek tries to detect this by calling `which ffmpeg` and `which avconv`, both seem to fail for your system (that's likely the two "Child process exited with code 1" errors). 

ffmpeg is preferred, with avconv provided for compatibility mainly for Debian. avconv has some annoying small differences and also some limitations (mainly you annot disable recording the mousecurser with it).

**Comment by phw** [comment]
Closing this as I think the issue was just the missing ffmpeg. Feel free to open a new issue if you still have problems with ffmpeg installed.
