### ISSUE TITLE
Failed to open Peek on Wayland without GDK_BACKEND=x11.

### ISSUE THREAD

**Issue by JulianLai** [phw/peek#109]
I have installed the `peek-git` from AUR, but it still can't run on Wayland natively.
`You are running Peek natively on Wayland, this is currently unsupported. Please start Peek using XWayland by setting GDK_BACKEND=x11`
![2017-03-18 15-35-35](https://cloud.githubusercontent.com/assets/20014762/24070067/9fa2de2c-0bf0-11e7-834b-2527b98a2f6f.png)

**Comment by phw** [comment]
Just follow the instructions and run it with XWayland by calling:

    GDK_BACKEND=x11 peek

If you start it via the desktop shortcut it should already be set correctly.

**Comment by JulianLai** [comment]
@phw I have to do it in terminal, the desktop shortcut doesn't work.

**Comment by JulianLai** [comment]
@phw help?

**Comment by phw** [comment]
What do you mean the desktop shortcut doesn't work? Does it do nothing or does it show that Wayland info dialog?

From the terminal just run

    GDK_BACKEND=x11 peek

Does that work?

**Comment by JulianLai** [comment]
@phw Yes, I can do it in terminal, but the desktop shortcut shows the Wayland info dialog.

**Comment by phw** [comment]
Ok, I'll investigate

**Comment by phw** [comment]
I know what's happening: since Peek is DBus activatable the command from the Desktop file is not used, but the one from the service file.I will fix that later today.

**Comment by phw** [comment]
Has been fixed, just tested with the actual peek-git package. Please update your peek-git package and it should work.

**Comment by JulianLai** [comment]
@phw 
It works now, thanks.
By the way, it's my first time to try a arch base distro, do I have to reinstall the package from AUR everytime? Is there any other ways that I can get the updates from git? It seems like yaourt -Syua won't get the updates from git.

**Comment by phw** [comment]
Yaourt had the "--devel" parameter for this.

    yaourt -Syua --devel

This will update all your packages that have outdated version numbers and will also rebuild all VCS packages (-git, -bzr etc.)

Or if you want to update only a single package you can just run "yaourt -Syu peek-git" again.

**Comment by JulianLai** [comment]
@phw Can Pamac do that?

**Comment by phw** [comment]
No, pacman is for binary package sources only. For the AUR you either
download the PKGBUILD and build with makepkg or you use one of the AUR
helpers to automate this.

Am 19.03.2017 2:55 nachm. schrieb "JulianLai" <notifications@github.com>:
