### ISSUE TITLE
Feature request: detect whether the mouse cursor is hidden

### ISSUE THREAD

**Issue by UlyssesZh** [phw/peek#1092]
There are currently only two options about the mouse cursor: always shown in the recorded video, or always hidden in the recorded video. I hope there is another option for intelligently detecting whether the cursor is hidden so that the recorded video is just the same as what people see on the screen.

**Comment by phw** [comment]
I don't fully understand, you have two options to either record the mouse cursor or not, what would it auto detect?

But regardless the answer is no. This depends on the recording back ends being used, and both ffmpeg and gnome screen recorder only have a boolean flag to either record the mouse cursor or not.

**Comment by UlyssesZh** [comment]
> you have two options to either record the mouse cursor or not, what would it auto detect?

Because the mouse cursor may be hidden in the middle of the recording. For example, when I am using mouse, the cursor is not hidden; when I am using touchscreen, the cursor is still moving (along with my finger), but it is hidden. If I switch using mouse to using touchscreen, the cursor will at first be visible but then hidden. However, Peek can only either always show the cursor or always hide the cursor (the expected behavior is to show the cursor at first when I am using mouse but then hide the cursor when I am using touchscreen).

> both ffmpeg and gnome screen recorder only have a boolean flag to either record the mouse cursor or not.

That's sad story. Maybe I should post issues there.
