### ISSUE TITLE
Grey bars on left and right

### ISSUE THREAD

**Issue by dankranz** [phw/peek#11]
Using Peek on Ubuntu 16.04 with Unity each gif has a slim grey bar on the left and right. 
Could this be removed?

**Comment by phw** [comment]
What's likely happening here is that the inner borders of the Peek Window get recorded as well. I have to look into this, any special theme you are using or the default?

I already did some tweaking of the recording area, but maybe this is theme dependent sometimes and I have to add theme specific tweak. But maybe the new recording implementation proposed in #1 would also help here.

**Comment by dankranz** [comment]
Hello Phillipp. Peek is a very nice little program. I am using the Ubuntu
default theme. I have attached a gif to show you what it is doing. I found
out I can load it into Gimp and simply crop off the grey bars and it works
fine.
Thanks for getting back to me.
Keep up the great work.

Dan Kranz

**Comment by probonopd** [comment]
Example recorded on Ubuntu 16.04 with Peek-0.7.2.glibc2.14-x86_64.AppImage:

![makeexec](https://cloud.githubusercontent.com/assets/2480569/19224873/bf7a08c2-8e8e-11e6-8537-2b1bd4dd42ea.gif)

**Comment by skrillex581** [comment]
I have the same problem under Ubuntu 16.04

**Comment by dandv** [comment]
Just installed Peek, sop happy I no longer have to depend on the abandoned GifRecorder!

I found the same problem with the grey bars. Hoping for a fix soon!

![amp custom loading indicator](https://cloud.githubusercontent.com/assets/33569/22918152/b6c2a668-f23d-11e6-91de-2e8195af5743.gif)

**Comment by dandv** [comment]
Interestingly, [LICEcap on WINE](http://www.tutorialgeek.net/2016/07/the-fastest-easiest-and-best-way-to.html) doesn't record those bars.

**Comment by phw** [comment]
This is a Gtk styling issue. I had already looked into it in the past and did not find the cause. But I have now committed a fix that will fix this. It is kind of a workaround, since it removes the rounded borders from the headerbar, but interestingly this also removes the gray bars. Somehow the border caused by this on the Window was visible in the recording area.

The change is only active on Ubuntu Unity, since I could not reproduce it elsewhere. But if anybody experiences this somewhere else let me know and we can hopefully fix it there, too.

**Comment by probonopd** [comment]
Will there be a new release with a new deb?

**Comment by phw** [comment]
@probonopd Yes, I want to make a new release. Until then there is now a PPA, see https://github.com/phw/peek/issues/15#issuecomment-279704016

Let me know if this works as expected.

**Comment by probonopd** [comment]
@phw 

Working well for me. I generated a `Peek-0.8.0.glibc2.14-x86_64.AppImage` [based on the ppa](https://github.com/probonopd/AppImages/blob/master/recipes/meta/Peek.yml), and this works on Ubuntu 16.04 without the grey bars.

**Comment by dandv** [comment]
The daily PPA works for me too. Yay, no more gray bars!
