### ISSUE TITLE
mp4 files missing mime types

### ISSUE THREAD

**Issue by Deluxo** [phw/peek#111]
Hello
videos in mp4 format recorded with peek cannot be played in html5 players,
saying: "no video with supported format and MIME type found".

People with windows media player cannot play the file,
however mpv does play it well.

**Comment by phw** [comment]
Could reproduce. Depended a bit on the browser, e.g. Chrome worked fine for me. Reason was the h264 encoding profile used, now uses the web save baseline profile.
