### ISSUE TITLE
Need an Icon?

### ISSUE THREAD

**Issue by JasonLG1979** [phw/peek#114]
I installed peek in Fedora 25 via the repo and it seems to work pretty good, does just about all I need it to do. Nice little utility.

Anyway, I'm not sure if it's a bug in the packaging but peek doesn't seem to have an icon. If you don't in fact have an icon yet I'd be happy to design you one if you'd like? I'm decent at icon design. I redesigned Pithos's icon a couple years ago. https://pithos.github.io/

**Comment by phw** [comment]
Peek has an icon, and it should show up. You probably have to run gtk-update-icon-cache or restart the shell to see it (on Arch Linux gtk-update-icon-cache runs automatically after package installation and that usually does the trick).

Anyway, the icon is not too pretty :) See  https://github.com/phw/peek/blob/master/data/icons/256x256/com.uploadedlobster.peek.png . It was a quick shot I got from someone, and it served well. But it does not fit well with other icons and doesn't tell much about the app.

If you want to give this a go I am more than happy to replace this icon .

**Comment by JasonLG1979** [comment]
> Peek has an icon, and it should show up. You probably have to run gtk-update-icon-cache or restart the shell to see it (on Arch Linux gtk-update-icon-cache runs automatically after package installation and that usually does the trick).

Must be a bug in the packaging. Neither gtk-update-icon-cache nor restarting the shell shows the icon.

> If you want to give this a go I am more than happy to replace this icon .

What did you have in mind style wise? Tango, flat?

**Comment by JasonLG1979** [comment]
Ok, weird. The icon finally showed up after 2 reboots...

**Comment by phw** [comment]
> What did you have in mind style wise? Tango, flat?

I think Tango like is fine. It should look nice with the icons you find on a typical GNOME or Unity desktop. I found my original request for an icon: https://www.reddit.com/r/freedesign/comments/3zlcqc/request_application_logo_for_open_source_animated/

I still have no good idea about what the icon should show. A thing that changed a bit is, that Peek no longer is exclusively recording only GIFs.

> Ok, weird. The icon finally showed up after 2 reboots...

Gnome Shell sometimes has some issues picking icons up, I have experienced this with other software as well. But normally running gtk-update-icon-cache or restarting the shell with `Alt+F2, r` does the trick for me. Also when I tested the Fedora package in a Virtual Machine it worked right away. I would say if the icons are installed at the right location this is a Gnome glitch.

**Comment by phw** [comment]
See also my comment on https://github.com/phw/peek/issues/115

**Comment by meetdilip** [comment]
How do you want the new icon to look like ? Any pointers ?

**Comment by bertob** [comment]
Hi, Tobias from the GNOME design team here.

We're working on a new icon style for GNOME, which will make it much easier to make app icons because it's simpler, more geometric, and there are fewer sizes. We will update all core GNOME apps' icons to the new style for 3.32 early next year, but some third-party apps are already starting to use them.

If you're interested in a new icon following the new guidelines I'd be happy to provide one.

**Comment by phw** [comment]
@bertob Is your offer still valid? Would be happy to see a new icon for Peek, but lack the skills to fix this myself.

**Comment by baranpirincal** [comment]
Hey @phw , if you still need a logo design for Peek, I can help you. If you have an idea, feel free to share with me.

**Comment by bertob** [comment]
@phw sure is. This is one of the ideas we've been playing with:

**Comment by gort818** [comment]
@bertob That is pretty awesome!

**Comment by phw** [comment]
@bertob I like this very much, great work. What about just getting rid of the "PEEK" text? Then it would already work well I think.

**Comment by bertob** [comment]
Ok, I think i found something that works:

![image](https://user-images.githubusercontent.com/1908896/47884817-925b7b00-de32-11e8-96b9-ae312e23c084.png)

Unfortunately Github doesn't allow uploading SVG (which is seriously weird, especially given that it does allow PPTX), so I put the hicolor and symbolic in a zip

[com.uploadedlobster.peek.zip](https://github.com/phw/peek/files/2540412/com.uploadedlobster.peek.zip)

**Comment by phw** [comment]
Thanks, this is awesome. Also like the color. What is your recommendation on providing PNG scaled versions for this? If I read the current HIG correctly it is recommended to only provide the SVG, so this should be fine, right?

**Comment by phw** [comment]
Thanks, prepared everything in https://github.com/phw/peek/pull/390/

@bertob Are you fine with how I credited you in these changes?

**Comment by bertob** [comment]
@phw can you change my email to tbernard@gnome.org?

Also, the icon was a collaboration with @snwh, @jimmac, and @lapo, so not sure what the best way to attribute credit is.

**Comment by phw** [comment]
Thanks a lot, finally merged

**Comment by bertob** [comment]
Is there an ETA for a new release?

I'm not sure what else is happening in the code base atm, but I for one would be very happy if included had no changes other than the icon :)

**Comment by WinEunuuchs2Unix** [comment]
Thanks for making this icon everyone. It looks nice on the desktop.
