### ISSUE TITLE
Icon suggestion

### ISSUE THREAD

**Issue by meetdilip** [phw/peek#115]
Just wondering whether you would like to use this as icon for Peek. More suggestive, in my opinion :)

![peek](https://cloud.githubusercontent.com/assets/6965443/24189636/c4e9b6ce-0f0b-11e7-9220-b4d71888b78d.png)

**Comment by meetdilip** [comment]
Forgot to mention. 100 % crafted by me.

**Comment by phw** [comment]
I thought about this for a while. I definitely want to have an icon that is more suggestive than the current "P", but this icon looks kind of too stylized, with only single color flat shapes.

There are currently two issues open about a new icon. I am going to close this in favor of https://github.com/phw/peek/issues/114, feel free to comment there.
