### ISSUE TITLE
Where do you keep icons in Ubuntu

### ISSUE THREAD

**Issue by meetdilip** [phw/peek#117]
Hi, Where can I find the default icon images for Peek in 16.04 ? Kindly share the image location. Thanks.

**Comment by phw** [comment]
Icons are installed in `share/icons/hicolor/`, e.g. `/usr/share/icons/hicolor/256x256/apps/com.uploadedlobster.peek.png`. Currently available in the sizes at https://github.com/phw/peek/tree/master/data/icons

**Comment by meetdilip** [comment]
Thanks. Where can I find 

> /apps/com.uploadedlobster.peek.png

**Comment by phw** [comment]
/usr/share/icons/hicolor/256x256/apps/com.uploadedlobster.peek.png
