### ISSUE TITLE
Output is all black except for mouse on i3 tiling window manager

### ISSUE THREAD

**Issue by pathammer** [phw/peek#12]
I use i3 instead of the unity desktop environment. The output gif from peek is all black except for my mouse. Using ffmpeg and x11grab independently works just fine.

**Comment by oleerik** [comment]
Experiencing the same issue. I believe you need to run a proper compositor for peek to work, however I did try with the built-in nvidia compositor and still got the black output.

**Comment by phw** [comment]
Running a compositor is a requirement for this to work, sot this would have been my first guess. Also I found I had issues with screen capturing in virtual machines with a similar result, but this did actually not just affect Peek but other screen capturing tools as well.

Just to be sure: When you run Peek the inner area is shown transparent? What happens, if you use ffmpeg and x11grab over the Peek window?

**Comment by ibrahima** [comment]
If it helps, I'm able to record with Peek using Awesome WM (another tiling WM) and compton. However, I'm not able to click through the recording window to the windows underneath.

**Comment by KabbAmine** [comment]
Using i3 here with compton, and no problem so far using Peek.
Some tips here:

* Set Peek as a floated window
* After starting the recording, select the recording zone using keyboard (There is no way to select it using the mouse)

**Comment by cars10** [comment]
I experience the same issue with awesome wm. Just black - nothing works.

**Comment by jruz** [comment]
i3 + compton here, works for recording but no way to get click through, resizes the window when I click.
Any luck anyone?

**Comment by dmsmidt** [comment]
Also using i3 + compton, also no luck interacting with the window below my floating peek.

Note: `focus_follows_mouse no` doesn't work.

**Comment by phw** [comment]
@dmsmidt, @jruz, @ibrahima and everybody else having issues clicking through the recording area please have a look at issue #52. Trying to find a common component here, so far my bet is on Compton. But just in cade, can you provide the Gtk version used in the linked issue?

**Comment by phw** [comment]
Added FAQ with the compositing requirement explained.

**Comment by phw** [comment]
Just a note that removing the need for a compositor is work in progress, see https://github.com/phw/peek/issues/147

**Comment by ibrahima** [comment]
Neat! Pretty excited to see that this might work without hackery in Awesome in the near future.

**Comment by erfanio** [comment]
I was having the same problem.  
The fix was running both peek and the window you want to record in floating more (with peek resized to what you want), hit record on peek and switch to the other floating window and do your thing, switch back and stop.

**Comment by oliversturm** [comment]
I can confirm what @erfanio suggests. I'm running i3 without compton on three 4k screens and often have trouble due to excessive resolution :) Using the described method looks a bit odd, but works perfectly in my setup.
