### ISSUE TITLE
codeblocks-devs/release/ubuntu focal Release Not Found

### ISSUE THREAD

**Issue by qfritayre** [phw/peek#1201]
**System Information**

- Linux XXXX 5.15.0-60-generic '#'66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- apt 2.0.9 (amd64)

**Describe the bug**
Input : 
`sudo add-apt-repository ppa:peek-developers/stable`

Output : 
```
Err:8 http://ppa.launchpad.net/codeblocks-devs/release/ubuntu focal Release    
  404  Not Found [IP: 185.125.190.52 80]
E: The repository 'http://ppa.launchpad.net/codeblocks-devs/release/ubuntu focal Release' does not have a Release file.
```

**Comment by phw** [comment]
The error is unrelated to the peek-developers PPA. It looks like you have another PPA for codeblocks-devs in your configuration that is not available for focal. Please remove that repository from your configuration in/etc/apt/sources.list or /etc/apt/sources.list.d

**Comment by qfritayre** [comment]
My bad. Problem solved. Thx.
