### ISSUE TITLE
Building & running peek on fedora fails

### ISSUE THREAD

**Issue by theIDinside** [phw/peek#1222]
Reproducible on Fedora 37

Steps to reproduce:
Clone repo
Follow build instructions

When running, get error:
(peek:940153): GLib-GIO-ERROR **: 16:14:18.929: Settings schema 'com.uploadedlobster.peek' is not installed

No further information on how to move forward.

**Comment by phw** [comment]
Looks like the schema did not get compiled. Depending on the install locations this should do (run as root):

```
glib-compile-schemas /usr/local/share/glib-2.0/schemas
```

Adjust the install location accordingly.

**Comment by theIDinside** [comment]
> Looks like the schema did not get compiled. Depending on the install locations this should do (run as root):
> 
> ```
> glib-compile-schemas /usr/local/share/glib-2.0/schemas
> ```
> 
> Adjust the install location accordingly.

Is it not possible to build and run peek from the build folder? Is that inherent to the whole gnome settings schema thingy?
