### ISSUE TITLE
\!/ Alternatively you might want to try the Ubuntu packages from the PPA (see above), they probably work just fine on Debian, too. ?

### ISSUE THREAD

**Issue by jordila** [phw/peek#128]
didn't worked in my Debian Jessie ... Packages couldn't be retrieved from http://ppa.launchpad.net/peek-developers

```
Fetched 19.7 kB in 5s (3,597 B/s)
W: Failed to fetch http://ppa.launchpad.net/peek-developers/stable/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/peek-developers/stable/ubuntu/dists/jessie/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
IMHO , in order to save energy, this installation optio should'nt be proposed, but the .deb self-creation  instead .

**Comment by phw** [comment]
Nah, that can't work as the distribution name is different. What I actually meant was downloading the precompiled deb packages and installing them with dpkg should work. But I have removed the misleading comment now, building your own package is the better approach.
