### ISSUE TITLE
Peek close button to the left?

### ISSUE THREAD

**Issue by orschiro** [phw/peek#129]
Dear all, 

I am on Ubuntu 17.04 MATE.

All my applications' close button are on the left but Peek. 

I find this irritating and not intuitive to have an inconsistent desktop experience. 

Can we somehow allow the user to choose where he wants the close button to be?

Yours,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/25062141/94380e40-21c6-11e7-9b05-72e428f5f453.png)

**Comment by phw** [comment]
I can try to fix that. Currently this gets put to the left on Unity. I will see if I can detect how this is configured for Mate and set it accordingly. If I cannot autodetect I will probably add a hidden option to force it.

**Comment by orschiro** [comment]
@phw, thank you!

Does this information maybe help you?

![image](https://cloud.githubusercontent.com/assets/170947/25065445/81f75b42-2210-11e7-8bc2-5a2ff704dc13.png)

**Comment by phw** [comment]
Fixed, can you try the latest development version? I have generalized my approach to determine the position, so this should now work independent of the desktop environment used (previously it used a hard coded check for Unity).

**Comment by orschiro** [comment]
Thank you, @phw!

I just received Peek 1.0.1.

However, the button is still to the right instead of left.

**Comment by phw** [comment]
How did you install peek? From the daily PPA? If so the package was rebuilt 2 hours ago and should be up to date. Please check the package version, it should currently be "1.0.1-0+git509~ppa11~ubuntu17.04.1".

**Comment by orschiro** [comment]
Yes, it is the correct package:

```
orschiro@x230:~$ sudo dpkg -i Desktop/peek_1.0.1-0+git509-ppa11-ubuntu17.04.1_amd64.deb 
[sudo] password for orschiro: 
(Reading database ... 456889 files and directories currently installed.)
Preparing to unpack .../peek_1.0.1-0+git509-ppa11-ubuntu17.04.1_amd64.deb ...
Unpacking peek (1.0.1-0+git509~ppa11~ubuntu17.04.1) over (1.0.1-0+git509~ppa11~ubuntu17.04.1) ...
Setting up peek (1.0.1-0+git509~ppa11~ubuntu17.04.1) ...
Processing triggers for bamfdaemon (0.5.3+17.04.20170406-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for libglib2.0-0:i386 (2.52.0-1) ...
Processing triggers for libglib2.0-0:amd64 (2.52.0-1) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
```

**Comment by phw** [comment]
Pretty strange, works for me on Mate installed on Ubuntu 16.04 with the setting enabled in mate-tweak as shown on your screenshot. Please make sure no instance of Peek is already running and try starting Peek with

    G_MESSAGES_DEBUG=all peek

Then post the output here. It should show some info about how the decoration layout is configured on your system.

**Comment by orschiro** [comment]
```
orschiro@x230:~$ G_MESSAGES_DEBUG=all peek
(peek:7747): Gtk-DEBUG: Connecting to session manager
** (peek:7747): DEBUG: desktop-integration.vala:160: Desktop: MATE
** (peek:7747): DEBUG: application.vala:301: Decoration layout: close,minimize,maximize:menu
** (peek:7747): DEBUG: desktop-integration.vala:160: Desktop: MATE
** (peek:7747): DEBUG: application.vala:41: Loading local settings failed: Failed to open file “./data/gschemas.compiled”: open() failed: No such file or directory
** (peek:7747): DEBUG: application.vala:194: Changed keybinding_toggle_recording  => <Ctrl><Alt>R

** (peek:7747): DEBUG: desktop-integration.vala:160: Desktop: MATE
** (peek:7747): DEBUG: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

Using screen recorder backend ffmpeg
** (peek:7747): DEBUG: desktop-integration.vala:160: Desktop: MATE
** (peek:7747): DEBUG: recording-area.vala:38: Absolute recording area x: 111, y: 93, w: 295, h: 556
** (peek:7747): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:7747): DEBUG: recording-area.vala:58: Clipped recording area x: 111, y: 93, w: 295, h: 556
** (peek:7747): DEBUG: recording-area.vala:69: Scaled recording area x: 111, y: 93, w: 295, h: 556
** (peek:7747): DEBUG: recording-area.vala:38: Absolute recording area x: 111, y: 93, w: 295, h: 556
** (peek:7747): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:7747): DEBUG: recording-area.vala:58: Clipped recording area x: 111, y: 93, w: 295, h: 556
** (peek:7747): DEBUG: recording-area.vala:69: Scaled recording area x: 111, y: 93, w: 295, h: 556
```

**Comment by phw** [comment]
Oh, never mind, my bad. The package in the daily PPA was not up to date, it was rebuild with the minor README change I did eralier. Currently rebuilding, should be ready any moment: https://code.launchpad.net/~peek-developers/+recipe/peek-daily

**Comment by orschiro** [comment]
`511` is working. Cool!

Thank you so much! :-)

![image](https://cloud.githubusercontent.com/assets/170947/25129976/b0b055e2-2440-11e7-821f-2afce5b5286c.png)
