### ISSUE TITLE
Recording works from terminal but not from .desktop

### ISSUE THREAD

**Issue by orschiro** [phw/peek#134]
Dear all, 

Any thoughts on the following problem? How could I debug this?

Peek produces an output file if run from the terminal but not if opened from the `.desktop` file.

**Comment by phw** [comment]
No good idea :) One thing: It is running different installations. E.g. do you have a Flatpak or Snap version installed? Becaus e.g. I have both the OS package and the Flatpak version installed, and my desktop shortcut is currently opening the Flatpak version. On the Flatpak (and probably also Snap) dev versions GIF recording on Gnome Shell is currently broken

**Comment by orschiro** [comment]
Neither did I install Flatpak nor a Snap version.

I am using the latest dev version from the PPA on Ubuntu 17.04 MATE.

Strange...

**Comment by phw** [comment]
You could run `journalctl -f` and see if there is any error output.

**Comment by orschiro** [comment]
Thanks!

I will close this as probably user error.
