### ISSUE TITLE
cannot grab bottom of recording window  ppa 1.0.1 ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by pleabargain** [phw/peek#140]
use case:
record only small portion at top of screen
problem:
cannot 'grab' bottom of recording screen

please see gif showing problem on Ubuntu LTS 16
using latest 1.0.1 ppa
![cannot get bottom of record screen peek 2017-05-23 12-01](https://cloud.githubusercontent.com/assets/640846/26346825/25bf7d7e-3fb0-11e7-997f-100355b9c778.gif)

**Comment by phw** [comment]
I don't fully get the issue. You mean you cannot resize the height because the bottom window edge is outside the window? You should be able to grab the top edge, make the window smaller in height, than pull it up until you see the bottom corner again. Basically the same you'd do with every other window.

The other question is how you ended up with such a large window. Did you use peek on a larger monitor before?

**Comment by pleabargain** [comment]
Hi you said

>  You should be able to grab the top edge, make the window smaller in height, than pull it up until you see the bottom corner again.

but that is exactly what I cannot do... :(

re: monitor:
I have two monitors. One IS larger than the other. HTH.

**Comment by phw** [comment]
So you can't grab the top of the window for resizing? Is this the case for all windows of all apps? This sounds more like a desktop environment issue, not sure what I can do about it in peek :(

**Comment by phw** [comment]
I just experienced this on XFCE where I could not grab the bottom even though it was visible. Seemed to be a theme issue. Maybe it is similar reason you cannot grab the top. What theme are you using? Also is it the same on other windows?

**Comment by phw** [comment]
No response from OP, closing as I don't think this is something Peek can handle. Looks like a theming bug to me.

**Comment by phw** [comment]
There is a similar issue #199 . I can probably work around this by theme, as we now have a nice theme specific CSS selection in the code. But I need to know which theme this is to be able to act on this.

**Comment by gort818** [comment]
It looks like the Radiance theme.

**Comment by pleabargain** [comment]
This is no longer an issue in Peek 1.3.1

thank you
