### ISSUE TITLE
Warn if closed while rendering

### ISSUE THREAD

**Issue by VxMxPx** [phw/peek#142]
Please show a warning if someone try to close application while rendering.
It's constantly happening to me that I click save and then close app, resulting in termination and loss of recorded material.

**Comment by phw** [comment]
Makes sense 👍

**Comment by phw** [comment]
I did this a little bit different: When closing peek while rendering, it will finish rendering / saving the file and show a notification afterwards. What do you think about it? I am no big fan of dialog boxes and of too much interaction with simple apps, so I personally like it. I would at least like to get this released and gather some feedback :)

This commit also fixes the issue that closing whole recording could lead to left over temp files.

**Comment by VxMxPx** [comment]
That's great. I'm glad you did it like this. I agree about dialogs.

_I absolutely love this app btw_ ;)

**Comment by phw** [comment]
Thanks :)
