### ISSUE TITLE
Got error: no images defined

### ISSUE THREAD

**Issue by harryyuanfeng** [phw/peek#143]
I run peek in command line and here is the output. 

I am using Debian and have followed the instruction to install peek. 

`Using screen recorder backend gnome-shell
Recording to file /home/harry/.cache/peek/peekTP7X0Y.mp4
convert: delegate failed `"ffmpeg" -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1310.
convert: unable to open image `/home/harry/.cache/peek/magick-4252MmiayLZTtV21.pam': No such file or directory @ error/blob.c/OpenBlob/2712.
convert: no images defined `/home/harry/.cache/peek/peekCCGM0Y.gif' @ error/convert.c/ConvertImageCommand/3210.
Error: Child process exited with code 1
Temp file delete error: Error removing file: No such file or directory`

**Comment by phw** [comment]
Sorry for the late reply. Can you look at the output of `journalctrl -f` while you encounter this issue? There should be some error message from gnome-shell. Also please let me know the gnome version you are using.

As a workaround use the ffmpeg backend by launing peek with:

    peek -b ffmpeg

**Comment by harryyuanfeng** [comment]
`journalctl -f
No journal files were found.
`
here is output when a start peek.

`peek -b ffmpeg
Requested screen recorder backend ffmpeg
Error: Failed to execute child process "ffmpeg" (No such file or directory)
`
this is what I got with `peek -b ffmpeg`

**Comment by phw** [comment]
Looks like you don't have ffmpeg installed, but that's required.

**Comment by harryyuanfeng** [comment]
Thanks, that was the problem.
