### ISSUE TITLE
A tip and a question

### ISSUE THREAD

**Issue by psychon** [phw/peek#147]
Hi,

I looked at peek because of https://github.com/awesomeWM/awesome/issues/1827. Two things caught my eye:

The following code draws recording view: https://github.com/phw/peek/blob/6dbf715acfe361851613eaf079e202bd39333e46/src/ui/application-window.vala#L198-L214
This is equivalent to the following:
```vala
ctx.set_operator (Operator.CLEAR);
ctx.paint ();

update_input_shape ();

return false;
```
If you take the time to understand https://cairographics.org/operators/#clear, you will see that the CLEAR operator does not use the current source, so it makes no difference if the source is completely transparent or is black. This also makes the `screen_supports_alpha` variable redundant!

The second change is that I dropped the call to `ctx.fill()`. You do not have a current path (no call to e.g. `ctx.rectangle`) and thus you are filling the empty path. Filling the empty path has no effect. Also, what effect should it have? `paint()` just cleared everything already.

------

The second thing concerns the use of shapes. You already use the input shape. Why don't you use the clip/bounding shape? https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-input-shape-combine-region

What I mean is basically the following patch:
```diff
--- application-window.vala.orig	2017-06-13 09:14:11.374492099 +0200
+++ application-window.vala	2017-06-13 09:14:32.210933971 +0200
@@ -382,6 +382,7 @@ namespace Peek.Ui {
       }
 
       this.input_shape_combine_region (window_region);
+      this.shape_combine_region (window_region);
     }
 
     private Widget? get_fallback_app_menu () {
```
Shaped windows also work without a compositing manager and an ARGB visual. I have never used Peek and I am not sure how it works, but the above (when no countdown is running...) could help.

Cheers,
Uli

**Comment by phw** [comment]
Thanks a lot, your feedback is very much appreciated. The documentation on those features is a bit scarce and so are the examples using it. I remember this was quite some trial and error based on some (maybe not so good example) until this worked as I wanted it. So getting some feedback from somebody who knows more about the internals here is awesome.

I tried your changes quickly and they seem to do what I want. Now I just need to test this on non compositing WM :)

**Comment by psychon** [comment]
> I remember this was quite some trial and error based on some (maybe not so good example) until this worked as I wanted it.

Rule of thumb: Shapes can only make a pixel fully transparent or opaque. If you want some partial transparency, then it's not helping you. So the count down in https://raw.githubusercontent.com/phw/peek/master/data/screenshots/peek-recording-itself.gif "should not work" with the shapes (it looks half-see-through, for that you really need a compositing manager and an ARGB visual).

Feel free to ping me if these changes broke anything and people start complaining. :-)
