### ISSUE TITLE
Settings schema 'com.uploadedlobster.peek' is not installed

### ISSUE THREAD

**Issue by orschiro** [phw/peek#158]
Dear all, 

Can someone please help me with this problem?
```
orschiro@x230:~/Desktop$ peek

(peek:22441): GLib-GIO-ERROR **: Settings schema 'com.uploadedlobster.peek' is not installed

Trace/breakpoint trap (core dumped)
orschiro@x230:~/Desktop$ sudo apt install peek
Reading package lists... Done
Building dependency tree       
Reading state information... Done
peek is already the newest version (1.0.3-0+git573~ubuntu17.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by phw** [comment]
Is this latest development version from PPA? There were some changes to the build system yesterday that did not work well at first and needed fixing. I will look into the PPA builds and see if there were any issues with the latest revision.

**Comment by phw** [comment]
I can confirm this with 1.0.3-0+git573, the files are installed all into the wrong place. But fixed with latest latest Peek 1.0.3-0+git576. Please run a full `apt update` and then `apt install peek` to install that.

**Comment by orschiro** [comment]
It got fixed. Thank you! :-)

**Comment by roxma** [comment]
I have the same issue on manjaro.

I've tried master HEAD, v1.0.3, v1.0.1. none of them work

**Comment by phw** [comment]
> I have the same issue on manjaro.

No, it's not the same issue, this here is specifically about a packaging error in the Ubuntu packages.

How did you install Peek? This sounds like whatever package you use, it does not install the schema properly. Try running as root:

    glib-compile-schemas /usr/share/glib-2.0/schemas

**Comment by roxma** [comment]
> How did you install Peek?

I install it from source. (There's [wired issue](https://github.com/roxma/ncm-phpactor) with the flatpak package I'm using currently.)

Here's my installation script:

```bash
#!/bin/sh

set -x

mkdir -p ~/.local/src/
cd ~/.local/src/

if [ ! -d peek ]
then
    git clone --depth 1 https://github.com/phw/peek.git
fi
mkdir peek/build
cd peek/build
cmake -DCMAKE_INSTALL_PREFIX=~/.local/stow/peek ..
make
make install


cd ~/.local/stow
stow peek
```

>  This sounds like whatever package you use, it does not install the schema properly. Try running as root:

Unfortunately `glib-compile-schemas /usr/share/glib-2.0/schemas` didn't help.

```
[roxma@roxma-pc ~]$ sudo glib-compile-schemas /usr/share/glib-2.0/schemas
[sudo] password for roxma: 
[roxma@roxma-pc ~]$ peek

(peek:9337): GLib-GIO-ERROR **: Settings schema 'com.uploadedlobster.peek' is not installed

Trace/breakpoint trap (core dumped)
```

Do I need to open another issue?

**Comment by phw** [comment]
Stow and GSettings schemas need some extra work: whenever you stow or unstow an application in `~/.local` which provides a glib schema you will need to run 

    glib-compile-schemas ~/.local/share/glib-2.0/schemas

Also by default applications might not pick up GSettings schmeas form `~/.local`, you likely will have to expand your `$XDG_DATA_DIRS`:

    export XDG_DATA_DIRS=$HOME/.local/share/:$XDG_DATA_DIRS

Best set this in your `~/.profile`.

By far the easier solution would be to build [peek from AUR](https://aur.archlinux.org/packages/peek/) and install it as a proper package :)

> Do I need to open another issue?

Let's see if we could handle it here :) If the above doesn't help, yes please, add another issue. It's easier to keep track of than to discuss in a long closed issue.

**Comment by roxma** [comment]
@phw  It's working. Thank you very much!
