### ISSUE TITLE
Arch Package

### ISSUE THREAD

**Issue by atomfrede** [phw/peek#16]
Hi Philipp,

the follow up of ou [twitter](https://twitter.com/phwolfer/status/771280021885427716) discussion. I can't install peek via the aur (using yaourt) with following error message:

```bash
==> Beginne check()...
Running tests...
Test project /tmp/yaourt-tmp-fred/aur-peek/src/peek
    Start 1: test-desktop-integration
1/3 Test #1: test-desktop-integration ............................***Exception: Other  0.09 sec
    Start 2: screen-recorder-test-recording-area
2/3 Test #2: screen-recorder-test-recording-area .................***Exception: Other  0.08 sec
    Start 3: test-screen-recorder-command-line-screen-recorder
3/3 Test #3: test-screen-recorder-command-line-screen-recorder ...***Exception: Other  0.09 sec

0% tests passed, 3 tests failed out of 3

Total Test time (real) =   0.26 sec

The following tests FAILED:
	  1 - test-desktop-integration (OTHER_FAULT)
	  2 - screen-recorder-test-recording-area (OTHER_FAULT)
	  3 - test-screen-recorder-command-line-screen-recorder (OTHER_FAULT)
Errors while running CTest
make: *** [Makefile:150: test] Fehler 8
==> FEHLER: Ein Fehler geschah in check().
    Breche ab...
==> FEHLER:Makepkg konnte peek nicht erstellen.

```

**Comment by oleerik** [comment]
Hello! I experienced the same issue while trying to install it in a tmux session. It seems like the tests needs some X session to be accessible to install.

All I did was run a normal xterm window and install it there. Worked fine.

**Comment by phw** [comment]
@oleerik Thanks for the hint, that would make sense. I already got the same report once, and could not find out what it was.

One option is to build the package with the makepkg `--nocheck` option. If using AUR helpers you have to look there if and how this can be done. Or edit the PKGBUILD and remove the check function.

Not sure whether I can do something about the tests. Maybe only execute them when inside a X session?

**Comment by atomfrede** [comment]
@oleerik @phw Thanks, will try it out!

**Comment by atomfrede** [comment]
Removing check from the PKBUILD works just fine! Thanks for the hint @oleerik

**Comment by oleerik** [comment]
I believe this "issue" could be closed? Maybe adding it to some FAQ might be a good idea.

**Comment by phw** [comment]
As a final update: I have disabled the checks in the AUR package for now. I still don't understand what was happening, if I found out I will re-enable the checks again.
