### ISSUE TITLE
Peek creates files with unusual default permissions

### ISSUE THREAD

**Issue by Moini** [phw/peek#161]
Not sure if this is intended to be a feature, but it's causing issues for me.

By default, all programs that I use on a daily basis create files with 644 permissions (owner: read/write, group/others: read). 

However, Peek creates files that can only be read/written by the owner, and nobody else can access them. This causes issues for me, when I want to share the files.

Version 1.0.3 on Linux Mint 18.1

**Comment by phw** [comment]
I can reproduce this. I guess this has to do that the files are created as temporary files and just copied over then. I will look into it.

**Comment by Moini** [comment]
Thank you, @phw !

**Comment by Moini** [comment]
Great, thank you, @phw !
