### ISSUE TITLE
How to create videos?

### ISSUE THREAD

**Issue by ShortAndSimple** [phw/peek#163]
I couldn't find an option. In readme, it is stated to change to video in the preferences but I couldn't find it :( Please help.

**Comment by phw** [comment]
I am not entirely sure what your question is, so I give you a couple of answers:

- You start recording a video by clicking the "Record" button at the top of Peek's window
- You can change the output format (GIF, WebM or MP4) in the preferences.
- The preferences can be opened in the app menu.
- The app menu is located in the top bar if you are using Gnome or Unity. If you are using a different desktop environment or the application menu is disabled the Peek window will contain an icon that opens the app menu.

**Comment by phw** [comment]
Issue resolved by support in gitter
