### ISSUE TITLE
W: Failed to fetch  package 404 not found

### ISSUE THREAD

**Issue by vivex** [phw/peek#164]
Getting following error on apt-get update in ubuntu 14.04 64 Bit

```
W: Failed to fetch http://ppa.launchpad.net/peek-developers/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/peek-developers/stable/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
```

**Comment by phw** [comment]
Ubuntu 14.04 is not supported by the PPA, due to the GTK version available there. But people have reported the snap package works for them, see https://github.com/phw/peek/issues/54

Please try installing snap and then install peek with:

    sudo snap install peek --edge

**Comment by phw** [comment]
Closing for now, please let me know if the snap approach doesn't work for you.

**Comment by pnatraj** [comment]
not sure this this issue is very specific to me but i am running ubuntu 14 and i am unable to install peek through snap

# sudo snap install peek --edge
ZOE ERROR (from /usr/lib/snap/snap): zoeParseOptions: unknown option (--edge)
ZOE library version 2006-07-28

**Comment by phw** [comment]
@pnatraj I no longer provide or support a snap package for Peek. For details please see https://www.reddit.com/r/Ubuntu/comments/870bcn/snap_support_for_peek_screen_recorder_discontinued/
