### ISSUE TITLE
build is failing according to the readme badge

### ISSUE THREAD

**Issue by matkoniecz** [phw/peek#165]
https://github.com/phw/peek#peek---an-animated-gif-recorder

**Comment by phw** [comment]
Yes, I have to look into it, thanks for the heads up. The tests are all crashing for some reason, but I don't see any change on Peek's side to cause this. It could be related to recent OS upgrade at Travis CI, will investigate.

**Comment by phw** [comment]
Fixed again without changes on my side, seems to have been a travisci issue
