### ISSUE TITLE
For the FAQ: "How to prevent Peek from freezing my computer?"

### ISSUE THREAD

**Issue by orschiro** [phw/peek#169]
Seeking some help and advice.

Sometimes after recording and showing me the save dialog window, my computer completely freezes and the system becomes unresponsive. By the LED of my laptop, I can see that a lot of processing is happening. Last time I waited for 20 minutes but the situation did not restore and I had to do a cold shutdown losing all my data I worked on.

How can I prevent Peek from completely freezing my machine? I prefer the recording to not complete than to lose my data and do a cold shutdown. 

Thanks!

----

Peek 1.0.3 on Solus Budgie.

**Comment by peteruithoven** [comment]
Also see: https://github.com/phw/peek/issues/125

**Comment by orschiro** [comment]
@peteruithoven thanks! I will watch the other issue and if a solution or workaround emerges, create the FAQ item. 

For now, I am using the .webm file format, especially for larger recordings. But I am not sure if that's a proper response to the FAQ question because it doesn't use the .gif format.

What do you think?

**Comment by phw** [comment]
My preferred solution would be to get #125 fixed. Probably I need to ask the ImageMagick guys why the resource usage is sometimes so ridiculous high when optimizing GIF files. 

I can still add a FAQ section though, as manual tweaking of ImageMagick's resource limits might be needed in some cases no matter what I do here.

**Comment by orschiro** [comment]
So let's wait until we have more information on this. Thanks for keeping this up!

**Comment by phw** [comment]
I will close this, as Peek now uses either ffmpeg or (if installed) gifski. Both solution don't have this massive RAM usage of ImageMagick and perform quite well, so I don't think this is an issue anymore.
