### ISSUE TITLE
Suppress notifications while recording?

### ISSUE THREAD

**Issue by orschiro** [phw/peek#173]
Frequently it happens to me that a notification is popping up while recording the screen, causing me to re-record.

This is very annoying. What do you think of adding a feature to peek that automatically suppresses notifications during recording time?

**Comment by phw** [comment]
That sounds like a very useful idea. I just don't know whether this can be done and if so how. Probably also desktop related. Will need some research, if you know anything about this let me know.

**Comment by orschiro** [comment]
Thanks for your prompt feedback!

I can only help by sharing the following links with you:

- https://launchpad.net/nonotifs
- https://ubuntu-mate.community/t/disable-notifications/8028

Hope that helps!

**Comment by phw** [comment]
So I had some look into this, and I found no really good way of doing this. All the solutions are desktop specific. In general it would always be what the nonotifs code does for Ubuntus notify-osd: Stop the process handling the notifications, launch up a replacement that captures the notifications silently. When finished start the notification handler again and resend all missed notifications.

But this would be different for every desktop environment and I really don't want to go into this. If there would be a generalized separate service dealing with this I would consider using it, but given my lack of time I won't be the one writing such a service.
