### ISSUE TITLE
Peek chooses non default file manager

### ISSUE THREAD

**Issue by Yanpas** [phw/peek#176]
I use Xfce, mine default fm is Thunar. Peek launches Nautilus instead

**Comment by phw** [comment]
Can you run peek with

```
G_MESSAGES_DEBUG=all peek
```

and then save a file with "Launch file manager" enabled, then post the output here.

Peek tries various strategies to open the file manager, I am curious what it chooses for your environment.

**Comment by Yanpas** [comment]
Here is [gist](https://gist.github.com/Yanpas/f8cc7615b2619cb15ab7ebac003468e3)

**Comment by phw** [comment]
Ok, so it's using the org.freedesktop.FileManager1 DBUS service, which is the default to use if available. Now we have to figure out how this is working in this case. I fear for XFCE it is enough that Nautilus is installed, as Nautilus provides this service (its not the only file manager doing so, though).

Related issue for XFCE and Thunar: https://bugzilla.xfce.org/show_bug.cgi?id=12414

I will try to figure out how to best solve this. Maybe I will just blacklist the usage of this service for XFCE.

**Comment by phw** [comment]
Just to have this here: Obviously uninstalling Nautilus would be a workaround, but likely not one you want (there is for sure a reason you have it installed).

**Comment by Yanpas** [comment]
`Maybe I will just blacklist the usage of this service for XFCE`
I guess it would be better to do nothing here since it's Xfce problem. Soon Xfce may receive support for this feature. May be closed, thanks :)

**Comment by phw** [comment]
After further though I decided to do nothing and close this. As you said, once XFCE supports this itself it is a non-issue, and any workaround I introduce would likely break things. Further more if I blacklist this service for XFCE, the feature would be broken completely when running inside Flatpak, as this relies in this service (due to the sandboxing).
