### ISSUE TITLE
Newer FFMPEG versions

### ISSUE THREAD

**Issue by rkantos** [phw/peek#181]
I tried using Peek with ffmpeg 3.3 from https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-3, but received error:
`Using screen recorder backend ffmpeg
ffmpeg: relocation error: /usr/lib/x86_64-linux-gnu/libavutil.so.55: symbol vaCreateSurfaces, version VA_API_0.33.0 not defined in file libva.so.1 with link time reference
Error: Child process exited with code 127
Error: Child process exited with code 127
Recording canceled with return code 127
`.

Any idea when we could get support for newer ffmpeg versions? They have some VAAPI features, which could enable better performance for some hardware combinations. I tried with stable and daily versions of peek.

**Comment by phw** [comment]
This is an issue with ffmpeg and VAAPI, looks like you need a newer version of libva than you have installed. This is not something Peek deals directly with.

No issues here using ffmpeg 3.3.3 with libva 1.8.3.
