### ISSUE TITLE
When i open Peek on my Ubuntu16.04, the window is black instead of transparent.

### ISSUE THREAD

**Issue by PhilipCard** [phw/peek#182]
I have a problem i'm trying to solve for a while but did not find a solution yet.
When i open Peek on my Ubuntu16.04, the window is black instead of transparent.
I've tried to uninstall and reinstall the application but always end up with the black window that does not record anything !

Does someone has a solution to that problem ?
Here's a screenshot of my problem :
![screenshot at 2017-08-30 14 27 26](https://user-images.githubusercontent.com/31930470/30386729-95ac5e24-9878-11e7-8da0-2099df054b3d.png)

**Comment by phw** [comment]
In the currently released version you need compositing enabled in your window manager. Depending on the desktop environment / window manager you use there should be some option to enable it.

The current git version works without compositing.

**Comment by phw** [comment]
I close this as I strongly suspect the missing compositing is the issue here. If this does not solve your problem feel free to comment again with additional info on the desktop environment and / or window manager you are using and I will reopen.
