### ISSUE TITLE
Package imagemagick is not installed

### ISSUE THREAD

**Issue by ralexrdz** [phw/peek#183]
I've followed instruction to install peek on a `Linux Mint LMDE Betsy` with `Debian 4.8.4-1`,  and I got stuck when
`sudo dpkg -i peek-1.0.3-Linux.deb`
gave me this error
`Package imagemagick is not installed`
I tried to install it via `sudo apt-get install imagemagick` and got `/usr/local/bin/magick` created

Still, installing peek gives me same error...

I'm I missing something?
Is there a way to flip this around?

**Comment by phw** [comment]
It is very unusual that a package from repositories creates anything in `/usr/local`, that looks strange. You are sure the package got installed?

What is the output of

    dpkg -s

Also you need the `convert` utility installed, does it exist?

**Comment by ralexrdz** [comment]
Thanks man! Lots of help! The problem was that apt installation failed got stuck on some dependacy, I tried to  install imagemagick manually, and created that usr/local folder. I uninstall that, fix dependancy and now it works!

**Comment by phw** [comment]
Great ist works now :)
