### ISSUE TITLE
Unable to record longer gif's

### ISSUE THREAD

**Issue by StephanMeijer** [phw/peek#196]
```
convert-im6.q16: unable to get registry ID `cache:hosts' @ error/registry.c/GetImageRegistry/201.
convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
convert-im6.q16: cache resources exhausted `/home/steve/.cache/peek/magick-11501eBiekymKg91r.pam' @ error/cache.c/OpenPixelCache/3945.
Error: Child process exited with code 1
File save error: Error when getting information for file “/home/steve/.cache/peek/peekXXXXXX.gif”: No such file or directory
Temp file delete error: Error removing file /home/steve/.cache/peek/peekXXXXXX.gif: No such file or directory
```

```
Linux steve-XPS-13-9360 4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
```

**Comment by StephanMeijer** [comment]
Could be a duplicate of #188

**Comment by phw** [comment]
Yes, duplicate, but see especially #125 . There are changes in the current development release to get rid of ImageMagick, which should eliminate those issues finally.

Can you try the latest development release and tell me how this works for you?

**Comment by StephanMeijer** [comment]
Will try and feedback :)

**Comment by StephanMeijer** [comment]
Seems to work!

**Comment by StephanMeijer** [comment]
**It does not :(**

```
Using screen recorder backend gnome-shell
Recording to file /home/steve/.cache/peek/peekXXXXXX.avi

(peek:21601): Gtk-WARNING **: Failed to measure available space: The specified location is not supported
convert-im6.q16: unable to get registry ID `cache:hosts' @ error/registry.c/GetImageRegistry/201.
convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
convert-im6.q16: cache resources exhausted `/home/steve/.cache/peek/magick-21655BDj5nXDmZGe5.pam' @ error/cache.c/OpenPixelCache/3945.
convert-im6.q16: no images defined `/home/steve/.cache/peek/peekXXXXXX.gif' @ error/convert.c/ConvertImageCommand/3258.
Error: Child process exited with code 1
File save error: Error when getting information for file “/home/steve/.cache/peek/peekXXXXXX.gif”: No such file or directory
Temp file delete error: Error removing file /home/steve/.cache/peek/peekXXXXXX.gif: No such file or directory
```

**Comment by phw** [comment]
This does not seem to be the latest code you are running. Please try installing via the daily PPA (see https://github.com/phw/peek/blob/master/README.md#ubuntu) or from source. 

Interesting is the `Gtk-WARNING **: Failed to measure available space` warning, not sure where this comes from, is there anything special about your `/home/steve/.cache` folder (tmpfs or something)?

If you want to continue using the stable version you must be aware that ImageMagick needs quite some RAM and disk space for processing GIFs (several GB are not uncommon). Peek 1.1.0 will by default give ImageMagick 90% of your free RAM, so make sure you have plenty of RAM free when recording. If ImageMagick runs out of RAM it will use the disk instead.

**Comment by StephanMeijer** [comment]
I installed by source.

**Comment by phw** [comment]
That's strange, as it still uses ImmageMagick, and the latest code should default to using ffmpeg. Can you try running it with `PEEK_POSTPROCESSOR=ffmpeg peek`?

Or double check if you are running the correct binary. A source install will default to be in `/usr/local/bin/peek`.

**Comment by StephanMeijer** [comment]
It uses `ffmpeg` and `convert` as far as I can read using `htop`. It doesn't use much RAM (like 1 - 2 % of 16 GB)

`$ whereis peek`
```
peek: /usr/bin/peek /usr/local/bin/peek /usr/share/man/man1/peek.1.gz
```

**Comment by phw** [comment]
You are probably running the older packaged version from `/usr/bin/peek`, please run the source install from `/usr/local/bin/peek`

**Comment by StephanMeijer** [comment]
Using `/usr/local/bin/peek` outputs `ffmpeg`-things. Binaries don seem to be equal. Will comment on that later.

**Comment by StephanMeijer** [comment]
`/usr/local/bin/peek` seems to work. Thanks. Maybe I didn't remove the old version properly.
