### ISSUE TITLE
Hi-DIP screens are not treated right

### ISSUE THREAD

**Issue by fb87** [phw/peek#20]
Peek always renders a smaller and (in the upper left direction) displaced area of my screen. Obviously because of doubled resolution in every direction. Please fix this. :)

**Comment by phw** [comment]
I gave to see how Gtk handles this and how it affects coordinates. But probably the new recording method mentioned in issue #1 will help here , too

**Comment by phw** [comment]
This was fixed with pull request #22

**Comment by fb87** [comment]
Works, thanks!
