### ISSUE TITLE
Feature Request: Provide flag to start peek without the top bar

### ISSUE THREAD

**Issue by McKean** [phw/peek#203]
Basically enabling the possibility to to start peek with minimal UI (or no UI at all essentially).  
This way it could be implemented easier programmatically for i3 as an example.
When using this in stacked mode it will cut off the top part
![screenshot](https://dl.dropbox.com/s/iq3jrzxl86ioxgw/shot-2017-10-26-17-54-50.png?dl=0)

See https://github.com/phw/peek/pull/200 for more information.

**Comment by phw** [comment]
I see how this makes sense in some cases. As you are limited to the keyboard shortcuts then this is definitely an advanced option, but I could even show a small hint "Press Ctrl+R to start" into the window.

I will consider this, but not high priority right now.

**Comment by McKean** [comment]
yeah, you could use the semi transparent surface and show that text on it x/y centered. once you start the capture it will not show anymore and everyone is happy. Perhaps also allow a flag which will start capturing directly. That would follow the gnu way of being able to plug in/out applications easily.

That would make it possible to have a key binding in i3 for example which will stack that window and start recording, when stoped the file is generated and the application is closed. Ideally then have dropobox uploader take the fila and generate a public link for sharing.

**Comment by phw** [comment]
I just implemented this as it was easy enough to do, start peek with `--no-headerbar`. I first feared hiding the headerbar would break the layout, but at least here it looks ok.

I will keep this issue open as I want to add that indicator showing the keyboard shortcut to use. Also maybe some testing with more themes.

**Comment by McKean** [comment]
Very nice!
![screenshot](https://dl.dropbox.com/s/wmnfm2fsobsdw02/shot-2017-11-07-15-05-01.png?dl=0)

**Comment by McKean** [comment]
so when doing `--no-headerbar --start` it will start right away, am I right? then `ctrl + alt r` and it will stop?

**Comment by phw** [comment]
Not quite.  You first have to start peek  with `--no-headerbar`, than another call to `peek --start` will start recording (in all open windows if you have opened multiple). Something like this:

```
peek --no-headerbar &
peek --start
```

You can stop again later with
```
peek --stop
```

But I probably should change Peek so that `peek --start` first opens a new window, if there is no window yet. Than `peek --no-headerbar --start` would work.

**Comment by McKean** [comment]
ah gotcha. sorry for my post edit...

so ideally: `peek --no-headerbar --start --autoclose --type gif --file ~/gifs/temp.gif`

**Comment by McKean** [comment]
although perhaps it might be better to do as you mentioned:  
`peek --no-headerbar`  
`i3 window modifications (stacking)`
`peek --start --autocolose --type gif --file $(myfile)`
`do something with $(myfile)`

**Comment by phw** [comment]
It's likely I will release this feature as is in 1.2.0 and improve the user experience later on.

**Comment by phw** [comment]
See #234
