### ISSUE TITLE
Screencast is sped up

### ISSUE THREAD

**Issue by fbruetting** [phw/peek#206]
I run Fedora 27 beta with Wayland on a UHD screen. Settings are 10 fps and resolution reduction by the factor 2.

I just created a screencast, and somehow the speed of the GIF is about doubled, compared to reality.

**Comment by phw** [comment]
Please see #190 , seems to be the same issue. But I closed #190 because it magically went away, and it didn't look like a Peek issue but rather some oddity with the screen recording in GNOME Shell.
