### ISSUE TITLE
Settings schema error after trying to build rpm for CentOS

### ISSUE THREAD

**Issue by darkvertex** [phw/peek#209]
I'm probably doing something wrong but I wanted to ask in case someone knows...

If I grab this file: https://github.com/phw/peek/blob/master/rpm/peek.spec
then yum install all my dependencies and all, then do `rpmbuild -v -bb --clean peek.spec` and install the resulting rpm, it seems to produce a valid rpm but when I try to run `peek` I get:
```
(peek:30648): GLib-GIO-ERROR **: Settings schema 'com.uploadedlobster.peek' is not installed

Trace/BPT trap (core dumped)
```

Furthermore, it so happens that when I build it locally like this:
```
cd ./build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
make
```
then run `./peek` it works but if I'm not inside the `./build` subfolder, I get the same error as above.

Is there a special flag I can pass to peek so it knows where the settings schema is? Does anyone know why peek is looking in the current working directory for this?

**Comment by darkvertex** [comment]
`glib-compile-schemas /usr/share/glib-2.0/schemas` made it work from any folder, yay!

Now I just need to figure out how to get my rpm to do that for me. Tried to put `glib-compile-schemas %{buildroot}/%{_datadir}/glib-2.0/schemas` in the `%install` block but it didn't want to run when building the rpm since it requires root. I guess it needs to go somewhere else...

In any case, thanks a lot for the tip, I am closer to making it work! Will post here if and when I am successful.

**Comment by darkvertex** [comment]
Woohoo! Got it:

```
%post
glib-compile-schemas /usr/share/glib-2.0/schemas
```

Added that, now my rpm works. My CentOS7 rpm is good, huzzah! Thanks again.

**Comment by phw** [comment]
Great to hear you got it working. I am not sure how to handle this in the .spec file properly. It seems not to be necessary for Fedora, probably dnf runs this automatically when necessary.

Currently the .spec is pretty Fedora specific anyway :)
