### ISSUE TITLE
Unable to install Peek Failed to read from snapd: Error receiving data: Connection reset by peer

### ISSUE THREAD

**Issue by pasniak** [phw/peek#210]
In Ubuntu 17.10. This is after installing from "Ubuntu Software" GUI.

**Comment by phw** [comment]
I can't say for sure and can't test it for now, but try executing the following commands from command line:

    sudo snap install gnome-3-26-1604
    sudo snap connect peek:gnome-3-26-1604 gnome-3-26-1604:gnome-3-26-1604

I currently would recommend to install Peek via command line. Peeks needs to be connected to the gnome-3-26-1604 snap, and snap does not yet fully automate this connection. The current status is that the second of above commands should be done automatically on installation, but installing gnome-3-26-1604 is still a manual step. I know the snap developers work on automating that, too, but it probably will take a few releases of snapd until that works.

**Comment by pasniak** [comment]
That worked (after a 150MB download). 

Thanks!

**Comment by phw** [comment]
> That worked (after a 150MB download).

Good to hear :)

Yeah, that's how Snap (or Flatpak) works. Since everything is bundled the sizes increase. But that gnome-3-26-1604 snap can be shared between applications, thus the file size of the Peek snap can be a bit lower.
