### ISSUE TITLE
Problem install peek on CentOS 7

### ISSUE THREAD

**Issue by animan01** [phw/peek#211]
I can not install Peek on CentOS 7. Maybe someone has detailed instructions on installing Peek?

**Comment by phw** [comment]
Installations instructions are at https://github.com/phw/peek#installation

What problems do you actually have? As there are no CentOS packages I am aware of you can either install from source or try the Fedora packages and see if they are installable (probably not). Another option would be Flatpak, but not sure how this is supported in CentOS.

**Comment by phw** [comment]
Another option is of course using the AppImage, that's maybe the easiest way if it is working on CentOS 7.

**Comment by animan01** [comment]
From source not work correctly.

> $ cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
> -- Found Vala: /usr/bin/valac (found version "0.34.6") 
> -- Found Vala: /usr/bin/valac (found suitable version "0.34.6", minimum required is "0.22") 
> -- checking for module 'gtk+-3.0>=3.14'
> --   package 'gtk+-3.0>=3.14' not found
> CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:279 (message):
>   A required package was not found
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
>   CMakeLists.txt:31 (pkg_check_modules)
> 
> 
> -- checking for module 'cairo'
> --   package 'cairo' not found
> CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:279 (message):
>   A required package was not found
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
>   CMakeLists.txt:32 (pkg_check_modules)
> 
> 
> -- checking for module 'keybinder-3.0'
> --   package 'keybinder-3.0' not found
> CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:279 (message):
>   A required package was not found
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
>   CMakeLists.txt:36 (pkg_check_modules)
> 
> 
> CMake Error at CMakeLists.txt:57 (if):
>   if given arguments:
> 
>     "VERSION_EQUAL" "3.16" "OR" "VERSION_GREATER" "3.16"
> 
>   Unknown arguments specified
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "Peek/peek/build/CMakeFiles/CMakeOutput.log".


Example, keybinder was installed - https://i.imgur.com/glYcHyj.png

**Comment by phw** [comment]
This sounds like you are missing the corresponding development packages. I don't know about the package naming in CentOS, but you likely need to install the development packages for gtk3, cairo and keybinder3. The package names likely end with `-devel`, something like gtk3-devel, keybinder3--devel etc.

**Comment by animan01** [comment]
Hm...really does work :)

**Comment by animan01** [comment]
**phw**, thanks for helping!

**Comment by kena0ki** [comment]
I also succeeded local install. And I needed to install ffmpeg for animated gif after local install as described at Fedora in Readme.
