### ISSUE TITLE
Consider / propose as option / default to new high-quality GIF encoder gifski

### ISSUE THREAD

**Issue by ronjouch** [phw/peek#212]
@pornel of ImageOptim/PNGQuant fame just released a first version of gifski ([website](https://gif.ski/), [github](https://github.com/ImageOptim/gifski)). Quoting the website,

> Highest-quality GIF encoder based on [pngquant](https://pngquant.org/).
> 
> [gifski](https://gif.ski/) converts video frames to GIF animations using pngquant's fancy features for efficient cross-frame palettes and temporal dithering. It produces animated GIFs that use thousands of colors per frame.
> ![demo](https://camo.githubusercontent.com/07bffc77a39484c0d8fed9aa9e20b74969d3fc7f/68747470733a2f2f6769662e736b692f64656d6f2e676966)
> It's a CLI tool, but it can also be compiled as library for seamelss use in other apps (note that for closed-source apps you need a commercial pngquant license).

Would be awesome for Peek to be able to directly use it. Probably as an option (?) as I guess it means good-looking but heavy GIFs, which depending on the use case may not be the user-desired tradeoff.

**Comment by phw** [comment]
This looks like an awesome tool. I will give this a test run as soon as possible and implement this in peek. Another option for replacing ImageMagick finally :)

**Comment by phw** [comment]
Here we go with a first quick implementation. For now hidden behind an environment variable. To test install the gifski executable somewhere in your `$PATH` and run latest peek from git with:

    PEEK_POSTPROCESSOR=gifski peek

Looking good so far. I haven't done many tests, but the quality seems to be great. But the images are significantly larger, in my tests the size was roughly doubled.

I like gifski and want to keep it as an option, but use ffmpeg by default. Not yet sure how to best expose this option to the user.

**Comment by phw** [comment]
Some more observations: Rendering the GIF takes way more time than with ffmpeg, but memory usage stays low all the time :) Quality is much better. I will try to upload an example later.

**Comment by ronjouch** [comment]
@phw installed gifski from cargo (running `gifski --help` works), built peek from source and ran it with `PEEK_POSTPROCESSOR=gifski`.

But before we talk gifski I need help with the build, my self-built `peek` is borked: with or without the `PEEK_POSTPROCESSOR` variable, the output GIF is always a single frame (around 20kB or 100kB, depending on what I captured).

This is the first time I build peek, so I may have done something wrong. Ubuntu 16.04.3, followed all [build peek from source](https://github.com/phw/peek#from-source) steps except the final `make install`, which felt undesired (since I have a ppa install), and unnecessary (since the docs mention I can *"Run directly from source"* after build). Build went fine after installing the 👍 documented [deps](https://github.com/phw/peek#requirements), and my settings are: Format=GIF, Delay=2, Framerate=5, Downsampling=1, Cursor=true.

HALP?

Log:

```
/opt/peek/build  ± master  /opt/peek/build/peek

** (peek:27351): WARNING **: Binding '<Ctrl><Alt>R' failed!
Using screen recorder backend ffmpeg
ffmpeg version 3.3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-4) 20170820
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
[x11grab @ 0x4aa5080] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':0+1288,120':
  Duration: N/A, start: 1509717443.545184, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1233x547, 5 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> pam (native))
Press [q] to stop, [?] for help
Output #0, rawvideo, to '/home/ronj/.cache/peek/peekPTH08Y.pam':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: pam, rgb24, 1233x547, q=2-31, 200 kb/s, 5 fps, 5 tbn, 5 tbc
    Metadata:
      encoder         : Lavc57.89.100 pam
frame=   20 fps=5.6 q=-0.0 Lsize=   39520kB time=00:00:04.00 bitrate=80936.7kbits/s speed=1.11x
video:39520kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
ffmpeg version 3.3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-4) 20170820
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, image2, from '/home/ronj/.cache/peek/peekPTH08Y.pam':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 8093668 kb/s
    Stream #0:0: Video: pam, rgb24, 1233x547, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (pam (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/home/ronj/.cache/peek/peekUQXZ8Y.png':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: png, rgba, 16x16 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 5 fps, 5 tbn, 5 tbc
    Metadata:
      encoder         : Lavc57.89.100 png
[Parsed_palettegen_1 @ 0x52c03e0] 255(+1) colors generated out of 2082 colors; ratio=0.122478
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.20 bitrate=N/A speed=3.69x
video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version 3.3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-4) 20170820
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, image2, from '/home/ronj/.cache/peek/peekPTH08Y.pam':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 8093668 kb/s
    Stream #0:0: Video: pam, rgb24, 1233x547, 25 tbr, 25 tbn, 25 tbc
Input #1, png_pipe, from '/home/ronj/.cache/peek/peekUQXZ8Y.png':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Video: png, rgba(pc), 16x16 [SAR 1:1 DAR 1:1], 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 (pam) -> fps
  Stream #1:0 (png) -> paletteuse:palette
  paletteuse -> Stream #0:0 (gif)
Press [q] to stop, [?] for help
Output #0, gif, to '/home/ronj/.cache/peek/peekERJ38Y.gif':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: gif, pal8, 1233x547, q=2-31, 200 kb/s, 5 fps, 100 tbn, 5 tbc (default)
    Metadata:
      encoder         : Lavc57.89.100 gif
frame=    1 fps=0.0 q=-0.0 Lsize=      27kB time=00:00:00.01 bitrate=22008.8kbits/s speed=0.321x
video:26kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.029736%

```

**Comment by ronjouch** [comment]
@phw I updated a lot my debug info, please read it through GitHub if you read it beforehand the (un-updated) notification email 🙂

**Comment by phw** [comment]
This sounds an awful lot like the issues reported at https://github.com/phw/peek/issues/198

I have no idea really, especially since I did not change anything in the recording itself. If you run

    PEEK_POSTPROCESSOR=imagemagick ./peek

you should get exactly the same behavior as with Peek 1.1.0, does this make a difference?

**Comment by phw** [comment]
It's interesting, the initial ffmpeg command for recording the video (pam file) shows `time=00:00:04.00` at the end. The later ffmpeg commands loading the file show `Duration: 00:00:00.04`. Something is wrong here. I have to refactor the recording part anyway (writing the data to that pam file only made sense in combination with imagemagick).

**Comment by ronjouch** [comment]
@phw

> This sounds an awful lot like the issues reported at #198

Indeed, thanks for the pointer 👍.

> I have no idea really, especially since I did not change anything in the recording itself. If you run
>
> `PEEK_POSTPROCESSOR=imagemagick ./peek`
>
> you should get exactly the same behavior as with Peek 1.1.0, does this make a difference?

It does: with this flag recording works as before.

> It's interesting, the initial ffmpeg command for recording the video (pam file) shows `time=00:00:04.00` at the end. The later ffmpeg commands loading the file show `Duration: 00:00:00.04`. Something is wrong here. I have to refactor the recording part anyway (writing the data to that pam file only made sense in combination with imagemagick).

👍, feel free to ping me when I can try the refactor. Or to avoid derailing the gifski discussion, ping #198, I subscribed to it. Thanks for the prompt feedback!

**Comment by phw** [comment]
Can you try again latest master? I could finally reproduce, changed the intermediary output format. This is probably an intermediate fix.

**Comment by ronjouch** [comment]
@phw gifski postprocessor working with your fix! As expected, output is beautiful and filesize is huge.

**Comment by phw** [comment]
gifski now supports a quality setting (0-100). This is interesting, because in a quick test a quality of around 50-60 gave me pretty similar results than ffmpeg, but with smaller file size. Ffmpeg still encodes faster, but it's kinda ok with gifski in lower quality settings.

There is a big case of making gifski the default and add a slider for quality. My current idea is to just do that with gifski, settting the default quality to 60. The user can then configure the quality with a slider. And if gifski is not available fall back to ffmpeg without quality setting.

Some comparisson, first with ffmpeg:

![ffmpeg](https://user-images.githubusercontent.com/29852/32415463-8cf96b0a-c23a-11e7-8a12-a0d03e40b32e.gif)

gifski quality 100:

![quality100](https://user-images.githubusercontent.com/29852/32415470-959097ca-c23a-11e7-9d82-8c64f0647fed.gif)

gifski quality 60:

![quality60](https://user-images.githubusercontent.com/29852/32415473-9d3361d8-c23a-11e7-99be-2b6ba4314c1c.gif)

**Comment by ronjouch** [comment]
@phw 

> gifski now supports a quality setting (0-100). This is interesting, because in a quick test a quality of around 50-60 gave me pretty similar results than ffmpeg, but with smaller file size. Ffmpeg still encodes faster, but it's kinda ok with gifski in lower quality settings.
>
> There is a big case of making gifski the default and add a slider for quality. My current idea is to just do that with gifski, settting the default quality to 60. The user can then configure the quality with a slider. And if gifski is not available fall back to ffmpeg without quality setting.

Pure awesome 👍; we can have our PNGQuant awesomeness cake and eat it in GIF-land 🙂. I guess/hope that will still let users customizing capture framerate (but there's no reason not to, right?), it remains an important way to keep GIF filesize reasonable. Ping me here if/when a first implementation is available, I'll be glad to test it.

**Comment by phw** [comment]
I have made gifski the default. If gifski is available it will be used, if not Peek will fallback to ffmpeg.

By default Peek will use a quality setting of 60. But you can change it in the preferences, see below. This setting is only available if gifski is installed.

![bildschirmfoto vom 2017-11-06 18-11-11](https://user-images.githubusercontent.com/29852/32453910-e88edd9a-c31d-11e7-988a-4d2b20fc63bb.png)

**Comment by ronjouch** [comment]
Works for me. @phw awesome work 👍.

**Comment by ronjouch** [comment]
> I have made gifski the default. If gifski is available it will be used, if not Peek will fallback to ffmpeg.
> 
> By default Peek will use a quality setting of 60. But you can change it in the preferences, see below. This setting is only available if gifski is installed.

@phw I've been playing with it (latest `master` gifski+peek), but for now I feel it's a bad idea to replace ffmpeg, because although gifski now advertises a quality setting, gifski remains in a whole diffrent ballpark regarding filesize, even when setting minimum gifski quality. See for yourself on similar screencasts (manual timing and clicking, so that's not a 100% exact comparison, but still gives an idea):

- **Baseline ffmpeg: 300kB**  
![peek-ffmpeg](https://user-images.githubusercontent.com/522085/32498338-74f2d79e-c39d-11e7-8441-3baefcc69b6d.gif)
 
- **Gifski q=20: 1.2MB**  
![peek-giphy_20](https://user-images.githubusercontent.com/522085/32498355-83de8de8-c39d-11e7-8623-dfd89011c627.gif)
 
- **Gifski q=100: 1MB** (yes, smaller than q=20, I guess it's actually just a bit shorter)  
![peek-giphy_100](https://user-images.githubusercontent.com/522085/32498374-8da000be-c39d-11e7-8c3c-6a9978603d7f.gif)

It feels like high quality makes for a bit less dithering, but overall filesize remains huge.

Am I doing something wrong? (Do you get the same behavior when fiddling with gifski quality?) If you confirm the huge filesizes regardless of gifski quality, please keep ffmpeg as an option.

**Comment by phw** [comment]
Thanks a lot for this testing. Yes, these results speak against gifski as default, especially as gifski cannot play out its huge advantage on the typical screen recording content (application interfaces without too many colors).

My results have been indeed different, gifski with q=60 was around the file size of ffmpeg, even a bit smaller sometimes. But the final file size depends so heavily on the recorded content and colors shown. For tests I encoded the WebM video in [test.zip](https://github.com/phw/peek/files/1450418/test.zip) with ffmpeg, imagemagick and gifski in different quality. My results where:

- imagemagick: 4.1 MB
- ffmpeg: 3.9 MB
- gifski q 100: 5.9 MB
- gifski q 80: 4.5 MB
- gifski q 60: 3.8 MB
- gifski q 40: 3.3 MB
- gifski q 20: 2.8 MB

New plan: I ad a checkbox to enable gifski.

**Comment by ronjouch** [comment]
@phw thinking about the non-effect of the new gifski slider, could it simply be that my build is screwed? Especially, I didn't `make install`, so the xml conf schemas were not deployed. I noticed that running from the `build` folder with `./peek` succeeds in making peek run (whereas if I just run `/opt/peek-git/build/peek` from `~` it crashes with a gschemas error), so it *looks like* new schemas (including the gifsky quality integer) are fetched, but could something more be wrong, causing a constant/default be passed to gifski regardless of the slider position?

**Comment by phw** [comment]
Which version of gifski do you use? gifski 0.5 compiled from AUR, or gifski-git, or the official binary from gifski release page?

**Comment by phw** [comment]
How did you install Peek? As it is not possible to install Peek in 14.04 from source I assume you are using the snap version, right?

If so, the snap.package is not yet update to include gifski. Due to the Sandboxer nature of snap apps it cannot use your system wide installation.

**Comment by andersaamodt** [comment]
Ah. Is there a workaround?

**Comment by phw** [comment]
@andersaamodt No, not currently. The flatpak builds already include gifski, but I don't know whether you can run this on 14.04. I will update the snaps to include gifski before the next release.

**Comment by phw** [comment]
@andersaamodt I have updated the snaps, could you try the latest snap from the edge channel if it works for you?

    sudo snap install --edge peek

**Comment by andersaamodt** [comment]
Hmm, I installed the update but there is still no progress bar.

**Comment by phw** [comment]
What do you mean with progress bar? Do you see the gifski settings in Peek's preferences

**Comment by andersaamodt** [comment]
No, they don't show up
