### ISSUE TITLE
Show elapsed time during recording

### ISSUE THREAD

**Issue by phw** [phw/peek#214]

**Comment by gort818** [comment]
I might do some testing with this this weekend.

**Comment by gort818** [comment]
Got a working example! Still got some work to do to make it look nicer, but the functionality is there.
![peek 2017-11-11 23-39](https://user-images.githubusercontent.com/9098121/32696953-f189a748-c739-11e7-91d5-e085596cf1bb.gif)

**Comment by gort818** [comment]
Here is a another one with the buttons left aligned and the different icon for record #218

**Comment by gort818** [comment]
![peek 2017-11-12 13-16](https://user-images.githubusercontent.com/9098121/32703519-308d4d6a-c7ac-11e7-9a9d-c470488d2fb0.gif)
![screenshot from 2017-11-12 13-18-47](https://user-images.githubusercontent.com/9098121/32703526-391878ce-c7ac-11e7-91db-791eee62e9b6.png)

**Comment by phw** [comment]
That last view already looks quite nice. What about centering the recording time between buttons and window controls?

**Comment by gort818** [comment]
Ok cool I will do some tests later and let's see how it looks.

**Comment by gort818** [comment]
@phw I am having a hard time centering the recording time label widget any idea how to go about this?

**Comment by phw** [comment]
Not sure actually, I consider myself a GTK beginner still :) But I could take a look, do you have the code up somewhere?

**Comment by gort818** [comment]
I'll set up a branch later when I get home.

**Comment by gort818** [comment]
Ok take a look!

https://github.com/gort818/peek/tree/update_time

**Comment by gort818** [comment]
#227
