### ISSUE TITLE
Crashes entire OS on Ubuntu 17.10

### ISSUE THREAD

**Issue by cb109** [phw/peek#215]
- **Ubuntu** `17.10` with **peek** `1.1.0-0~ppa16~ubuntu17.10.1`
- `Using screen recorder backend gnome-shell`
- Hardware: Intel NUC

I can open the UI and start recording, but once it has finished counting down from 3 the screen will freeze and render the complete machine unusable, so I am forced to restart.

Please let me know any details/logs you may find useful and I will provide them.

**Comment by phw** [comment]
Please see https://github.com/phw/peek/issues/202 and the Gnome Shell Bug at https://bugzilla.gnome.org/show_bug.cgi?id=790008

**Comment by cb109** [comment]
Worked around by switching to Unity as window manager.

**Comment by phw** [comment]
You should also be able to switch to the Xorg session instead of Wayland.
