### ISSUE TITLE
Computer freezes every time at record countdown 1

### ISSUE THREAD

**Issue by jamesray1** [phw/peek#216]
Using Artful.

Also after this freeze happened twice, I installed via the Ubuntu Software Centre there were then two results for Peek (previously there was only one). One result had nothing happen when I clicked on it, the other opened but still froze.

**Comment by phw** [comment]
Please see #202 and the Gnome Shell Bug at https://bugzilla.gnome.org/show_bug.cgi?id=790008

**Comment by uqmessias** [comment]
@phw 
Do you know if it was already fixed and if it was, how can I get the fix and upgrade my system?
