### ISSUE TITLE
"Record" button does not follow established UI standard

### ISSUE THREAD

**Issue by p-e-w** [phw/peek#218]
For decades, there has been a standard way of labeling the "record" button on devices from video cameras to studio equipment to smartphones: A **red circle.**

Peek's "record" button currently is **blue** and its icon a **triangle**, which classically means "play" rather than "record".

I suggest to change that and use the standard.

References:

https://www.quora.com/Why-is-the-record-button-on-any-recording-device-identified-by-the-red-dot

https://ux.stackexchange.com/questions/41434/why-is-the-record-icon-always-round-and-usually-red

**Comment by gort818** [comment]
@p-e-w This has been merged we changed the record icon, it is not a red circle but a circle nonetheless, I think it looks great.

**Comment by phw** [comment]
I actually like it this way. We could still make the icon red (but keep the `-symbolic` version, just color it differently), but I am not sure this will work with all themes and I would like to honor theme defaults. Also the button being blue depends on  the theme, it uses the default for a "primary" button. E.g. on the new Ubuntu 17.10 theme it will be green.

@p-e-w Thoughts?

**Comment by phw** [comment]
I consider this closed for now, but feel free to comment on the new layout. Here is a screenshot for reference:

![bildschirmfoto vom 2017-11-19 02-08-38](https://user-images.githubusercontent.com/29852/32986257-9c67d0ec-ccce-11e7-8c7d-155e7fe4611d.png)
