### ISSUE TITLE
Gifski not used even though installed

### ISSUE THREAD

**Issue by linusg** [phw/peek#219]
Hey there!
I found this tool pretty useful lately and ma glad that the performance issues were resolved.

However it seems like I'm having issues with getting `gifski` up running. I have `peek 1.1.0` installed from the Ubuntu repository added beforehand and `gifski 0.6.0` installed from the DEB-package.

After looking into the source code: https://github.com/phw/peek/blob/master/src/utils.vala#L55
I'm not quite sure what's wrong here. `which gifski` as also executed by `peek` works perfectly fine but no quality slider is showing up:

![peek 2017-11-12 14-48](https://user-images.githubusercontent.com/19366641/32699637-68675192-c7b9-11e7-95a2-e46cc395464f.gif)

**Comment by linusg** [comment]
What I forgot mentioning:
when run from the command line peek chooses `ffmpeg` as its backend:

> Using screen recorder backend ffmpeg

**Comment by phw** [comment]
gifski support is not yet released. You will have to use the latest development version or wait for a new release (I plan to release soon). You can install development versions from source, as Flatpak or Snap or from PPA, see the README for details.

**Comment by linusg** [comment]
Crap, I must have missed that. Thanks for your time, I'll try building from source or installing a dev version from the PPA!
