### ISSUE TITLE
peek locks machine entirely

### ISSUE THREAD

**Issue by esfourteen** [phw/peek#221]
running ubuntu 17.10, gnome on wayland. installed app via official ubuntu ppa repo. peek loads fine and the timer counts down, however when it attempts to start capturing it locks the machine entirely requiring a hard reboot.

**Comment by esfourteen** [comment]
after further investigation, this seems to be a known bug under gnome/wayland.

**Comment by phw** [comment]
Please see #202 and the Gnome Shell Bug at https://bugzilla.gnome.org/show_bug.cgi?id=790008
