### ISSUE TITLE
Fallback app menu not clickable

### ISSUE THREAD

**Issue by gort818** [phw/peek#222]
I tested the latest build on multiple distros and found a bug I unintentionally  caused.

>
      this.forall ((child)  => {
        if (child is Gtk.Popover) {
            fallback_app_menu = child;
Since the new format popover menu is a a popover menu as well  there is an issue on some desktops and distros (Linux Mint 18.2) where it uses the format popover as the fallback menu.. but not to fret pr coming soon.

**Comment by phw** [comment]
Fixed with #223
