### ISSUE TITLE
Autohide record button label

### ISSUE THREAD

**Issue by gort818** [phw/peek#226]
We will have to change

>  private const int SMALL_WINDOW_SIZE = 300;

as the the record button label will now be larger, and will not autohide. I tested with 350 it worked well but my font size is set to 9.

**Comment by phw** [comment]
True, needs to be changed now. Is setting the SMALL_WINDOW_SIZE enough or do we need to handle more due to the new layout with popover button?

**Comment by phw** [comment]
I went a little bit different route and optimized the layout a bit. The 300 pixel still works for me now. I tested even with 18pt Cantarell font, still it's enough to trigger the label hiding :)
