### ISSUE TITLE
Show recoding shortcut hint

### ISSUE THREAD

**Issue by phw** [phw/peek#234]
Show a hint to the user that recording can be started / stopped with a keyboard shortcut (if available and configured). This is especially useful when Peek is started without headerbar (#203) or recording fullscreen (#61).

Idea: Show the shortcut hint in the overlay on startup / on recording countdown. Make sure the label can be displayed (maybe hide on small window sizes).

**Comment by gort818** [comment]
Here is quick test obliviously needs more work
![screenshot from 2017-11-21 17-30-13](https://user-images.githubusercontent.com/9098121/33105396-b8800028-cee1-11e7-9f71-75929a9902b3.png)

**Comment by gort818** [comment]
@phw are you still interested in this? Sorry been a little busy lately, I got some free time would love to finish this up.

**Comment by phw** [comment]
Sure, still interested in this. I am pretty busy myself and won't find the time soon.

Just as a general guidelines for the implementation: My main concern is again that the minimal window size will be increased by the change. So maybe there needs to be some logic again to only show the full hint at a certain size.

**Comment by gort818** [comment]
Still haven't forgot.. going to try to tackle this on the weekend if I have time.

**Comment by phw** [comment]
@gort818 Much appreciated :) Currently I also struggle to find some time, but definitely want to work on some of the bugs and features here, too.

**Comment by gort818** [comment]
Got something nice coming along, pull request coming shortly
![screenshot from 2018-02-22 17-54-17](https://user-images.githubusercontent.com/9098121/36574217-721c24a2-17f9-11e8-9a9b-6b313b157e24.png)
![screenshot from 2018-02-22 17-53-49](https://user-images.githubusercontent.com/9098121/36574218-7237ae16-17f9-11e8-94d2-16ea01fa05a3.png)

**Comment by gort818** [comment]
The minimal window is not increased the label text will scale down once the window is below the threshold.

**Comment by gort818** [comment]
Fixed with #285 . We can close this guy
