### ISSUE TITLE
[Flatpak] File can’t be saved in home directory

### ISSUE THREAD

**Issue by fbruetting** [phw/peek#235]
When I try to save a file in my home directory, it shows up again in the Peek-inside gtk file chooser widget when I open the save dialog again, but when I open my home folder in Nautilus, the file isn’t there. I even couldn’t find it via `find ~ -iname "<file name>"`.

The file chooser widget shows other folders like “images” and “videos” with an eject button in the left pane (so they seem mounted) – there I could save my file correctly. Seems like the home directory isn’t the real home directory of my system, but an artificial one of the Flatpak sandbox…?

**Comment by phw** [comment]
Please see #228

**Comment by fbruetting** [comment]
Cool, thanks!

**Comment by phw** [comment]
Just as an info: I hope to release 1.2.0 this weekend (things are looking good so far). That's the main reason why I don't bother updating the stable Flatpak right now ;)

**Comment by fbruetting** [comment]
Great!
