### ISSUE TITLE
GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.interface' is not installed

### ISSUE THREAD

**Issue by probonopd** [phw/peek#238]
```
me@host:~$ /isodevice/Applications/peek-1.2.0-x86_64.AppImage 

(peek-run:11047): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.interface' is not installed

Trace/breakpoint trap

me@host:~$ cat /etc/os-release 
PRETTY_NAME="Deepin 15"
NAME="Deepin"
VERSION_ID="15.4.1"
VERSION="15.4.1"
ID=deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="http://feedback.deepin.org/feedback/"

me@host:~$ sudo apt install gsettings-desktop-schemas
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gsettings-desktop-schemas is already the newest version (3.22.0-1).
```

**Comment by probonopd** [comment]
Similar to https://github.com/AppImage/AppImages/issues/51

**Comment by phw** [comment]
Found the issue, currently the launcher assumes that `$XDG_DATA_DIRS` is set. If this is not set it should assume a default of `/usr/local/share/:/usr/share/`.

Can you verify that this variable is not set in your case?

**Comment by phw** [comment]
@probonopd I tried to fix this by checking whether XDG_DATA_DIRS is already set, as my launcher script appends to it:

```
if [ -z "$XDG_DATA_DIRS" ]
then
  XDG_DATA_DIRS=/usr/local/share/:/usr/share/
fi
export XDG_DATA_DIRS=$BASE_DIR/usr/share/:$XDG_DATA_DIRS
```

But I found that XDG_DATA_DIRS is already set to `XDG_DATA_DIRS=/tmp/.mount_gXr9lb/usr/share/:` when my script gets launched. Does the AppImage default launcher already set this? If so it also should handle the case that this is not always set.

According to the [spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) a default of `/usr/local/share/:/usr/share/` should be assumed.

**Comment by phw** [comment]
Opened a pull request at https://github.com/AppImage/AppImageKit/pull/552

**Comment by phw** [comment]
Fixed for Peek by just setting `/usr/local/share/:/usr/share/` no matter what.

**Comment by probonopd** [comment]
Thanks!

**Comment by romariolopezc** [comment]
Hello, I'm having this exact same error.
```$ uname -a
Linux xps 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux
```

Window Manager: i3
