### ISSUE TITLE
Add Indicator to Show When Rendering GIF

### ISSUE THREAD

**Issue by xd1936** [phw/peek#24]
When you're done recording and hit "Stop", the program gives no indication that you have successfully stopped the recording and are now rendering a GIF to output. Since this can take 30+ seconds, consider maybe changing the "Stop" button to say "Rendering..." and grey it out or something.

Keep up the great work!

**Comment by phw** [comment]
Yes, that's something I really should do :)

**Comment by xd1936** [comment]
Holy cow! You're quick :)

**Comment by phw** [comment]
> Holy cow! You're quick :)

Na, you are just lucky ;) The things I want to do for Peek pile up due to other commitments, but I wanted to get some things done for a new release again and this one was easy to do.
