### ISSUE TITLE
Peek v1.2.1 isn't compatible with Gnome 3.26.2

### ISSUE THREAD

**Issue by mlaitinen** [phw/peek#243]
When I try to launch Peek v1.2.1 I get:
```
$ peek
You need to connect this snap to the gnome platform snap.

You can do this with those commands:
snap install gnome-3-26-1604
snap connect peek:gnome-3-26-1604 gnome-3-26-1604

(the '3-26-1604' number defines the platform version and might change)

$ gnome-shell --version
GNOME Shell 3.26.2
```

I didn't have guts to install `gnome-3-26-1604` because it's clearly an older version.

Any workarounds?

**Comment by phw** [comment]
`gnome-3.-26-1604` is just the platform snap, which provides basic libraries for snaps using the gnome stack (so not every snap has to bundle everything and snaps can be smaller). It is unrelated to the gnome version you have installed (you can even have an older version installed locally).

Just follow the commands printed and it should work. Please note that the Peek snap does not work under Wayland, if you want to use Wayland you should install Peek from the PPA.

**Comment by mlaitinen** [comment]
Ahh, ok. I've been using Ubuntu for many years but it's the first time I hear about snaps.

I installed the snap and conneted peek, but now I get:
```
$ peek

(peek:5460): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Using screen recorder backend ffmpeg
/snap/peek/619/bin/launch-peek: line 7:  5460 Segmentation fault      (core dumped) peek
```

**Comment by mlaitinen** [comment]
Ah, might be related to Wayland. I don't know what that is but I'll try to install Peek from the PPA.

**Comment by phw** [comment]
Yes, please try using the PPA for now. That's pretty unfortunate that the Snap does not support GNOME Wayland, but Ubuntu 17.10 switched to GNOME Wayland as default. I actually don't know how to deal with this situation for now.

I have added a new issue https://github.com/phw/peek/issues/245 to track this.
