### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by jingle0927** [phw/peek#244]
I am come form deepin

We will collect some good applications on the deepin AppStore, hoping to support Chinese

http://appstore.deepin.org/app/peek

**Comment by phw** [comment]
Thanks for this. Peek should actually already have rather good support for Chinese. The simplified Chinese translation is complete, the traditional script translation is missing some translations, see https://hosted.weblate.org/projects/peek/translations/zh_Hant/ . If you spot any mistakes in translations those can be edited online at https://hosted.weblate.org/projects/peek/translations/

I also have app store translations (short description and long description), maybe those can be used for the Deepin store, too:

----

zh_Hans
Peek
简单易用的屏幕录制器

Peek 使得在屏幕上录制指定区域变得简单。比如: 你可以简单的把Peek窗口移动到你想要录制的区域，然后按下"录制"，这样就可以方便的展示自己应用UI的功能或是在错误报告中展示错误。Peek 对制作GIF动画有优化，但是，如果你喜欢的话，你也可以直接录制MP4 或者 WebM。

特色：

  - 选择要录制的屏幕区域
  - 将录制的视频保存为优化过的 GIF 动画
  - 直接录制为 WebM 或 MP4 格式
  - 为任务优化的简单用户界面
  - 自动缩放录制的视频
  - 支持 HiDPI 屏幕
  - 可以在 GNOME Shell Wayland 会话内使用(使用 XWayland)

Peek 不是一个拥有扩展功能的通用屏幕录制应用，它唯一的功能就是在屏幕上录制小巧无声的 GIF，MP4和WebM视频。

---

zh_Hant
Peek
簡單易用的螢幕錄影軟體

Peek 讓錄製一部分的螢幕截取變得更加容易。這是專門被設計來錄製部分螢幕區塊的，例如在示範軟體操作或者重現 bug 狀況時就能派上用場。有了 Peek，您只要把 Peek 的視窗放置在您想錄影的區塊，然後按下「錄影」即可。Peek 已針對產生 GIF 動畫進行優化，不過需要的話也能直接錄製 WebM 或者 MP4 格式。

功能：

  - 可選取欲錄製的螢幕區塊
  - 可將錄製的影片儲存為經優化的 GIF 動畫
  - 可直接錄製成 WebM 或 MP4 格式
  - 簡單易用的界面
  - 可自動縮小影片解析度
  - 支援 HiDPI 螢幕
  - 支援 GNOME Shell Wayland 模式（透過 XWayland）

Peek 並不是專門用來錄影的應用程式，Peek 專注在錄製螢幕區塊並輸出成 GIF 動畫或無聲的 WebM、MP4 影片。

**Comment by jingle0927** [comment]
@phw   Thanks
