### ISSUE TITLE
Snap is not compatible with Wayland, but Wayland is the default on Ubuntu 17.10

### ISSUE THREAD

**Issue by phw** [phw/peek#245]
Starting with Ubuntu 17.10 GNOME Wayland is the default desktop environment. But the Peek Snap does not support screen recording on Wayland since the Snap cannot access the GNOME screencast DBus service.

There are two workarounds for this:

- Use X11 session instead of Wayland
- Install Peek from PPA

A fix is needed since this is causing a very bad user experience for Ubuntu users installing from the Ubuntu store. But for now I have no good idea how to solve this.

See also https://github.com/phw/peek/issues/243

**Comment by phw** [comment]
@umpirsky The freezing issue is another thing, please see #202 and the Gnome Shell Bug at https://bugzilla.gnome.org/show_bug.cgi?id=790008

**Comment by phw** [comment]
I opened a discussion at https://forum.snapcraft.io/t/screen-recording-on-wayland/3563

**Comment by umpirsky** [comment]
Thanks @phw!

It's sad seeing Peek loosing customers because of Gnome Shell bug.

**Comment by phw** [comment]
@umpirsky It's not only affecting Peek, but screen recording on GNOME Wayland in general. But so far only Ubuntu seems to be affected.

**Comment by umpirsky** [comment]
@phw I have installed a screen recorder that works fine on Wayland. Don't want to promote here, but if you want to check it out, I can share via email or here. It's open source too.

**Comment by phw** [comment]
@umpirsky Just to be clear, you have neither installed Peek nor the other screen recorder as a Snap, right? And you can tell what it is, that's not promotion and mentioning other screen recorders is for sure not banned here :)

**Comment by umpirsky** [comment]
@phw Ye, that might be the case, I experimented with the snap. :)

**Comment by phw** [comment]
Ok, we have currently two issues here:

1. Starting the snap segfaults on Wayland. This should be solvable, I already made some progress here
2. Once Peek starts recording will not work, since there is no screen recording interface for Snaps (see linked discussion above). Best thing I could do right now is show a dialog explaining the user to either use X11 or install Peek via PPA, Flatpak or AppImage.

Actually the situation is very dissatisfying. I am very close to just trash the Snap version again and stop dealing with this until the situation has significantly improved.

**Comment by umpirsky** [comment]
I like the dialog, if you can detect this bugs and prevent them, it will be good for the app and it's users.

Until they resolve it.

**Comment by phw** [comment]
Snap packages are no longer supported, see https://www.reddit.com/r/Ubuntu/comments/870bcn/snap_support_for_peek_screen_recorder_discontinued/

**Comment by umpirsky** [comment]
Smart move.
