### ISSUE TITLE
bombs out with framerate 1

### ISSUE THREAD

**Issue by rubaboo** [phw/peek#249]
Peek: 1.2.1-10-g62bb7d1
GTK: 3.22.24
GLib: 2.54.1

Details:
```
Missing output file after post processing.
```

~~Error when trying to use gifski (0.7.0). It works without gifski.~~
Not working at all after I changed framerate to 1.

**Comment by rubaboo** [comment]
I think these are two separate issues. It doesn't work with Framerate 10 and gifski enabled, and dosn't work at all with Framerate 1.

**Comment by rubaboo** [comment]
I just wanted to make a screenshot (not animated), that's why framerate 1. :)
Can you add a screenshot functionality, so there is no need for another app just for that?

**Comment by phw** [comment]
Does gifski run on it's own? Please try running gifski as described on https://github.com/phw/peek/issues/240#issuecomment-348435154

**Comment by rubaboo** [comment]
No. I'm renaming this issue so it's not a duplicate.
```
Frame 141 / 1900  ########_....................................................................................................... 30s Segmentation fault
```

**Comment by phw** [comment]
As this is a gifski issue it should be reported there. How did you install gifski? If you installed from source try compiling it without the openmp option, that caused defaults for me in some environments (but I could not yet debug it)

**Comment by rubaboo** [comment]
I'll try again to explain... Using gifski is not really important to me. The other issue I found is that peek gives the same error message when the framerate is set to 1. Regardless of gifski setting. So I'd like to report that issue with peek, here. I renamed the issue accordingly. This is not about gifski anymore.

Here are the conditions that lead to `Missing output file after post processing.` error:
Output format: GIF
"Use gifski" is unchecked, clear.
Framerate: 1
Start recording and stop in 3 seconds or so.
It spins "Rendering" for a moment, then there is "Save animation" dialog, and when I hit Save, I get the error.

**Comment by phw** [comment]
Got it :) Will test this after the holidays

**Comment by phw** [comment]
Two more questions:

1. Are you running this on Gnome or not?
2. Can you give me the output of `ffmpeg -version`?

**Comment by rubaboo** [comment]
On xfce 4.12.

```
$ ffmpeg -version
ffmpeg version 3.4.1-1 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 7 (Debian 7.2.0-17)
configuration: --prefix=/usr --extra-version=1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
```

**Comment by phw** [comment]
Some preliminary tests using the ffmpeg backend:

- For WebM and GIF / APNG (also using Matroska internally) the minimum frame rate seems to be 3fps
-For MP4 the minimum framerate seems to be 4fps

Using the gnome-shell backend recording works down to 1fps in all formats.
