### ISSUE TITLE
line 7: 31104 Segmentation fault      (core dumped) peek

### ISSUE THREAD

**Issue by Qwertie-** [phw/peek#251]
I just installed peek from snap on fedora 27 and when I run it I get the error
```

(peek:30566): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Using screen recorder backend ffmpeg
/snap/peek/619/bin/launch-peek: line 7: 30566 Segmentation fault      (core dumped) peek

```
If I run `export LC_ALL=C` The first part goes away and I just get 
```

Using screen recorder backend ffmpeg
/snap/peek/619/bin/launch-peek: line 7: 31104 Segmentation fault      (core dumped) peek


```

Tested with flatpak and it does work fine. Just not with snap.

**Comment by phw** [comment]
You are likely trying to run the Peek snap on Gnome Wayland. The snap version does not support Wayland yet, please install from PPA.

**Comment by Qwertie-** [comment]
Hah, I didn't even know I was running wayland but I checked and that seems to be the case.

**Comment by phw** [comment]
I am closing this in favor of #245

**Comment by bokub** [comment]
I'm having the same issue with Peek 1.5.1, installed from the PPA...
