### ISSUE TITLE
Can't record: Permission Denied

### ISSUE THREAD

**Issue by i-snyder** [phw/peek#252]
I'm new to Linux, starting to get my head wrapped around things. I downloaded the AppImage and was able to use it no problems, but then I thought hey I'll install with sudo to get it to show up in the Applications in Elementary OS. Once I installed through the Terminal I started getting the below error when trying to record. I understand this is a Permissions issue, but I don't know how to clear it up. I'm able to run it fine by running "sudo peek" through terminal, but I'd like to be able to just click the icon in Applications. I actually tried uninstalling through the Terminal and just running the AppImage, but I'm getting the same error, so I'm not sure if this is an issue with ffmpeg config getting changed or something? Thanks!
- Ian

Peek: 1.2.1
GTK: 3.18.9
GLib: 2.48.2

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 409x226 -i :0+413,223 -filter:v scale=iw/1:-1 -codec:v libx264rgb -preset:v ultrafast -crf 0 -y /home/linuxian/.cache/peek/peek86B7AZ.mkv" failed with status 256 (received signal 0).

Output:
ffmpeg version 3.4.1-1~16.04.york0 Copyright (c) 2000-2017 the FFmpeg developers  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 20160609  configuration: --prefix=/usr --extra-version='1~16.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared  libavutil      55. 78.100 / 55. 78.100  libavcodec     57.107.100 / 57.107.100  libavformat    57. 83.100 / 57. 83.100  libavdevice    57. 10.100 / 57. 10.100  libavfilter     6.107.100 /  6.107.100  libavresample   3.  7.  0 /  3.  7.  0  libswscale      4.  8.100 /  4.  8.100  libswresample   2.  9.100 /  2.  9.100  libpostproc    54.  7.100 / 54.  7.100Input #0, x11grab, from ':0+413,223':  Duration: N/A, start: 1513572760.640249, bitrate: N/A    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 409x226, 10 fps, 10 tbr, 1000k tbn, 1000k tbc/home/linuxian/.cache/peek/peek86B7AZ.mkv: Permission denied
```

**Comment by phw** [comment]
What exactly did you do to "install with sudo to get it to show up in the Applications in Elementary OS"?

Most likely you ran peek with sudo and now /home/linuxian/.cache/peek/ is owned by root and you don't have permissions to it. Try running

    rm -rf /home/linuxian/.cache/peek/

then try starting Peek again. You really should not use sudo for starting most software as this will often cause permission issues like this.

**Comment by i-snyder** [comment]
That did it, thanks! I usually don't run software with sudo, but I think what must've happened is I ran it through Nautilus in sudo mode on accident. Now that I'm understanding this all better now I'll be sure to be more careful with sudo in the future. Thanks for the super quick response and the explanation!
