### ISSUE TITLE
Peek window underneath bottom panel on Cinnamon

### ISSUE THREAD

**Issue by orschiro** [phw/peek#253]
Dear all, 

Just noticed that the Peek window goes underneath the bottom panel on Linux Mint 18.3 Cinnamon which suggests that it doesn't capture the panel but I tried it and it does. 

Can anyone confirm that? 

I installed the Flatpak version.

![image](https://user-images.githubusercontent.com/170947/34112619-701149dc-e40d-11e7-80a2-991f913bc762.png)

**Comment by phw** [comment]
The panel is on top of every Window, there is no way for Peek to get renered atop of that. But the layering does not really matter anyway, the Peek window is just a tool to select the recording position. Apart from that it takes no part in the recording itself.

**Comment by orschiro** [comment]
Understood. Thanks! :-)

**Comment by phw** [comment]
As an interesting sidenote, this is also the reason why one can make Peek work on i3, even though the i3 window manager does not support the click through (and thus would not allow UI interaction with the recording area). But the workaround is to place the Peek window to select the recording area, but then during recording actually send it to the background ;)

**Comment by orschiro** [comment]
Haha, nice. Thanks for sharing that although I am not an i3 user. :-)
