### ISSUE TITLE
Recording cancels when changing workspaces (Ubuntu)

### ISSUE THREAD

**Issue by jayypluss** [phw/peek#255]
Not sure if Peek team is aware of it, but I've noticed that recording just cancels when I change workspaces (saving dialog doesn't appear).

My system info:
OS: Ubuntu 17.10
Shell: Unity 7.5.0
Intel® Core™ i5 CPU 650 @ 3.20GHz × 4 
Intel® Ironlake Desktop 
64-bit

**Comment by phw** [comment]
Is this with the GNOME desktop? I cannot reproduce this here on my GNOME on Arch, I will try to reproduce this on Ubuntu 17.10.

Likely this is related to the fact that recording stops when the window position or size changes.

**Comment by arist0tl3** [comment]
I get a different experience -- the peek window "stays" on the initial workspace, but records whatever is at that screen position when moving around the workspaces.

Gnome 3.8.13
Ubuntu 16.04.3 LTS 64-bit

I also use https://extensions.gnome.org/extension/484/workspace-grid/

![peek 2017-12-28 19-20](https://user-images.githubusercontent.com/9328541/34428847-90f35cd0-ec05-11e7-8eda-1d4174fc5c63.gif)

**Comment by phw** [comment]
@arist0tl3 That's expected behavior
