### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by SuperHori** [phw/peek#256]
Peek: 1.2.1
GTK: 3.22.26
GLib: 2.54.1

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
First make sure you have gstreamer1.0-plugins-good and gstreamer1.0-plugins-ugly installed.

If it still does not work  take a look at journalctl if there is any log output when you start recording. 

A few questions to narrow down the issue:

- What format are you recording (GIF, WebM, MP4)?
- Are you running on X11 or Wayland?
- What Linux distribution is this?

**Comment by phw** [comment]
@SuperHori Was your question answered, can this be closed? Or is there still some issue?

**Comment by phw** [comment]
Closing for now, feel free to give more details if you still need some help.
