### ISSUE TITLE
Peek Notification Stuck on Lock Screen

### ISSUE THREAD

**Issue by fenimore** [phw/peek#257]
Hi,

My system info:
OS: Arch
Gnome 3.26
Peek 1.2.1-11-g325c1ea

I can't figure out why, but the lock screen on my gnome shell always has a Peek notification, even when I restart the computer and have not used Peek.

It says "1 New Notification" (from Peek)

and my `ps -A` output doesn't have any `peek` processes running. 🤔 

I can't take a screenshot 😬 because, well it's the login screen.

**Comment by phw** [comment]
Is it only the lock screen or is the notification actually shown in the notification area when you are logged in? Does the notification dissapear when you interact with it?

Having a running Peek instacnce is not required for the notification to be there. Unless you have dismissed it it will stay around if the DE supports persistent notifications (as GNOME does). If you click the notification it will invoke Peek again to handle the action (you won't see Peek in this case, but it will open, handle opening Nautilus and close again).

**Comment by fenimore** [comment]
Hmm ok, so it's expected behavior? And yeah, it's only in the lockscreen, I don't see any notification area. So I went to the gnome settings and disabled the notifications for peek and it went away. So I suppose you can close this?

**Comment by phw** [comment]
> I don't see any notification area.

GNOME calls it the "message tray". You can open it by clicking on the clock at the top or pressing Super + M. It holds all still active notifications and upcoming calendar events. It's quite a fundamental piece of the desktop ;)

**Comment by TroyWolf** [comment]
I _was_ having same issue.
![IMG_20190622_103753885_BURST000_COVER_TOP](https://user-images.githubusercontent.com/6349163/59966577-c4197300-94e3-11e9-89d9-756df0b09112.jpg)

Despite using Ubuntu for years, I was not aware of the list of notifications when clicking the clock in the top bar! :grinning: 

There was the Peek notification, so I cleared it. Problem solved. There were other notifications there, but only the Peek notification was showing up on my login screen.
