### ISSUE TITLE
using gifski

### ISSUE THREAD

**Issue by Heliotrop** [phw/peek#258]
Peek: 1.2.1
GTK: 3.22.25
GLib: 2.54.1

Details:
```
Missing output file after post processing.
```

**Comment by Heliotrop** [comment]
gifski crashed with SIGSEGV (gifski 0.7.1)

**Comment by phw** [comment]
If you have gifski reproducible segfaulting, please report this to the gifski project. Peek just uses this as an external tool, there is nothing to be done inside Peek.

One thing to try is compiling gifski without the openmp feature, see https://github.com/ImageOptim/gifski#building for details.
