### ISSUE TITLE
Can't install peek on Ubuntu

### ISSUE THREAD

**Issue by VectorM** [phw/peek#261]
OS: Ubuntu 14.04 (Xubuntu)
When type:
`sudo apt update && sudo apt install peek`
get this in my terminal
![image](https://user-images.githubusercontent.com/12542364/34881369-121e45ec-f7bc-11e7-8798-b6fce533e818.png)

**Comment by phw** [comment]
Ubuntu 14.04 is unsupported, Peek can't be built for it. But I have heard from users that the Snap version works, see https://github.com/phw/peek#snappy

Not sure what is required to install Snap on Ubuntu 14.04, but Canonical for sure has some documentation on this.
