### ISSUE TITLE
Fedora Installation Not Working

### ISSUE THREAD

**Issue by mauriandres** [phw/peek#263]
When following the installation instruction for Fedora, I get:

`[root@x230 yum.repos.d]# dnf install peek
Failed to synchronize cache for repo 'home_Bajoja', disabling.                                                      ] ---  B/s |   0  B     --:-- ETA
Last metadata expiration check: 0:26:50 ago on Tue 23 Jan 2018 11:12:45 AM EST.
No match for argument: peek`

I'm currently running Fedora 27. It seems to be the _repomd.xml.key_ file in _repodata_. If I try to open that file I get:
`XML Parsing Error: syntax error
Location: http://download.opensuse.org/repositories/home:/Bajoja/Fedora_25/repodata/repomd.xml.key
Line Number 1, Column 1:-----BEGIN PGP PUBLIC KEY BLOCK-----
^`
Any advice would be welcomed. Thank you.

**Comment by phw** [comment]
I am not maintaining this repository and can currently not test myself, but maybe it just does not work with Fedora 27. I have actually setup my own repositories a while back, but as I was not sure whether I can maintain them I have not announced it. But please try if any of those repositories work:

- https://download.opensuse.org/repositories/home:/phiwo:/peek/Fedora_25/home:phiwo:peek.repo
- https://download.opensuse.org/repositories/home:/phiwo:/peek/Fedora_26/home:phiwo:peek.repo
- https://download.opensuse.org/repositories/home:/phiwo:/peek/Fedora_Rawhide/home:phiwo:peek.repo

Fedora 27 is not yet available on the opensuse build server. But if one of the above work for you I will update the install instructions for Fedora to use those repositories instead.

If this still fails I would recommend installing the Flatpak version. Fedora has excellent support for Flatpak, and the Flatpak version of Peek supports all features.

**Comment by mauriandres** [comment]
Hello Philipp,

Thank you very much for getting back to me!
I ended up installing it via FlatPak and it worked great!
Great educational tool!

Appreciate your attention,

Mauricio

On Jan 23, 2018 3:02 PM, "Philipp Wolfer" <notifications@github.com> wrote:

I am not maintaining this repository and can currently not test myself, but
maybe it just does not work with Fedora 27. I have actually setup my own
repositories a while back, but as I was not sure whether I can maintain
them I have not announced it. But please try if any of those repositories
work:

   - https://download.opensuse.org/repositories/home:/phiwo:/
   peek/Fedora_25/home:phiwo:peek.repo
   <https://download.opensuse.org/repositories/home:/phiwo:/peek/Fedora_25/home:phiwo:peek.repo>
   - https://download.opensuse.org/repositories/home:/phiwo:/
   peek/Fedora_26/home:phiwo:peek.repo
   <https://download.opensuse.org/repositories/home:/phiwo:/peek/Fedora_26/home:phiwo:peek.repo>
   - https://download.opensuse.org/repositories/home:/phiwo:/
   peek/Fedora_Rawhide/home:phiwo:peek.repo
   <https://download.opensuse.org/repositories/home:/phiwo:/peek/Fedora_Rawhide/home:phiwo:peek.repo>

Fedora 27 is not yet available on the opensuse build server. But if one of
the above work for you I will update the install instructions for Fedora to
use those repositories instead.

If this still fails I would recommend installing the Flatpak version.
Fedora has excellent support for Flatpak, and the Flatpak version of Peek
supports all features.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/phw/peek/issues/263#issuecomment-359912435>, or mute
the thread
