### ISSUE TITLE
How I can change the size of the window for record the background?

### ISSUE THREAD

**Issue by emartinezpinzon** [phw/peek#264]
I need to be able to capture a larger area of the screen, how can I increase the normal capture resolution?

![1]

[1]: https://i.imgur.com/v94tY9L.png

**Comment by phw** [comment]
I am not sure I understand the question correctly :) You can resize and move the Peek window like any other window to change the recording area.

If you actually the entire screen (full screen) however, this is currently not possible. See https://github.com/phw/peek/issues/61

**Comment by emartinezpinzon** [comment]
Yes, it is correct, you can resize it by resizing the window like any other. I'm using XFCE and for some reason it's harder to do it. I had thought about whether the application would allow me to set these sizes from some configuration window.

Thank you.

**Comment by emartinezpinzon** [comment]
This is what is happening to me, I can resize the window but it is somewhat stressful. Hehehe

[He is trolling me!](https://i.imgur.com/D0KJZJW.gif)

**Comment by phw** [comment]
I see, looks tricky :( Please try enabling compositing in XFCE settings. Normally GTK windows will draw a shadow around the window, which is in addition to the optical effect also used to increase the area in which a window can be grabbed for resizing. Apart from that changing themes can help.

There is also a separate issue for this, see https://github.com/phw/peek/issues/199 . It is mostly about KDE, but maybe some of the comments and tips there will help.

I am closing this as a duplicate then.

**Comment by Tofandel** [comment]
Same issue, I can't resize the window horizontaly in Kubuntu 18.10 (but I can vertically)

**Comment by danger89** [comment]
Within XFCE is a big issue!!

**Comment by nmingotti** [comment]
Solution for KDE. Tested in Debian Stable 10.3.
System Settings -> Application Style -> Widget Style -> Gtk Themes
Change "Select a GTK3 theme" to Default. 
After that you will see peek window frame and resize will be easy.
