### ISSUE TITLE
Capture flickers and captures desktop background

### ISSUE THREAD

**Issue by StephenFluin** [phw/peek#265]
Whenever I run a capture, the capture flickers and sometimes captures the desktop background despite me not clicking on anything or doing anything:

Example:
![peek 2018-01-23 12-02](https://user-images.githubusercontent.com/165056/35297990-92a96544-0035-11e8-9296-08b1230da3ce.gif)

No idea what's wrong or how to debug it. Got this with 1.0.3 from AppImage, as well as with earlier version compiled to .deb from source.

**Comment by phw** [comment]
That's usually a driver issue, please the the FAQ at https://github.com/phw/peek#my-recorded-gifs-flicker-what-is-wrong

In case you are using GNOME you can also try to switch to the ffmpeg backend by running `peek -b ffmpeg`  (if you are not using GNOME this is the default).

**Comment by StephenFluin** [comment]
Turning off "Allow Flipping" in nvidia-settings fixed it.

![peek 2018-01-23 12-22](https://user-images.githubusercontent.com/165056/35298787-1218e2b2-0038-11e8-9e6a-41914ee28114.gif)

**Comment by phw** [comment]
Thanks for the feedback :)

**Comment by timroes** [comment]
I can confirm, that "Allow Flipping" fixes this issue reliable for me (Nvidia GeForce GTX 750 Ti, Driver version 390.48 on Archlinux).

In case you need/want to automate this: `nvidia-settings -a 'AllowFlipping=0'` works for setting it. Be aware that `nvidia-settings` behaves rather strange, and if you open the nvidia-settings GUI after you used the above command, it will just overwrite the setting with (as far as I see) the value it had the last time the UI was opened.
