### ISSUE TITLE
Report issue

### ISSUE THREAD

**Issue by kun7** [phw/peek#267]
Peek: 1.2.1
GTK: 3.22.26
GLib: 2.54.1

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
Thanks for the report. This error usually indicates there is something wrong with the GNOME shell screen recording. A common issue is a missing gstreamer good and/or ugly plugins package. Unfortunately this info is not enough to see what is missing. 

- What distribution is this?
- What format did you try to record?
- How was Peek installed (from package, distribution, Flatpak, Snap, AppImage?)
- Can you look at the output of `journalctl -f` while you see this error and post it here?

**Comment by kun7** [comment]
hello, thanks for quick reply

i've downloaded from endless os app center while i was trying to record in mp4 format.

Jan 26 16:10:20 endless systemd[877]: Starting GNOME Terminal Server...
Jan 26 16:10:20 endless dbus-daemon[916]: Successfully activated service 'org.gnome.Terminal'
Jan 26 16:10:20 endless systemd[877]: Started GNOME Terminal Server.
Jan 26 16:10:54 endless gnome-shell[1030]: ShellRecorder: failed to parse pipeline: no element "x264enc"
Jan 26 16:10:54 endless gnome-shell[1030]: shell_recorder_close: assertion 'recorder->state != RECORDER_STATE_CLOSED' failed
Jan 26 16:10:54 endless gnome-software-service.desktop[1243]: Failed to initialize recorder: Could not start recording, already an active recording using org.gnome.Shell.Screencast?

**Comment by phw** [comment]
For MP4 recording you need the gstreamer ugly plugins installed. I don't know whether this is available in Endless or not and how it would be named. Please refer to Endless for this, I could not find a public available package list. Some distributions don't include the x264 codec due to licensing / patent issues.

**Comment by phw** [comment]
I consider this answered, please let me know if that's not the case.

**Comment by kparal** [comment]
For the record, gnome-shell needs to be restarted after gstreamer1-plugins-ugly are installed.

**Comment by fatso83** [comment]
@kparal That tip was a life saver! [Had installed all possible libraries without getting MP4 running](https://github.com/phw/peek/issues/287#issuecomment-529969763), and it turned out restarting gnome-shell was all that was needed to get it working!
