### ISSUE TITLE
Unable to resize Peek

### ISSUE THREAD

**Issue by Art-2** [phw/peek#269]
After recording is not possible to resize the window
![peek njh28-01-2018 13-54](https://user-images.githubusercontent.com/12375357/35486493-65729e80-0434-11e8-926a-29d0f828b4ae.gif)

I am using Xfce 4.12
sorry if this was reported before

**Comment by phw** [comment]
This is a very strange issue, I have not seen it before. No idea how this can happen, the last time I tested on Xfce this definitely did not happen. I will take a look.

**Comment by novoid** [comment]
I can copy that behavior: I can't resize the peek window after the first recording as well.

Debian stable (Stretch) using xfce4 v4.12

**Comment by phw** [comment]
I can reproduce this on xfce 4.12. Very strange indeed.

**Comment by phw** [comment]
This is an Xfce bug, see https://bugzilla.xfce.org/show_bug.cgi?id=13338

I will workaround this by not disabling window resize on Xfce. Please note that accidentally resizing the window will immediatelly interrupt the recording.

I will close this issue as there is nothing else I can do right now, but I will make sure to deal with the workaround should the Xfce issue get resolved.

**Comment by Art-2** [comment]
Glad this is a know issue on Xfce, thanks.

**Comment by blackPantherOS** [comment]
Same issue i can't resize Peek window in Plasma
