### ISSUE TITLE
Peek is very slow to encode gifs compared to byzanz-record

### ISSUE THREAD

**Issue by edi9999** [phw/peek#271]
Peek is very slow to render GIFs compared to byzanz-record.

If I record a GIF for 10 seconds, I will have to wait another 10 seconds or more to get the GIF file saved.

Compared to that, byzanz-record doesn't take additional time to encode the file as GIF.

I'm now using peek because byzanz-record is now [unmaintained on fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1531159), but really miss the speed of it.

**Comment by phw** [comment]
I can't really reproduce this. For testing I recoreded a large file (1800x900 pixels, 30 seconds long) with both byzanz and Peek. byzanz took around 15 seconds to postprocess the file, Peek around 20 seconds. I don't think this is a deal breaker. Also as Peek is using either ffmpeg or gifski to do the GIF generation there is little I can do about this anyway.

Speaking of gifski: In case you have the gifski option enabled slow encoding is to be expected.
