### ISSUE TITLE
Could not install peek on Debian 8.6

### ISSUE THREAD

**Issue by AlexMiroshnikov** [phw/peek#272]
Hello.
I tried to install peek on Debian 8.6 following [the instructions](https://github.com/phw/peek#debian). I've got a deb file and on running `dpkg -i peek-1.2.2-Linux.deb` I get this:
```
(Reading database ... 213323 files and directories currently installed.)
Preparing to unpack peek-1.2.2-Linux.deb ...
Unpacking peek (1.2.2) over (1.2.2) ...
dpkg: dependency problems prevent configuration of peek:
 peek depends on ffmpeg; however:
  Package ffmpeg is not installed.

dpkg: error processing package peek (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for libglib2.0-0:i386 (2.42.1-1+b1) ...
Processing triggers for libglib2.0-0:amd64 (2.42.1-1+b1) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for mime-support (3.58) ...
Processing triggers for man-db (2.7.0.2-5) ...
Errors were encountered while processing:
 peek
```

Then I try install to install the required `ffmpeg` - `apt-get install ffmpeg`, but the output is:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'ffmpeg' has no installation candidate
```

So I guess the dependency is not set correct. Or am I doing something wrong?

**Comment by phw** [comment]
Debian 8 does not contain `ffmpeg` in its repository, but instead uses `libav-tools` (avconv). Peek used to work with `libav-tools` and still somewhat does, but as avconv provides limited functionality I can no longer support it and have removed it from the package dependency.

If you want to try it you can edit the dependencies at https://github.com/phw/peek/blob/master/CMakeLists.txt#L224 and replace `ffmpeg`  with `ffmpeg | libav-tools, imagemagick`. This will require you to also install imagemagick.

Please note the following:

1. The code is untested. In theory it should still work, but it might not. And if it doesn't I won't fix it.
2. When using avconv the GIF creation by default uses ImageMagick's convert, with all the issues this caused (high RAM and disk usage, long processing). I would recommend you to install [gifski](https://gif.ski/), this will improve the situation.
3. I will completely remove avconv support in one of the following releases, likely 1.3
4. APNG recording won't work

Other options include just installing from source (without package) or installing Peek 1.1.0, but I wouldn't recommend this.

**Comment by AlexMiroshnikov** [comment]
Thanks a lot for a quick and detailed answer!
