### ISSUE TITLE
I get "Missing output file after post processing." error whenever trying to record anything with any output type selected.

### ISSUE THREAD

**Issue by AshleyMcVeigh** [phw/peek#275]
Peek: 1.2.2
GTK: 3.18.9
GLib: 2.48.2

Details:
```
Missing output file after post processing.
```

P.S:
should also note that occasionally would get a Ubuntu ("system error" I think )error, although I haven't been able to reproduce this.

will add more details Later if I can

**Comment by AshleyMcVeigh** [comment]
The error stops when gifski is disabled, therefore I believe this is the same issue as https://github.com/phw/peek/issues/240

**Comment by phw** [comment]
Yes. Try updating gifski, the recent releases fixed some crashes.

Closing as an upstream issue

**Comment by Moini** [comment]
Updating to gifski 0.8.2 from https://gif.ski/ solved the issue for me.
