### ISSUE TITLE
There are no processes working simultaneous, and this error apper only with mp4 mode.

### ISSUE THREAD

**Issue by francisconp** [phw/peek#277]
Peek: 1.2.2
GTK: 3.22.26
GLib: 2.54.1

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
You should install gstreamer ugly plugins, those are required for MP4 recording

**Comment by francisconp** [comment]
I tried to install it, but I founded the some problem.

Follow my list of installed packages:
gstreamer1-plugins-base-1.12.4-1.fc27.x86_64
gstreamer-0.10.36-18.fc27.x86_64
gstreamer1-plugins-bad-free-1.12.4-1.fc27.x86_64
gstreamer1-plugins-ugly-free-1.12.4-2.fc27.x86_64
gstreamer1-plugins-bad-free-gtk-1.12.4-1.fc27.x86_64
gstreamer1-1.12.4-1.fc27.x86_64
gstreamer1-plugins-good-1.12.4-1.fc27.x86_64
PackageKit-gstreamer-plugin-1.1.8-1.fc27.x86_64
gstreamer-tools-0.10.36-18.fc27.x86_64

**Comment by phw** [comment]
What distro are you using? Your distro likely does not ship the necessary codecs. You might want to try with the ffmpeg backend, run peek with

    peek -b ffmpeg

But that might have the same issue. You might have to figure out how to enable the H.264 codec on your distro.

**Comment by phw** [comment]
I am closing this. If you have trouble installing the gstreamer ugly plugins on your distribution I recommend you to use the flatpak version.

If the missing gstreamer ugly plugins where not actually the issue, please let me know.
