### ISSUE TITLE
Show in File Manager Notification does not open Dolphin

### ISSUE THREAD

**Issue by crouthamela** [phw/peek#282]
After saving a video, a notification appears with a button, stating the file has been saved, and it may be viewed in File Manager. Clicking the button does not open Dolphin to view the file.

**Comment by gort818** [comment]
Can you post the output from the terminal?

**Comment by phw** [comment]
Some more questions:

1. Does opening Dolhpin work if you enable the "Show file manager after saving" option in Peek's preferences (this will circumvent the notification and show the file manager directly)?
2. Please give me the output of:

        G_MESSAGES_DEBUG=all flatpak run com.uploadedlobster.peek

3. What distro is this?
4. If possible it would be helpful to see whether a natively installed Peek (non-flatpak) works as expected

I tried reproducing this on my KDE Neon VM with Plasma 5.12, but unfortunately the Flatpak version  doesn't show me notificatioins at all (even though Peek is sending one). I am probably missing something. With a native installed Peek everything works as it should.

**Comment by crouthamela** [comment]
1. It does not. The terminal has no output either regarding a Dolphin opening attempting.
2. [Peek Debug.txt](https://github.com/phw/peek/files/1736829/Peek.Debug.txt)
3. Kubuntu 17.10 with [Backports PPA](https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/backports)
4. I installed native Peek 1.2.2 from the [Peek Stable PPA](https://launchpad.net/~peek-developers/+archive/ubuntu/stable/+packages) and it works as expected.

**Comment by phw** [comment]
Not sure, but something must be wrong with the way Flatpak is setup here. Just to make sure your DBus is working as it should, does the following command open your file manager with the home folder open?

````
dbus-send --session --print-reply --dest=org.freedesktop.FileManager1 /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowFolders array:string:"file://$HOME" string:""
````

Also do you have xdg-desktop-portal-kde installed? Not sure that is needed in this case, but it at least it is required for a fully functional Flatpak setup.

**Comment by crouthamela** [comment]
The dbus command works in a terminal.

Interestingly I did not have xdg-desktop-portal-kde installed, I suppose I'll let the KDE Discover team know that would be a good dependency for plasma-discover-flatpak-backend. After installing, the terminal message `g_simple_action_activate:` has gone away when I click the notification, but Dolphin still fails to open.

**Comment by phw** [comment]
Ok, we are now a step further :D Thanks for the help so far. Now that this error is gone the output of `G_MESSAGES_DEBUG=all flatpak run com.uploadedlobster.peek` would be helpful again. It should tell us how Peek is trying to open the file manager (in case of Flatpak it should use the DBus method, but Peek uses some fallbacks if this doesn't work).

**Comment by crouthamela** [comment]
No problem I've been writing KDE bugs for days too :)

Debug: [Peek Debug 2.txt](https://github.com/phw/peek/files/1737021/Peek.Debug.2.txt)

The notification appears (and I click on it) after `Temp file deleted: true` is shown in the debug, but I don't see anything appear regarding DBus.

**Comment by crouthamela** [comment]
FYI - Apparently everyone is on their computer right now, and the KDE Neon and Kubuntu teams [have already pushed a patch](https://phabricator.kde.org/T5911) to fix dependencies so the xdg-desktop-portal-kde package will be included in the future. :)

**Comment by rikmills** [comment]
> FYI - Apparently everyone is on their computer right now, and the KDE Neon and Kubuntu teams have already pushed a patch to fix dependencies so the xdg-desktop-portal-kde package will be included in the future. :)

https://launchpad.net/ubuntu/+source/plasma-discover/5.12.1-0ubuntu2

**Comment by phw** [comment]
Sorry, took me some time to get back to this. For me this looks like a general Flatpak issue. From the log I would say Peek is not even receiving the signal that opening the file was requested. Also the many other DBus related issues in the log indicate that there is something wrong in your setup regarding Flatpak and DBus. I cannot reproduce any of this on my KDE Neon VM.

I would suggest you bring this up with the Flatpak team, or maybe see if this will work better in Ubuntu 18.04. But it doesn't look like I can do anything in Peek to handle this.
