### ISSUE TITLE
error while loading shared libraries: libsodium.so.18

### ISSUE THREAD

**Issue by pontikis** [phw/peek#286]
Peek: 1.2.2
GTK: 3.18.9
GLib: 2.48.2

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 1243x756 -i :0.0+288,229 -filter:v scale=iw/1:-1 -codec:v libx264rgb -preset:v ultrafast -crf 0 -r 10 -y /home/pontikis/.cache/peek/peek6F4SEZ.mkv" failed with status 32512 (received signal 0).

Output:
ffmpeg: error while loading shared libraries: libsodium.so.18: cannot open shared object file: No such file or directory
```

**Comment by phw** [comment]
That's seems to be a ffmpeg install issue. What distribution is this and how did you install ffmpeg? How was Peek installed?

**Comment by pontikis** [comment]
Hello @phw ! Yes, you are right. I have `libsodium.so.23.1.0` in Xubuntu 16.04 LTS.
So, symlinking

`ln -s libsodium.so.23.1.0 libsodium.so.18`

seems to solve the problem. Thanks! 

(Peek installed using https://github.com/phw/peek#ubuntu)

**Comment by pontikis** [comment]
@phw I suppose you may close the issue. Thanks!

**Comment by phw** [comment]
@pontikis Yes, that is not the version from official 16.04 repositories. You probably installed that one via a PPA. I would personally stay away from PPAs that install entire new versions for system level libs, that's just calling for trouble :)
