### ISSUE TITLE
Support for capturing static screenshots?

### ISSUE THREAD

**Issue by akavel** [phw/peek#292]
Would you consider supporting capturing of static (1-frame) screenshots (as e.g. PNG, not APNG)? The UI framing idea of Peek is very nice and would be cool to be able to use it for both purposes. Though I'm aware it's introducing some risk of feature bloat; that's why I'm posing it as a question. By the way, before asking, I tried searching if somebody already asked such question/proposal (was pretty sure somebody must have asked for this already), but I couldn't find anything relevant in Issues with "static" nor "screenshot" keywords... also haven't seen anything related in the FAQ in the Readme...

**Comment by phw** [comment]
This was asked, at lease indirectly, in the past. This might be something that could be added, but to be honest it has a rather low priority for me, as Peek was always meant to fix my needs for a quick and easy little screen recorder.

If this gets added, it's UI should be really minimal and should not interfere with the current minimal UI. One idea would be to add "Screenshot" as just another output format with special handling.

**Comment by furai** [comment]
This would be really cool feature to have.

**Comment by lmj0011** [comment]
In the meantime... If using linux (ubuntu) you can install

`sudo apt install gnome-screenshot`

`gnome-screenshot -a`

select area on screen to capture

screenshot should save in Pictures directory

only downside to this method is that you can't defined the area, because there's no numbers visible.

ref: https://askubuntu.com/a/896006/393264

**Comment by furai** [comment]
I'm using `import` for that - package from imagemagick.
Only problem I have with it is that sometimes the selection rectangle bugs out and becomes part of the screenshot.

**Comment by phw** [comment]
I will close this. Peek was developed to capture short animations of parts of your screen, I have no interest in  turning it into a general purpose screenshot utility.

**Comment by thhart** [comment]
Hi Philip, is it possible to specify a more detailed reasoning? Do you fear any special bad influence if the utility turns into a generic purpose utility? What if I introduce a pull request for such a feature?
