### ISSUE TITLE
[bug] Using non-standard locale name for Chinese (zh_Hans, zh_Hant)

### ISSUE THREAD

**Issue by hosiet** [phw/peek#294]
While examining the default installation of peek into system, I found the following files:

```
[...]
drwxr-xr-x root/root         0 2018-03-16 10:07 ./usr/share/locale/uk_UA/
drwxr-xr-x root/root         0 2018-03-16 10:07 ./usr/share/locale/uk_UA/LC_MESSAGES/
-rw-r--r-- root/root      7070 2018-03-16 10:07 ./usr/share/locale/uk_UA/LC_MESSAGES/peek.mo
drwxr-xr-x root/root         0 2018-03-16 10:07 ./usr/share/locale/zh_Hans/
drwxr-xr-x root/root         0 2018-03-16 10:07 ./usr/share/locale/zh_Hans/LC_MESSAGES/
-rw-r--r-- root/root      8580 2018-03-16 10:07 ./usr/share/locale/zh_Hans/LC_MESSAGES/peek.mo
drwxr-xr-x root/root         0 2018-03-16 10:07 ./usr/share/locale/zh_Hant/
drwxr-xr-x root/root         0 2018-03-16 10:07 ./usr/share/locale/zh_Hant/LC_MESSAGES/
-rw-r--r-- root/root      7161 2018-03-16 10:07 ./usr/share/locale/zh_Hant/LC_MESSAGES/peek.mo
drwxr-xr-x root/root         0 2018-03-16 10:07 ./usr/share/man/
drwxr-xr-x root/root         0 2018-03-16 10:07 ./usr/share/man/man1/
-rw-r--r-- root/root       927 2018-03-16 10:07 ./usr/share/man/man1/peek.1.gz
[...]
```

Using `zh_Hans` and `zh_Hant` in `/usr/share/locale/` directory is weird. Almost **all** other applications on Linux install them into directories named `zh_CN` and `zh_TW` (which somehow represents the simplified variant of Chinese and the traditional variant of Chinese).

**Comment by phw** [comment]
Thanks for the bug report. The directory naming is a direct result of the translation tool used for Peek, I have to figure out how to best deal with this.

@nijel Any thoughts on this?

**Comment by nijel** [comment]
This is actually standard name. You can find reasoning in several places (eg. https://code.djangoproject.com/ticket/18419) - it doesn't make sense to bind traditional/simplified variants with country as they are used in more countries. Still if you prefer to use zh_CN and zh_TW for some reason, just rename the files and Weblate will work just fine.

**Comment by hosiet** [comment]
While I understand that `zh_CN` and `zh_TW`cannot fully represent Simplified Chinese and Traditional Chinese, binding country/region with translation is reasonable since each region has different standards in character and words. For example,

* `zh_CN` is for Chinese in China mainland, a simplified Chinese variant
* `zh_SG` is for Chinese in Singapore, a simplified Chinese variant
* `zh_HK` is for Chinese in Hong Kong SAR, a traditional Chinese variant
* `zh_TW` is for Chinese in Taiwan, a traditional Chinese variant

The ideal situation is that we organize translations for all those variants (which happens in some large projects like KDE). With smaller projects, `zh_TW` is used to represent Simplified Chinese and `zh_CN` is used to represent Traditional Chinese.

* * *

Well those above is not the most important reason. The most important thing is that current installation will make Chinese translations invalid because the system only recognize .mo files inside `zh_CN` dir if locale is set to `zh_CN`. Files under `/usr/share/locale/zh_Hans/` simply won't work and that is a bug.

**Comment by nijel** [comment]
The problem with country based names is that you want to use same translation for zh_CN and zh_SG, similarly for zh_HK and zh_TW.

As written before, Weblate will work with any naming, feel free to rename the files to whatever you find appropriate. It defaults to follow standards when creating new translations, but it's flexible in accepting other naming.

**Comment by phw** [comment]
@nijel Thanks for the input. I have renamed the files now, glad to hear weblate can deal with this naming.

For desktop use it completely makes sense to follow this naming. Peek was literally the only software installed on my system which used the zh_Hans and zh_Hant naming.
