### ISSUE TITLE
Missing original xml spec files for dbus interface in /src/dbus/ directory

### ISSUE THREAD

**Issue by hosiet** [phw/peek#296]
Vala source files in `/src/dbus` directory are generated from D-Bus XML spec files. However, those xml files are not provided.

This problem seems pedantic but it is rather important for Debian downstream. Debian requires all generated files in the project shall be provided together with its original form.

It would be great if you could point out where those original XML files came from. The best plan is that you provide those XML files under the same directory as those generated Vala files, which would circumvent this problem and satisfy Debian's policy.

**Comment by phw** [comment]
Those files are generated from the respective upstream sources. I have to lookup this. But I find it a bit strange, as the files are essentially parts of other projects. Would a script be sufficient that pills upstream sources and builds the files?

Also you should be aware that vala-dbus-binding-tool is not perfect and the generated files might need some manual tweaking. As far as I remember this was the case for at least one of the interfaces. I don't really consider those files auto generated files in the sense that you could include this in your build process. Rather vala-dbus-binding-tool was used as a scaffolding tool, more like you might use code snippets in your editor to speed up writing repetitive code.

**Comment by hosiet** [comment]
As long as enough information is provided (in git repo, not in issue tracker) to show those files' origin, I don't want to bother with it too. It's just that Debian's package reviewer might catch and raise the issue later thus preparation in advance is preferable.

Their origin is needed even if actually came from another project. Please provide those information if you could.

**Comment by hosiet** [comment]
Thanks, that helps.
