### ISSUE TITLE
I have this isue

### ISSUE THREAD

**Issue by hulkco** [phw/peek#297]
Peek: 1.2.2
GTK: 3.18.9
GLib: 2.48.2

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 280x97 -i :0+829,211 -filter:v scale=iw/1:-1 -codec:v libx264rgb -preset:v ultrafast -crf 0 -r 10 -y /home/greynaga/.cache/peek/peekBP5VFZ.mkv" failed with status 32512 (received signal 0).

Output:
ffmpeg: error while loading shared libraries: libvdpau.so.1: cannot open shared object file: No such file or directory
```

**Comment by phw** [comment]
Please make sure you have a working ffmpeg on your system. How did you install ffmpeg? What distribution are you using? There should be some package providing the missing  libvdpau library.

**Comment by hulkco** [comment]
Thanks for the reply,  i made your sugesstion right now :)

**Comment by hulkco** [comment]
Ok,  the problem its the ffmpeg installed in my sistema,  thanks,  i close the isue
