### ISSUE TITLE
Showing save dialog when rendering is started

### ISSUE THREAD

**Issue by fb87** [phw/peek#30]
Could you please implement showing the file chooser for saving the GIF directly after recording is finished? This way rendering can run in the background and we can make the next record without having to wait for the previous rendering to finish. While showing the file chooser, rendering can start in a parallel thread for further speed up. :)

**Comment by phw** [comment]
Great suggestion, I think this will really improve the user experience and should not be difficult to implement.

**Comment by pepa65** [comment]
I need a slight delay before it pops up, sometimes it gets captured at the end.

**Comment by phw** [comment]
@pepa65: Can you open a new issue for this? Comments in long closed comments are likely to be forgotten. Thanks.
