### ISSUE TITLE
Hotkey for starting/stopping recording session.

### ISSUE THREAD

**Issue by FizzyGalacticus** [phw/peek#303]
While I really like the simple interface, my biggest issue is that there are no hotkeys to start/stop recording. It really takes away from recordings when you see the mouse move to/from the button.

I've been using https://github.com/MaartenBaert/ssr which has this feature, although ssr is much more complex than anything I really need. It would be really awesome to incorporate some kind of hotkey feature into peek.

**Comment by phw** [comment]
A Hotkey for starting / stopping the recording is already supported and can be configured in Peek's preferences. The default is Ctrl + Alt + R

An exception is if you use Wayland (Gnome Wayland, other desktop environments are not yet supported on Wayland), in this case global hotkeys are unsupported. In this case you can configure a hotkey in the desktop environment and bind it to `peek --toggle`

You can also use this truck if Peek's global hotkeys don't work for you.
