### ISSUE TITLE
Could not start recording

### ISSUE THREAD

**Issue by conde2** [phw/peek#317]
Peek: 1.3.1
GTK: 3.22.28
GLib: 2.54.3

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

OBS:
I have both installed x264 codec and gstreamer ugly plugins

running with: peek -b ffmpeg it does not show the error but only records the mouse pointer moving and a black screen behind

OS: Arch Linux

**Comment by phw** [comment]
Please take a look at the logs in journalctl, gnome shell should report some more details about the error.

> running with: peek -b ffmpeg it does not show the error but only records the mouse pointer moving and a black screen behind

That indicates you are using Wayland, ffmpeg cannot record on Wayland.

**Comment by conde2** [comment]
May 03 14:25:24 archlinux gnome-shell[722]: ShellRecorder: failed to parse pipeline: no element "x264enc"
May 03 14:25:24 archlinux gnome-shell[722]: shell_recorder_close: assertion 'recorder->state != RECORDER_STATE_CLOSED' failed
May 03 14:25:25 archlinux gnome-shell[722]: Object Meta.WindowActor (0x559b01f94450), has been already finalized. Impossible to get any pr>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: == Stack trace for context 0x559aff1b4000 ==
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #0 0x7ffecc4425a0 b   resource:///org/gnome/shell/ui/tweener.js:73 (0x7fe55c0ddef0>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #1 0x7ffecc442db0 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7fe55c0df23>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #2 0x559aff4c8bb0 i   resource:///org/gnome/shell/ui/tweener.js:92 (0x7fe55c0df098>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #3 0x7ffecc444190 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:203 (0x>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #4 0x7ffecc4442e0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:332 (0x>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #5 0x7ffecc444390 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:345 (0x>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #6 0x7ffecc444420 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:360 (0x>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #7 0x7ffecc4444a0 I   resource:///org/gnome/gjs/modules/signals.js:126 (0x7fe55c0e>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #8 0x7ffecc444550 b   resource:///org/gnome/shell/ui/tweener.js:208 (0x7fe55c0df80>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #9 0x7ffecc4445b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe55c0c2>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #10 0x7ffecc444660 b   resource:///org/gnome/shell/ui/tweener.js:183 (0x7fe55c0df7>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #11 0x7ffecc4446f0 I   self-hosted:917 (0x7fe55c0ee5e8 @ 394)
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: == Stack trace for context 0x559aff1b4000 ==
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #0 0x7ffecc4425a0 b   resource:///org/gnome/shell/ui/tweener.js:80 (0x7fe55c0ddef0>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #1 0x7ffecc442db0 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7fe55c0df23>
May 03 14:25:25 archlinux org.gnome.Shell.desktop[722]: #2 0x559aff4c8bb0 i   resource:///org/gnome/shell/ui/tweener.js:92 (0x7fe55c0df098>

**Comment by phw** [comment]
@conde2 You are missing the x264 codec. On Arch you need to install `gst-plugins-ugly` for this.

**Comment by conde2** [comment]
![screenshot from 2018-05-03 16-41-41](https://user-images.githubusercontent.com/2137569/39599143-3803ce80-4ef1-11e8-8d8e-1c464e1a1a85.png)

I've installed it and x264 codec and still have the same problem.

**Comment by phw** [comment]
Again we need the output from gnome-shell in the journal, otherwise it's just guessing. Could be the same issue, could be something different now.

It is possible that gnome-shell needs to be restarted after the plugins have been installed, not sure about that.

**Comment by pablox-cl** [comment]
If you are on wayland, you need to log out and log in, since there's  no way to restart gnome shell "live", as you could on X.

**Comment by phw** [comment]
Please refer to the answers on https://github.com/phw/peek/issues/287
