### ISSUE TITLE
I don't what the error is. I saw this window asking me to report an error so I'm reporting. 

### ISSUE THREAD

**Issue by numoonchld** [phw/peek#319]
Peek: 1.3.1
GTK: 3.22.25
GLib: 2.54.1

Details:
```
Missing output file after post processing.
```

**Comment by phw** [comment]
This is one situation where the reported error does not really help identifying the issue :(

Can you:

    Before Launching Peek, run journalctl -f
    Start Peek from command line with G_MESSAGES_DEBUG=all ./peek, reproduce the error and post the output here together with any related output from journalctl above (there might be some gnome-shell errors).

I assume this is on Gnome? X11 or Wayland?

As a workaround if you are on Gnome / X11 try running peek with the ffmpeg backend by launching peek -b ffmpeg

**Comment by numoonchld** [comment]
Unfortunately, I haven't been able to recreate the issue again. It was a Gnome Ubuntu on a macbook, so I reverted back to the default OS because of a bunch of other driver issues.
