### ISSUE TITLE
Could not start recording, already an active recording using org.gnome.Shell.Screencast?

### ISSUE THREAD

**Issue by hcal** [phw/peek#325]
Peek: 1.3.1
GTK: 3.22.26
GLib: 2.54.3

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

As far as I can tell there is no other screen recording active.   I get this error when recording an mpg, but not when recording a gif.  I'm on wayland if that matters.  Also, the program works well enough for me and I'm providing feed back because I thought it might help the project.  If not please close.

**Comment by AlexWayfer** [comment]
Duplicate of #287, I think.

**Comment by phw** [comment]
Thanks for reporting.

Yes. Please make sure you have gstreamer ugly plugins installed and also the H264 codec. If that does not solve your issue, have a look at the gnome shell output in journalctl.

**Comment by RezaIr7200** [comment]
I have same problem
Gnome log:
`gnome-shell[2783]: Ignoring excess values in shadow definition`
