### ISSUE TITLE
Setting fps for gifs

### ISSUE THREAD

**Issue by Ranguna** [phw/peek#338]
Hello, first of all awesome tool !

Is there any way to change the fps of the gifs ?

I didn't find any documentation on how to do this and the help command didn't really help with this.

Thanks :+1:

**Comment by gort818** [comment]
Go to preferences and change the framerate.

**Comment by Ranguna** [comment]
Thanks but where are the preferences ?

**Comment by gort818** [comment]
![screenshot_20180719_164707](https://user-images.githubusercontent.com/9098121/42975858-71bf59b4-8b73-11e8-945c-c390ec9fd931.png)

**Comment by gort818** [comment]
are you using Gnome? Should be at the top in the task bar.

**Comment by Ranguna** [comment]
Yep it was in the task bar.

Thank you very much and keep it up :ok_hand:
