### ISSUE TITLE
build from src (redhat) "glib-gio-error: com.uploadedlobster.peel is not installed"

### ISSUE THREAD

**Issue by pberto** [phw/peek#344]
Hello,
I have built successfully peek (master branch, 1.2.2-103-g5def79a) on RedHat 7.5 using CMAKE.
When running peek I am getting:

```(peek:10759): GLib-GIO-ERROR **: Settings schema 'com.uploadedlobster.peek' is not installed```

Any idea how to get this running?

**Comment by phw** [comment]
The schema needs to be installed. I guess you haven't use `make install` to install Peek on your system but try to run from the build dir instead, right?

If you don't want to install Peek the easiest way to just install the schema is probably to copy `data/com.uploadedlobster.peek.gschema.xml` to `/usr/local/share/glib-2.0/schemas/` and then run:

    glib-compile-schemas /usr/local/share/glib-2.0/schemas/

I actually had some code to compile and load the schema from the local data dir, but this worked only with CMake anyway and I never got it ported to Meson and it is very hackish and only meant for quickly running locally for development purposes. I don't know if this still works and will remove the still existent code related to this.
