### ISSUE TITLE
No way to enter preferences window in Gnome 3

### ISSUE THREAD

**Issue by szoper** [phw/peek#345]
I've installed Peek using [AUR](https://aur.archlinux.org/packages/peek/) package in [Manjaro GNOME Edition](https://manjaro.org/get-manjaro/) with Gnome 3.28 and the application window looks like this (notice the title bar).

![Peek @Gnome3](https://user-images.githubusercontent.com/2564066/43631869-b3f22e5a-9704-11e8-862e-d1b7afd3ee8b.png)

There is no Peek icon in the top right corner I could use to enter the preferences. I remember that when I was running Kubuntu it was there.

If you need any additional information about my environment - I'm here to help.
Peek is a brilliant app - powerful, yet plain simple to use. Thank you for your work.

**Comment by hosiet** [comment]
As a GNOME user, you should be aware that top menu can be opened by clicking on the top icon using right mouse button.

**Comment by szoper** [comment]
Ouch, you're right.
I'm wondering if anything can be done to facilitate this. I even hoped for a runtime argument to open the preferences from CLI.

**Comment by phw** [comment]
@szoper If you don't like the App menu at the top you can disable it with GNOME Tweak. Peek will then use the default fallback, which is providing the App menu in the application toolbar.
