### ISSUE TITLE
Flatpak install fails with "The Application com.uploadedlobster.peek/x86_64/stable requires the org.gnome.Platform/x86_64/3.26 which was not found" under Ubuntu 18.04 bionic: 

### ISSUE THREAD

**Issue by bentolor** [phw/peek#364]
I' trying to circumvent #363 and tried a 

```
$ sudo flatpak install --user https://flathub.org/repo/appstream/com.uploadedlobster.peek.flatpakref
Fehler: The Application com.uploadedlobster.peek/x86_64/stable requires the org.gnome.Platform/x86_64/3.26 which was not found
```

I'm not proficient enough with Flatpak to understand if this is a Flatpak-issue or one with the Peek Flatpak bundle.

This is the output of `flatpak info`:

```
$ flatpak info org.gnome.Platform
Ref: runtime/org.gnome.Platform/x86_64/3.28
Kennung: org.gnome.Platform
Architektur: x86_64
Zweig: 3.28
Ursprung: flathub
Collection ID: org.flathub.Stable
Date: 2018-08-30 19:06:39 +0000
Subject: build of org.gnome.Sdk, Thu Aug 30 11:32:42 UTC 2018
Commit: 9d3fe926d425ad837e40a0945020a00f09c1f531335987a753e07f276d76ee36
Parent: f5ad47d93872b617a6a05227d82e04481bc5a236c7299d04005e3c1f306f76d8
Ort: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.28/9d3fe926d425ad837e40a0945020a00f09c1f531335987a753e07f276d76ee36
Installierte Größe: 1,3 GB
```

I did not explicitly install this version of the Gnome plattform. It was implicitly fetched by installing Gradio via Flatpak

**Comment by phw** [comment]
Actually Flatpak should install the required runtime itself, I'm not sure why it doesn't. You should probably bring this up on https://github.com/flatpak/flatpak/issues

However, to manually fix the issue you should be able to manually install it by running

    flatpak install flathub org.gnome.Platform//3.26

**Comment by bentolor** [comment]
@phw I assumed that too. Really having a hard time with Flatpak. It mostly does not work at-all yet. Hopefully it will graduate soon.

Thanks for you quick reply. I reported it upstream. See linked issue.
