### ISSUE TITLE
Visual improvements to file type chooser

### ISSUE THREAD

**Issue by bertob** [phw/peek#368]
The file type chooser is great functionally, but doesn't look as good as it could.

![image](https://user-images.githubusercontent.com/1908896/46281821-138fcb80-c570-11e8-87b7-b5bc120fb5bc.png)

Two simple changes could improve that a lot:
- merging the two adjacent buttons in the headerbar into a combined button
- getting rid of the button style on the options in the popover and adding an indicator for which one is active

Here's what that could look like:

![image](https://user-images.githubusercontent.com/1908896/46441024-90d06180-c765-11e8-89df-44941bd22562.png)

**Comment by phw** [comment]
This was basically implemented in recent releases
