### ISSUE TITLE
DbusActivatable is not a valid key for a desktop file

### ISSUE THREAD

**Issue by probonopd** [phw/peek#393]
Does not pass desktop-file-validate in Ubuntu trusty:

```
com.uploadedlobster.peek.desktop: error: file contains key "DBusActivatable" in group "Desktop Entry", but keys extending the format should start with "X-"
ERROR: Desktop file contains errors. Please fix them. Please see
       https://standards.freedesktop.org/desktop-entry-spec/latest/
       for more information.
user@clr-b8cf94b408544d1a88c7b8ad7
```

The [DBusActivatable](https://wiki.gnome.org/HowDoI/DBusApplicationLaunching) key is not allowable as per the 1.0 desktop file spec. (Why didn't they call it `X-DBusActivatable`?)

**Comment by phw** [comment]
Your validator is likely outdated, this key is part of the spec:

https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by probonopd** [comment]
Yes, we are using the validator from trusty.
