### ISSUE TITLE
Ubuntu 18.10 cannot add ppa because of not existing "Release File"

### ISSUE THREAD

**Issue by Naoray** [phw/peek#396]
![image](https://user-images.githubusercontent.com/10154100/48951213-01ae2180-ef3e-11e8-8d5b-67188bd1e335.png)

**Comment by Naoray** [comment]
ended up adding the daily repository `ppa:peek-developers/daily`

**Comment by uusijani** [comment]
Alternatively, after adding the PPA, replace 'cosmic' with 'bionic' in the sources list, as the package for Bionic currently appears to install and work in Cosmic just fine (from my brief testing).

**Comment by aplatypus** [comment]
This is strange.  I installed `peek` just yesterday and today the update failed (still):

    sudo apt update
    Err:14 http://ppa.launchpad.net/peek-developers/stable/ubuntu cosmic Release
      404  Not Found [IP: 91.189.95.83 80]
    Reading package lists... Done                      
    E: The repository 'http://ppa.launchpad.net/peek-developers/stable/ubuntu cosmic Release' does not have a Release file.
    N: Updating from such a repository can't be done securely, and is therefore    disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.

Is this just some intermintient problem that drops-out and thenget better from time to time?

**Comment by axel1200** [comment]
same issue here

**Comment by axel1200** [comment]
Really annoying

**Comment by axel1200** [comment]
```
E: The repository 'http://ppa.launchpad.net/pinta-maintainers/pinta-stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease' changed its 'Label' value from 'Oracle Java (JDK) 8 Installer PPA' to 'Oracle Java (JDK) 8 Installer PPA (DISCONTINUED)'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

**Comment by phw** [comment]
@axel1200 please report issues with the pinta PPA to whoever maintains that PPA, this has nothing to do with Peek

**Comment by axel1200** [comment]
Well u mention it on your read me, so I assume so

**Comment by axel1200** [comment]
Maybe you should take it out of the read me then :D

**Comment by phw** [comment]
@axel1200 What I'm saying is that you reported an issue with a PPA called `ppa:pinta-maintainers/pinta-stable`, this has nothing to do with this project (Peek) nor the README here. I don't know what pinta is, but issues with their repository should be reported there.

Peek is available from ppa:peek-developers/stable

**Comment by phw** [comment]
Currently supported PPAs are for Ubuntu 18.04, 19.04 and 19.10 and they should all be up-to-date and working.
