### ISSUE TITLE
Screen flickering during recording

### ISSUE THREAD

**Issue by phw** [phw/peek#4]
On some systems the screen flickers druing recording

**Comment by phw** [comment]
Looks like this is an issue with DRI3 on intel. Same flickering happens with other screen recording software, goes away immediately if switching to DRI2. I don't think there is anything that can be done in Peek.

**Comment by bobblkabb** [comment]
For me disabling changing vsync option in Plasma (5.14.3) did the trick:

**Option:**
_Tear prevention (vsync) = Never_
**Settings path:**
_System Settings > Hardware > Display and Monitor > Compositor Settings for Desktop Effects_

**Comment by undernature** [comment]
> For me disabling changing vsync option in Plasma (5.14.3) did the trick:
> 
> **Option:**
> _Tear prevention (vsync) = Never_
> **Settings path:**
> _System Settings > Hardware > Display and Monitor > Compositor Settings for Desktop Effects_

Thanks a lot, bobblkabb, it works !!!
