### ISSUE TITLE
peek App

### ISSUE THREAD

**Issue by wwwjay** [phw/peek#402]
Peek: 1.3.1
GTK: 3.22.26
GLib: 2.54.3

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by wwwjay** [comment]
What could be the reason for this ?

**Comment by phw** [comment]
The most common cause of this are missing gstreamer-good- or gstreamer-ugly-plugins packages. If you record MP4 and get this error this usually means the h.264 codec is missing, which usually is provided by the gstreamer-ugly-plugins package. Refer to your distribution's documentation on how to install it

You can also look into the output of `journalctl`, there should be some gnome-shell logging with more details.

**Comment by wwwjay** [comment]
Let me have a look thanks.

**Comment by phw** [comment]
See also #287
