### ISSUE TITLE
Building on Fedora

### ISSUE THREAD

**Issue by m-kuhn** [phw/peek#41]
Not directly an issue but I thought I'd write down the process which can be integrated in the readme or another file for build instructions.

Dependencies
---------
```bash
sudo dnf install vala gtk3-devel ffmpeg
```

Clone and build
----------

```bash
git clone git@github.com:phw/peek.git
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ../peek && make
./peek # Simply run from build folder
sudo make install # Install to system
```

Using Ninja
----------

```bash
# For people who prefer spending less time to build ;)
cmake -DCMAKE_INSTALL_PREFIX=/usr -GNinja ../peek
ninja-build
# or directly
sudo ninja-build install
```

And by the way: Awesome, Thanks a lot :tada:  !!

**Comment by phw** [comment]
Thanks a lot for this, I want to update the README anyway to add more installation instructions and a FAQ section, will take care of this then.

**Comment by sincerefly** [comment]
Thanks!

**Comment by phw** [comment]
I have updated the README with Fedora instructions. Also thanks for sharing the ninja example, tried it and love it. Builds indeed faster. But I decided against adding it to the README in order to not complicate things
