### ISSUE TITLE
double free or corruption (fasttop)

### ISSUE THREAD

**Issue by bitshiftnetau** [phw/peek#411]
Arch Linux: 4.19.13-1-lts
Peek 1.3.1

Once at the save window, program crashes.

$ G_MESSAGES_DEBUG=all peek
(peek:4641): Gtk-DEBUG: 11:43:24.226: Connecting to session manager
(peek:4641): Gtk-DEBUG: 11:43:24.227: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(peek:4641): Gtk-DEBUG: 11:43:24.228: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(peek:4641): Gtk-DEBUG: 11:43:24.229: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
** (peek:4641): DEBUG: 11:43:24.229: desktop-integration.vala:168: Desktop: 
(peek:4641): dconf-DEBUG: 11:43:24.229: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(peek:4641): dconf-DEBUG: 11:43:24.230: unwatch_fast: "/org/gnome/desktop/interface/" (active: 0, establishing: 1)
** (peek:4641): DEBUG: 11:43:24.230: application.vala:286: GTK theme: Adwaita
** (peek:4641): DEBUG: 11:43:24.230: desktop-integration.vala:168: Desktop: 
** (peek:4641): DEBUG: 11:43:24.230: application.vala:341: Decoration layout: menu:minimize,maximize,close
** (peek:4641): DEBUG: 11:43:24.230: desktop-integration.vala:168: Desktop: 
(peek:4641): dconf-DEBUG: 11:43:24.230: watch_fast: "/com/uploadedlobster/peek/" (establishing: 0, active: 0)
(peek:4641): dconf-DEBUG: 11:43:24.230: watch_established: "/org/gnome/desktop/interface/" (establishing: 0)
(peek:4641): dconf-DEBUG: 11:43:24.230: watch_established: "/com/uploadedlobster/peek/" (establishing: 1)
** (peek:4641): DEBUG: 11:43:24.231: application.vala:221: Changed keybinding_toggle_recording  => <Ctrl><Alt>R

** (peek:4641): DEBUG: 11:43:24.231: desktop-integration.vala:168: Desktop: 
(peek:4641): GLib-DEBUG: 11:43:24.231: posix_spawn avoided (fd close requested) 
** (peek:4641): DEBUG: 11:43:24.233: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

Using screen recorder backend ffmpeg
** (peek:4641): DEBUG: 11:43:24.300: application-window.vala:884: Decoration layout: menu:minimize,maximize,close
** (peek:4641): DEBUG: 11:43:24.375: recording-area.vala:38: Absolute recording area x: 2, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:24.375: recording-area.vala:45: Screen w: 1280, h: 800
** (peek:4641): DEBUG: 11:43:24.375: recording-area.vala:58: Clipped recording area x: 2, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:24.375: recording-area.vala:69: Scaled recording area x: 2, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:24.416: recording-area.vala:38: Absolute recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:24.416: recording-area.vala:45: Screen w: 1280, h: 800
** (peek:4641): DEBUG: 11:43:24.416: recording-area.vala:58: Clipped recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:24.416: recording-area.vala:69: Scaled recording area x: 222, y: 45, w: 498, h: 298
(peek:4641): GdkPixbuf-DEBUG: 11:43:24.419: gdk_pixbuf_from_pixdata() called on:
(peek:4641): GdkPixbuf-DEBUG: 11:43:24.419: 	Encoding raw
(peek:4641): GdkPixbuf-DEBUG: 11:43:24.419: 	Dimensions: 16 x 16
(peek:4641): GdkPixbuf-DEBUG: 11:43:24.419: 	Rowstride: 64, Length: 1048
(peek:4641): GdkPixbuf-DEBUG: 11:43:24.419: 	Copy pixels == false
** (peek:4641): DEBUG: 11:43:27.968: desktop-integration.vala:168: Desktop: 
** (peek:4641): DEBUG: 11:43:27.968: application-window.vala:641: freeze_window_size w: 502, h: 345
** (peek:4641): DEBUG: 11:43:27.993: recording-area.vala:38: Absolute recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:27.993: recording-area.vala:45: Screen w: 1280, h: 800
** (peek:4641): DEBUG: 11:43:27.993: recording-area.vala:58: Clipped recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:27.993: recording-area.vala:69: Scaled recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:29.049: recording-area.vala:38: Absolute recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:29.050: recording-area.vala:45: Screen w: 1280, h: 800
** (peek:4641): DEBUG: 11:43:29.050: recording-area.vala:58: Clipped recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:29.050: recording-area.vala:69: Scaled recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:30.050: recording-area.vala:38: Absolute recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:30.050: recording-area.vala:45: Screen w: 1280, h: 800
** (peek:4641): DEBUG: 11:43:30.050: recording-area.vala:58: Clipped recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:30.050: recording-area.vala:69: Scaled recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:31.050: recording-area.vala:38: Absolute recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:31.050: recording-area.vala:45: Screen w: 1280, h: 800
** (peek:4641): DEBUG: 11:43:31.050: recording-area.vala:58: Clipped recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:31.050: recording-area.vala:69: Scaled recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:31.050: application-window.vala:512: Recording area: 222, 45, 498, 298

** (peek:4641): DEBUG: 11:43:31.051: utils.vala:23: Cache directory does already exist /home/access/.cache/peek

** (peek:4641): DEBUG: 11:43:31.051: utils.vala:38: Temp file: /home/access/.cache/peek/peekYA1OVZ.webm

(peek:4641): GLib-DEBUG: 11:43:31.051: posix_spawn avoided (fd close requested) (child_setup specified) 
** (peek:4641): DEBUG: 11:43:31.063: recording-area.vala:38: Absolute recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:31.064: recording-area.vala:45: Screen w: 1280, h: 800
** (peek:4641): DEBUG: 11:43:31.064: recording-area.vala:58: Clipped recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:31.064: recording-area.vala:69: Scaled recording area x: 222, y: 45, w: 498, h: 298
** (peek:4641): DEBUG: 11:43:40.620: base-screen-recorder.vala:55: Recording stopped
** (peek:4641): DEBUG: 11:43:41.115: cli-screen-recorder.vala:34: recording process exited, term_sig: 0, exit_status: 0, success: true
** (peek:4641): DEBUG: 11:43:41.124: Temporary file /home/access/.cache/peek/peekYA1OVZ.webm, 146224 bytes
** (peek:4641): DEBUG: 11:43:41.124: base-screen-recorder.vala:67: Started post processing
(peek:4641): GLib-DEBUG: 11:43:41.124: posix_spawn avoided (fd close requested) 
** (peek:4641): DEBUG: 11:43:41.128: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

** (peek:4641): DEBUG: 11:43:41.128: post-processing-pipeline.vala:30: Running post processor PeekPostProcessingFfmpegPostProcessor with files 1
** (peek:4641): DEBUG: 11:43:41.128: utils.vala:23: Cache directory does already exist /home/access/.cache/peek

** (peek:4641): DEBUG: 11:43:41.128: utils.vala:38: Temp file: /home/access/.cache/peek/peek9R6PVZ.png

(peek:4641): GLib-DEBUG: 11:43:41.128: posix_spawn avoided (fd close requested) (child_setup specified) 
(peek:4641): dconf-DEBUG: 11:43:41.302: watch_fast: "/org/gtk/settings/file-chooser/" (establishing: 0, active: 0)
(peek:4641): dconf-DEBUG: 11:43:41.303: watch_established: "/org/gtk/settings/file-chooser/" (establishing: 1)
** (peek:4641): DEBUG: 11:43:41.303: application-window.vala:697: Showing file chooser (GtkFileChooserNative)
** (peek:4641): DEBUG: 11:43:41.388: utils.vala:23: Cache directory does already exist /home/access/.cache/peek

** (peek:4641): DEBUG: 11:43:41.389: utils.vala:38: Temp file: /home/access/.cache/peek/peekHNLKVZ.gif

(peek:4641): GLib-DEBUG: 11:43:41.389: posix_spawn avoided (fd close requested) (child_setup specified) 
double free or corruption (fasttop)
Aborted (core dumped)

**Comment by freddii** [comment]
same here:
freddii@debian:~$ peek
Using screen recorder backend ffmpeg
double free or corruption (fasttop)
Aborted
freddii@debian:~$ peek --version
Peek 1.3.1

**Comment by cdluminate** [comment]
Same here on Debian sid.

**Comment by cdluminate** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926386

**Comment by cdluminate** [comment]
This issue is duplicated. See https://github.com/phw/peek/issues/419

**Comment by phw** [comment]
Fixed, closing as duplicate of #419
