### ISSUE TITLE
Failed to record

### ISSUE THREAD

**Issue by beeblebrox3** [phw/peek#412]
Peek: 1.3.1
GTK: 3.22.29
GLib: 2.56.0

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 932x439 -i :0+122,160 -filter:v scale=iw/1:-1, crop=iw-mod(iw\,2):ih-mod(ih\,2) -codec:v libx264 -preset:v fast -profile:v baseline -pix_fmt yuv420p -r 10 -y /home/luis/.cache/peek/peek5NHYVZ.mp4" failed with status 256 (received signal 0).

Output:
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)  configuration: --disable-x86asm  libavutil      56. 22.100 / 56. 22.100  libavcodec     58. 35.100 / 58. 35.100  libavformat    58. 20.100 / 58. 20.100  libavdevice    58.  5.100 / 58.  5.100  libavfilter     7. 40.101 /  7. 40.101  libswscale      5.  3.100 /  5.  3.100  libswresample   3.  3.100 /  3.  3.100Unrecognized option 'preset:v'.Error splitting the argument list: Option not found
```

**Comment by phw** [comment]
Thanks for the report. Your ffmpeg was compiled without some required functionality. How did you install ffmpeg? From source or from distribution?

If you installed from source please see https://github.com/phw/peek/blob/master/data/flatpak/flatpak-stable.yml#L35 for a list of minimal configure options required for ffmpeg to be used by Peek.

If you use Anaconda this is a frequent cause of issues like this. In this case make sure `$HOME/anaconda3/bin/` is not in your `$PATH` variable. See also https://github.com/phw/peek/issues/304

**Comment by beeblebrox3** [comment]
@phw I'm not sure, probably `apt-get` from official repos of my distro. But I did "clean install" and is working now. Thanks!
