### ISSUE TITLE
Weird flickering in image whenever I try to scroll

### ISSUE THREAD

**Issue by laurybueno** [phw/peek#42]
First of all, thanks a lot for the great work in this app and thanks for also maintaining the arch package yourself :)

I'm using Cinnamon with Arch (Antergos install) on two computers and always get a weird effect in the recorded GIF during scrolling.

Any chances you know what I may be missing?

![blue-hack](https://cloud.githubusercontent.com/assets/1108897/20038772/62ca00e4-a420-11e6-983e-270a84ae2a44.gif)

Thanks again!

EDIT: the Link image is my desktop background

**Comment by phw** [comment]
That's most likely a driver issue, I have seen similar in the past with screen recording and remote desktop software.

If you are using Intel graphics, try switching between UXA and SNA, see https://wiki.archlinux.org/index.php/intel_graphics#SNA_issues

**Comment by laurybueno** [comment]
It works perfectly now! Thanks a lot for your time!
