### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by fabiomarquesyj** [phw/peek#420]
Peek: 1.3.1
GTK: 3.24.2
GLib: 2.58.1
![captura de tela de 2019-02-19 15-42-23](https://user-images.githubusercontent.com/47792595/53039108-1e82c400-345d-11e9-83a9-e669dff5c935.png)

Details:
```como resolver
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
Please refer to the answers on https://github.com/phw/peek/issues/287
