### ISSUE TITLE
Can't change file format or any settings

### ISSUE THREAD

**Issue by avalonv** [phw/peek#423]
I am running peek from flatpak and I can record GIFs without issues, however I cannot change the file format at all and I get this warning:

`(peek:2): dconf-WARNING **: 19:04:27.589: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=6aa24a8a9a38f3a568f2d9e35be7567e --binary-syntax --close-stderr”: Child process exited with code 1
`

I get very similar dconf warnings when trying to change other settings from "Preferences"

Kernel 4.19.26_1 x86_64, Void Linux with i3wm
Peek version 1.3.1

**Comment by phw** [comment]
Is dbus in general working for you? This looks like a general setup issue on your side, please make sure dconf is setup properly. I think you should look for support on this on the Void Linux support channels.

**Comment by avalonv** [comment]
Thanks for responding. 
It seems it was really a dconf issue on my side, on a fresh void install it is working perfectly!
