### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by alecsandermarques** [phw/peek#428]
Peek: 1.3.1
GTK: 3.22.29
GLib: 2.56.0

Details:
```
Missing output file after post processing.
```

**Comment by phw** [comment]
It is impossible to tell what is happening without further details. Are your recording on GNOME or other desktop environment? If on GNOME, please look for error details by GNOME shell in journalctl.

**Comment by alecsandermarques** [comment]
hello, thanks for quick reply. I was using a Gnome Ubuntu, but i just restarted the application and now everything is right

```
jun 24 21:27:17 alecs-Aspire-E5-573 dbus-daemon[2474]: [session uid=1000 pid=2474] Successfully activated service 'com.uploadedlobster.peek'
```
