### ISSUE TITLE
Mouse cursor not recorded in the animated gif

### ISSUE THREAD

**Issue by elgs** [phw/peek#430]
I installed Peek 1.3.1 on Arch Linux (5.0.7-arch1-1-ARCH). The mouse cursor is not shown in the recorded animated gif. Previously the mouse cursor was shown as expected. Thanks.

![peek-bug](https://user-images.githubusercontent.com/55955/56309689-e4513e00-60fe-11e9-9509-dd9e27048cad.gif)

**Comment by RyuzakiKK** [comment]
I'm experiencing the same problem also with green recorder and the built in GNOME screen recorder (ctrl+alt+shift+r).
I've opened an issue against gnome-shell https://gitlab.gnome.org/GNOME/gnome-shell/issues/1208

**Comment by jonata** [comment]
This is an issue with WEBM file too.

**Comment by rugk** [comment]
Same issue, in WEBM and GIF.

**Comment by rugk** [comment]
BTW, interestingly, also the overlay/mouse clicks by `key-mon` ([as recommended here](https://github.com/phw/peek#user-content-how-can-i-capture-mouse-clicks-andor-keystrokes)) were not recorded. Possibly, because of Wayland or so. (see https://github.com/phw/peek/issues/159)

**Comment by carestad** [comment]
Works for me (Ubuntu 19.04) if I set the backend to `ffmpeg`, so I suppose that is a workaround for now

**Comment by rugk** [comment]
Tried so (with flatpak, GNOME, Wayland) and you were not wrong in saying it fixes this issue, but look at it by yourself: :laughing:: 

![black screen only mouse cursor moving](https://user-images.githubusercontent.com/11966684/58974725-5ff86e80-87c3-11e9-8cf9-1a45f99a0d62.gif)

So I have to decide now: Do I want a mouse cursor or a recording of everything behind… :stuck_out_tongue_winking_eye: 

For those wondering, command BTW:
```sh
$ flatpak run com.uploadedlobster.peek -b ffmpeg
```

**Comment by dlbnco** [comment]
>So I have to decide now: Do I want a mouse cursor or a recording of everything behind… stuck_out_tongue_winking_eye

For me the fix actually made it work with both the cursor and everything else.

**Comment by rugk** [comment]
The question then would be: Do you also use it as a flatpak, and with Wayland?

**Comment by carestad** [comment]
Sorry, I did not mention in my comment further up that I am using X11. Have installed peek via .deb installer and not flatpak as well. So that could of course matter. Especially the X11 part :slightly_smiling_face:

**Comment by seanh** [comment]
`flatpak run com.uploadedlobster.peek -b ffmpeg` works for me too, both the image and mouse pointer are correctly recorded. GNOME Shell 3.32.1, Ubuntu 19.04, X Windows not Wayland. It does not work for me with `-b gnome-shell`, records the screen successfully but doesn't capture the mouse pointer.

**Comment by kparal** [comment]
A temporary workaround, until fixed gnome-shell is released, is to go to Gnome Settings -> Universal Access -> Zoom -> Magnifier and enable it with magnification 1.00. You'll get much worse cursor performance (and higher CPU utilization) though.

**Comment by phw** [comment]
This should be fixed with current gnome shell

**Comment by toverux** [comment]
Hello, thank you so much for continuing to maintain this software that helped me so much often (before this bug came to existence).
But, it still seems broken on v.1.4.0 :

![Peek 24-09-2019 13-04](https://user-images.githubusercontent.com/1343250/65506550-1647a700-decc-11e9-8788-5d77bc00649b.gif)

No more crashes though!

```
⚡ gnome-shell --version
GNOME Shell 3.32.2

⚡ peek -v
Peek 1.4.0

⚡ loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
wayland
```

**Comment by phw** [comment]
Please seem my answer at https://github.com/phw/peek/issues/492#issuecomment-534508455

This is basically outside the scope of what Peek can influence. It just instructs Gnome Shell to record the screen with mouse cursor. If it does not capture the mouse cursor this is an issue with Gnome Shell and should be reported there.

**Comment by toverux** [comment]
Okay, cool! The release post mentioned Gnome 3.32 so I thought it was Ok.
I'll just wait or use a GNOME PPA.

**Comment by Daniel-Griffiths** [comment]
The `peek -b ffmpeg` work around did the trick for the meantime :slightly_smiling_face:

**Comment by DannyFeliz** [comment]
> Works for me (Ubuntu 19.04) if I set the backend to `ffmpeg`, so I suppose that is a workaround for now.
> 
> `peek -b ffmpeg`

This should be in the troubleshooting section.

**Comment by lifeeric** [comment]
Thanks, @DannyFeliz! works fine now with `peek -b ffmpeg`

**Comment by stearruda** [comment]
The workaround of `peek -b ffmpeg` still works fine! ;)

**Comment by riolly** [comment]
> In Ubuntu 22.04, go to Settings, Accessibility and enable zoom. It made mouse cursor visible in recordings for me.

After hours of searching, finally.
Thank you so much.

**Comment by rugk** [comment]
New GNOME (and thus Ubuntu etc.) versions also have screenrecord built-in right into the screenshot toool. So actually no need to use Peek anymore.

**Comment by gitressa** [comment]
Thanks for clarifying that @rugk, the built in Gnome screen recording tool via the `PrtScn` key works well. I did have to enable Zoom (just using Magnification 1) for the mouse cursor to show ("Show pointer").
