### ISSUE TITLE
Ubuntu 19.04 / Peek 1.3.1 core dump

### ISSUE THREAD

**Issue by ttatanepvp123** [phw/peek#434]
## INFOS
name|value
-|-
Kernel | 5.0.0-13-generic
Gnome Version | 3.32.1
Peek Version | 1.3.1

### STDOUT

```
Using screen recorder backend gnome-shell
Recording to file /home/ttatane/.cache/peek/peek3A2H0Z.webm
free(): double free detected in tcache 2
Abandon (core dumped)
```
(if you need more info ask)

**Comment by mxa** [comment]
same with recording a gif

**Comment by saberraz** [comment]
I have compiled it from source on Ubuntu 19.04 and have run it with debug option. See attached for the output.
[debug_info.txt](https://github.com/phw/peek/files/3127296/debug_info.txt)

**Comment by bherrmann7** [comment]
ditto 19.04 fresh install peek crashes when saving gif.

**Comment by xsellier** [comment]
Duplicate of https://github.com/phw/peek/issues/419
