### ISSUE TITLE
peek goes in crash by clicking on the save button  on Ubuntu 19.04

### ISSUE THREAD

**Issue by napo** [phw/peek#435]
Peek: 1.3.1
GTK: 3.24.5
GLib: 2.58.2

Details:
```
Missing output file after post processing.
```

**Comment by Cryt1c** [comment]
I have a similar issue with the same Ubuntu and Peek version, where it also crashes on saving.
But it crashes with this error message:

> peek assert failure: double free or corruption (fasttop)

**Comment by ttatanepvp123** [comment]
if you please look if the issue exists before! #434

**Comment by L4ZZA** [comment]
it still crashes on ubuntu 19.04!

1. Start peek 
2. Record as gif (4 seconds in my case)
3. Click save

Bug:
Peek crashes as soon as it opens the file explorer.

Expected:
Being able to save.

**Comment by jhkersul** [comment]
It's really crashing on Ubuntu 19.04, but if you install using the Flatpak version, it works :smile: 

```bash
sudo apt update
sudo apt install flatpak
flatpak install flathub com.uploadedlobster.peek
```

**Comment by bashoholic** [comment]
> It's really crashing on Ubuntu 19.04, but if you install the Flatpak version, it works smile
> 
> ```shell
> sudo apt update
> sudo apt install flatpak
> flatpak install flathub com.uploadedlobster.peek
> ```

Will the program capture the mouse? I'm using the flatpak version to workaround the crash, but the flatpak version won't capture the mouse.

**Comment by ataulien** [comment]
I also get a crash, but peek is writing the .gif into `~/.cache/peek` just fine...

**Comment by phw** [comment]
It is impossible to tell what is happening without further details. Are your recording on GNOME or other desktop environment? If on GNOME, please look for error details by GNOME shell in `journalctl`.

**Comment by code4pay** [comment]
```
Jun 18 10:16:29 michael-Lenovo-Y520 org.gnome.Shell.desktop[3563]: Recording to /home/michaelwork/.cache/peek/peekF95N3Z.webm
Jun 18 10:16:45 michael-Lenovo-Y520 com.uploadedlobster.peek[3351]: Error: Child process exited with code 1
Jun 18 10:16:45 michael-Lenovo-Y520 com.uploadedlobster.peek[3351]: Error deleting temporary file /home/michaelwork/.cache/peek/peekF95N3Z.webm: Command "ffmpeg -y -i /home/michaelwork/.cache/peek/peekF95N3Z.webm -vf fps=10,palettegen /home/michaelwork/.cache/peek/peekH7TN3Z.png" failed with status 256 (received signal 0).
Jun 18 10:16:45 michael-Lenovo-Y520 com.uploadedlobster.peek[3351]: Output:
Jun 18 10:16:45 michael-Lenovo-Y520 com.uploadedlobster.peek[3351]: ffmpeg version N-93825-gc967128952 Copyright (c) 2000-2019 the FFmpeg developers  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04)  configuration: --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64  libavutil      56. 26.101 / 56. 26.101  liba
Jun 18 10:16:45 michael-Lenovo-Y520 com.uploadedlobster.peek[3351]: Recording canceled: Missing output file after post processing.
```

**Comment by beothorn** [comment]
Same problem, gif and webm are recorded on cache but peek crashes before I am able to put the file path.
This is what I see on the output:

➜  ~ peek --version
Peek 1.3.1
➜  ~ peek
Using screen recorder backend gnome-shell
Recording to file /home/beothorn/.cache/peek/peek7JP92Z.webm
free(): double free detected in tcache 2
[1]    1339 abort (core dumped)  peek

Ubuntu 19.04
Release:	19.04
Codename:	disco

**Comment by bobblkabb** [comment]
Same here.
Peek version 1.3.1
ffmpeg version 4.1.3

console output:
```
** (peek:7304): WARNING **: 14:16:48.990: Binding '<Ctrl><Alt>R' failed!
Using screen recorder backend ffmpeg
double free or corruption (fasttop)
fish: 'peek' terminated by signal SIGABRT (abbort)
```

Operating System: openSUSE Tumbleweed 20190628
KDE Plasma Version: 5.16.2
KDE Frameworks Version: 5.59.0
Qt Version: 5.13.0
Kernel Version: 5.1.10-1-default
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-4590 CPU @ 3.30GHz
Memory: 15,5 GiB

**Comment by phw** [comment]
#419
