### ISSUE TITLE
Preferences window not accessible on Gnome 3.22

### ISSUE THREAD

**Issue by kparal** [phw/peek#438]
In GNOME 3.22 the global app menu is still present but seems to be going away:
https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement

I'm not sure whether it's related to this or it's a bug, but ever since I upgraded to GNOME 3.22 (Fedora 30), I can't enter Peek preferences, because the item is no longer available in the global app menu:

![no-menu](https://user-images.githubusercontent.com/755451/57079876-99841880-6cf1-11e9-98b2-0e8d3841694c.png)

I found out that I can disable global app menu in gnome-tweak-tool, and then Peek gets an extra icon that I can use:

![menu](https://user-images.githubusercontent.com/755451/57079929-b3bdf680-6cf1-11e9-922b-e7a9eb900105.png)

But that's inconvenient, because I have to disable app menu for all applications.

Also, with a fresh user profile, I see an extra icon with Peek, same as in the screenshot above, even when I don't disable global app menu in tweak tool. I have no idea what's going on.

Can you please implement an in-application icon to show the preferences window? Thanks a lot.

Reported from Fedora 30 using the latest Peek from Flathub.

**Comment by ktsaou** [comment]
I have the same issue on Manjaro. Without the fallback. There is no way to bring the app menu back on my system.

So, Peek is pretty unusable. Settings cannot be changed...

**Comment by phw** [comment]
Fixed with #391

**Comment by kparal** [comment]
Is there a chance for a new release soon so that this gets fixed for people? Thanks a lot.
