### ISSUE TITLE
Peek AppImage (1.3.1-0 x86_64) crashes on startup - "/tmp/.mount_peek-1mvzDtg/usr/lib/peek/peek-run: symbol lookup error: /lib64/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var"

### ISSUE THREAD

**Issue by furquan-lp** [phw/peek#444]
Error:
 ```
$ ./peek-1.3.1-0-x86_64.AppImage 
/tmp/.mount_peek-1mvzDtg/usr/lib/peek/peek-run: symbol lookup error: /lib64/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
```
Peek version - latest AppImage downloaded from [here](https://github.com/phw/peek/releases/download/1.3.1/peek-1.3.1-0-x86_64.AppImage)
Distribution - Fedora 29 (latest updated)
fontconfig package version - 2.13.1 (`fontconfig-2.13.1-3.fc29.i686`)

`nm` returns:
```
$ nm --dynamic /lib64/libfontconfig.so.1 | grep FT_Done_MM_Var
                 U FT_Done_MM_Var
```
Is this an issue of privileges?

**Comment by phw** [comment]
This is an issue of library incompatibility. Unfortunately dealing with this on AppImage is a major PITA, as it is not fully isolated from system libraries.

If possible I would suggest you install from other sources such as Flatpak or Fedora packages.

I am closing this as I don't have the resources to adpat the AppImage built for different distributions. The AppImage is built on the openSUSE build service, and it relies on what libraries are available there.

**Comment by phw** [comment]
Update: This is also a duplicate, see #392. That issue has a proposal for a solution, so maybe this will get fixed.
