### ISSUE TITLE
peek can not record max window

### ISSUE THREAD

**Issue by fgheng** [phw/peek#447]
Because the top bar of PEEK is too high, if a window is maximized, peek will not be able to cover the window completely.

![image](https://user-images.githubusercontent.com/50551377/59435653-ab90c500-8e20-11e9-89b4-5fa586a039c0.png)

**Comment by phw** [comment]
Yes, the obvious solution is to move the other window a bit down so it is inside the recording frame ;)

Apart from this there is #61 for full screen recording. If feasible this might come, apart from this I have no plans to do changes. Peek is made for recording small parts of your screen. For a proper recording you might need to stage the scene before recording.
