### ISSUE TITLE
Crashes when countdown reaches 0 in Ubuntu 19.04

### ISSUE THREAD

**Issue by maidenone** [phw/peek#451]
Peek: 1.3.1
GTK: 3.24.5
GLib: 2.58.2

Details:
```
GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code19: Invalid params
```

**Comment by JonnySpruce** [comment]
@maidenone as a workaround, I've found that if you run it from a terminal with ffmpeg as the backend it can run and record successfully:
```bash
peek --backend=ffmpeg
```

**Comment by phw** [comment]
What version of GNOME is this?

**Comment by phw** [comment]
#536 reports this for PopOS!. I'm closing this under the assumption that this is a duplicate and that PopOS! probably has a different screen recording interface. Please let me know if this is not true and you encountered the issue on GNOME.

**Comment by JonnySpruce** [comment]
@phw I'm experiencing this on Ubuntu 19.04, GNOME version `3.34.2`

**Comment by hosiet** [comment]
I need to remind Ubuntu 19.04 users that Ubuntu 19.04 is now End-Of-Life (since Jan 2020) and is no longer supported by Ubuntu upstream. Please upgrade your system to a new version and see if there's any improvement.

**Comment by JonnySpruce** [comment]
@hosiet - apologies, I'm on 19.10
