### ISSUE TITLE
Peek not working for record gif in ubuntu

### ISSUE THREAD

**Issue by techragesh** [phw/peek#454]
Peek: 1.3.1
GTK: 3.22.29
GLib: 2.56.0

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by jonbam** [comment]
Rebooting seems to fix this.

Peek: 1.3.1
GTK: 3.22.30
GLib: 2.27

**Comment by phw** [comment]
Please see the [FAQs](https://github.com/phw/peek#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors) and https://github.com/phw/peek/issues/267
