### ISSUE TITLE
Error in open Peek in my ubuntu 18 lts

### ISSUE THREAD

**Issue by catalunha** [phw/peek#458]
Peek: 1.3.1
GTK: 3.22.29
GLib: 2.56.0

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by passcod** [comment]
Also seen in:

Peek: 1.3.1
GTK: 3.22.30
GLib: 2.56.2
(Arch Linux)

Journal additionally reports gnome-shell says:

```
ShellRecorder: failed to parse pipeline: no element "x264enc"
shell_recorder_close: assertion 'recorder->state != RECORDER_STATE_CLOSED' failed
```

**Comment by slavik-chapelskyi** [comment]
Same for me.

**Comment by passcod** [comment]
This is most likely #287, btw. Thought I had the same issue, turned out I needed the ugly gst plugins. Oops.
