### ISSUE TITLE
Peek ignores GTK_THEME environtment variable to force Peek using light theme

### ISSUE THREAD

**Issue by jEsuSdA** [phw/peek#460]
Hi!

I'm trying to lauch peek with "lightk" version of my GTK theme, but it not possible.

Peek always use the "dark" version and peek ignores the GTK_THEME environment value.

Trying to do:

`GTK_THEME=Adwaita:light peek`

does not works.

Any ideas? 
Thanks a lot!

**Comment by phw** [comment]
There is a hidden configuration for this:

```
gsettings set com.uploadedlobster.peek interface-prefer-dark-theme false
```
