### ISSUE TITLE
Crashes when recording stopped in Ubuntu 19.04

### ISSUE THREAD

**Issue by mattwelke** [phw/peek#461]
I've been getting an error when I try to use Peek lately. It started happening a few months ago I think. Before that, I had been able to use it without any issues.

I can start recording and then stop recording, at which point the "Save As" dialog appears but the dialog isn't responsive. A few seconds later, it crashes, and I get the Ubuntu "The application Peek has closed unexpectedly." dialog:

![image](https://user-images.githubusercontent.com/7719209/60620423-2a867700-9da9-11e9-960d-6fc1342916fe.png)

The Stacktrace portion:

![image](https://user-images.githubusercontent.com/7719209/60620441-38d49300-9da9-11e9-878c-b2c5c615473f.png)

(Apologies, I couldn't figure out how to copy and paste this info into a gist. Screenshot was all I could think of to show these details)

From the command line, it just displays:

```
Using screen recorder backend gnome-shell
Recording to file /home/matt/.cache/peek/peekECI03Z.webm
free(): double free detected in tcache 2
Aborted (core dumped)
```

Kernel version: 5.0.0-20-generic

Let me know if there's more data that be helpful.

**Comment by hkyq** [comment]
Same here, Pop OS Gnome based on Ubuntu 19.04. Crashes on save with 
```
free(): double free detected in tcache 2
Aborted (core dumped)
```

**Comment by tassoevan** [comment]
@hkyq It worked, thanks!

**Comment by krisleech** [comment]
Not sure if related but I also find peek to crash (it used to work) after the save dialog.

Recording to file /home/kris/.cache/peek/peekRWLU5Z.webm
double free or corruption (fasttop)
[1]    4692 abort (core dumped)  peek

This is on Ubuntu 19.04
Peek 1.3.1

The Ubuntu PPA does not have the latest 1.4 release.

However the files (gif, webm) are recorded and do exist in ~/.cache/peek.

**Comment by phw** [comment]
Duplicate of #419
