### ISSUE TITLE
Is flathub version unmaintained?

### ISSUE THREAD

**Issue by vlad20012** [phw/peek#463]
Looks like the [official version](https://flathub.org/apps/details/com.uploadedlobster.peek) was not updated more than a year and doesn't include critical fixes like #449

**Comment by kparal** [comment]
That's probably because the latest official version (1.3.1) is more than a year old:
https://github.com/phw/peek/releases

**Comment by vlad20012** [comment]
Hmm, maybe it's time to release a new version because 1.3.1 just doesn't work =/ (#449)

**Comment by luzpaz** [comment]
Here are the contributors to flathub, i think:  
https://github.com/flathub/com.uploadedlobster.peek/graphs/contributors/

**Comment by phw** [comment]
No, but there hasn't been a release. New release is out and flathub version will get updated.
