### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sharmarajat01** [phw/peek#464]
Even i am running it only once, still shows the following error !

Peek: 1.3.1
GTK: 3.22.29
GLib: 2.56.0

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by jonbam** [comment]
Looks like this issue #454

**Comment by phw** [comment]
Please see the [FAQs](https://github.com/phw/peek#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors) and https://github.com/phw/peek/issues/267
