### ISSUE TITLE
Could not start recording, single screen gnome 3.32.1

### ISSUE THREAD

**Issue by laverdone** [phw/peek#468]
Peek: 1.3.1
GTK: 3.24.2
GLib: 2.58.1

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by fatso83** [comment]
Duplicate. Remember to restart `gnome-shell` after installing the gstreamer-ugly plugins. Ref https://github.com/phw/peek/issues/267#issuecomment-488697956
