### ISSUE TITLE
unable to record MP4

### ISSUE THREAD

**Issue by zhn3** [phw/peek#469]
Peek: 1.3.1
GTK: 3.22.29
GLib: 2.56.0

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by aadilayub** [comment]
I'm also experiencing this issue.

**Comment by fatso83** [comment]
Duplicate. Remember to restart `gnome-shell` after installing the gstreamer-ugly plugins. Ref https://github.com/phw/peek/issues/267#issuecomment-488697956
