### ISSUE TITLE
Peek not able to record

### ISSUE THREAD

**Issue by road2guru** [phw/peek#470]
Peek: 1.3.1
GTK: 3.24.2
GLib: 2.58.1

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by mariana-fantini-movile** [comment]
I got the same error. It happened just after I installed Peek, on my first attempt to record a gif 
Peek: 1.3.1
GTK: 3.22.29
GLib: 2.56.0

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
Please see the [FAQs](https://github.com/phw/peek#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors) and https://github.com/phw/peek/issues/267
