### ISSUE TITLE
recording error appeared.I couldn't record an mp4 vedio and the peek window is always pinned up other opened windows. So i can't move between my windows.

### ISSUE THREAD

**Issue by nelshamy** [phw/peek#472]
Peek: 1.3.1
GTK: 3.24.2
GLib: 2.58.1

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
Please see the [FAQs](https://github.com/phw/peek#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors) and https://github.com/phw/peek/issues/267
