### ISSUE TITLE
Issue with recording 

### ISSUE THREAD

**Issue by PizzaPablo666** [phw/peek#480]
Peek: 1.3.1
GTK: 3.24.8
GLib: 2.60.3

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
Please see the [FAQs](https://github.com/phw/peek#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors) and https://github.com/phw/peek/issues/267
