### ISSUE TITLE
Pop-up with error/alert information

### ISSUE THREAD

**Issue by guillecro** [phw/peek#49]
So my area of recording was outside the screen size.
After opening peek on the terminal I saw what was the error. But it would be nice to have maybe a pop-up giving me the same message without using the terminal 

```
[x11grab @ 0x562632890c60] Capture area 503x691 at position 869.71 outside the screen size 1366x768
:0+869,71: Invalid argument
```

**Comment by phw** [comment]
I am not a huge fan of error popups, but this surely needs some better handling, yes.

**Comment by phw** [comment]
I added a dialog for showing error details. But not 100% finished, the displayed errors are rather basic for now. I keep this open as I want to show actual error output in case of commands called.
