### ISSUE TITLE
Lock window resizing to even numbered pixels

### ISSUE THREAD

**Issue by snwh** [phw/peek#491]
If Peek records an area of the screen that happens to be an odd number of pixels in height or width, e.g. 601x433, that causes errors with some video formats or transcoding (like MP4) if you wanted to edit or make use of the screen recording in some other format. 

Is there a reason to not lock the capture area to even numbered pixels?

**Comment by phw** [comment]
Peek already takes care of using only even numbers for MP4 videos. I am not sure we should do this for all formats, it is not really necessary there and when transcoding this can usually be dealt with as well.

**Comment by phw** [comment]
I am closing this as a won't fix. Peek already records only even sizes for e.g. MP4, so there is not technical issue with the created files.
