### ISSUE TITLE
Fedora 30: Peek does not capture the mouse cursor

### ISSUE THREAD

**Issue by rvsia** [phw/peek#492]
On my Fedora 30 Peek **does not capture the mouse cursor** 

Mode: GIF

Settings: 
![Screenshot from 2019-09-13 12-24-19](https://user-images.githubusercontent.com/32869456/64856055-73687080-d621-11e9-8ce5-2189e1ce1798.png)

Package INFO:
```sh
Installed Packages
Name         : peek
Version      : 1.3.1
Release      : 6.20190616gitaeb190d.fc30
Architecture : x86_64
Size         : 890 k
Source       : peek-1.3.1-6.20190616gitaeb190d.fc30.src.rpm
Repository   : @System
From repo    : updates
```

System 
```sh
Operating System: Fedora 30 (Workstation Edition)
    CPE OS Name: cpe:/o:fedoraproject:fedora:30
                  Kernel: Linux 5.2.13-200.fc30.x86_64
```

Do you need any additional info?

**Comment by phw** [comment]
@rvsia Let me guess, this is on Wayland? This turned out to work on wayland a while back, not sure why. But likely a Gnome Shell issue, but I haven't looked into it yet.

**Comment by rvsia** [comment]
@phw You guess right

**Comment by painejake** [comment]
I can also confirm this happening under F30 with nvidia non-free drivers using Xorg

```  Operating System: Fedora 30 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:30
            Kernel: Linux 5.2.14-200.fc30.x86_64
      Architecture: x86-64```

```[    22.766] (II) NVIDIA dlloader X Driver  435.21  Sun Aug 25 08:17:08 CDT 2019```

Let me know if any additional info is required also

**Comment by phw** [comment]
#430 suggests this is a gnome shell issue. If there is no fix for Fedora a workaround might be to use the ffmpeg backend (start peek with `peek -b ffmpeg`).

**Comment by rvsia** [comment]
@phw It fixed the missing cursor.. however, anything else is gone. :smiley_cat: 

![mousetest](https://user-images.githubusercontent.com/32869456/65505358-4d688900-dec9-11e9-93d4-f39ca31ed64f.gif)

**Comment by rvsia** [comment]
Outer peek

![inner](https://user-images.githubusercontent.com/32869456/65505717-265e8700-deca-11e9-977d-4f3a25cf4f1a.gif)

Inner peek -b ffmpeg

![outer](https://user-images.githubusercontent.com/32869456/65505724-2a8aa480-deca-11e9-9194-2430e045da46.gif)

**Comment by phw** [comment]
Blank recording area with ffmpeg could either be the cause of running on Wayland or this is probably a driver issue then. Any chance this is inside a VM? I have seen VM setups where screen recording with ffmpeg was basically not possible. 

Anyway, if ffmpeg is not able to properly record your screen this is outside of what Peek can influence. And missing cursor in gnome-shell recording is an issue with gnome-shell and should be reported there. But AFAIK this has already been fixed upstream.

**Comment by rvsia** [comment]
No VM.

Okay, I will wait for updates of gnome. Thank you!

**Comment by rvsia** [comment]
@phw Otherwise, I would like to thank you for this application. Peek is really awesome and I am using it everyday to show what I do as frontend developer, it makes it so simple!  :trophy:
