### ISSUE TITLE
Ubuntu 18.04 LTS PPA server issue: "Error: retrieving gpg key timed out."

### ISSUE THREAD

**Issue by tommai78101** [phw/peek#494]
Was attempting to add the PPA to Ubuntu 18.04 LTS:

`$ sudo add-apt-repository ppa:peek-developers/stable`

When it reported that retrieving the gpg key is taking too long.

I have already did `$ sudo apt-get update` first.

**Comment by phw** [comment]
Works for me, please try again. This could have been a network issue or some issue with Ubuntu's server.

Nonetheless, I don't have control over the PPA hosting. It is working in general, but if you continue to have issues you should best contact Ubuntu.

**Comment by tommai78101** [comment]
Ah, it didn't cross my mind that my company network blocks PPA servers. Thanks for confirming that it works on your end.
