### ISSUE TITLE
Peek Fails to record for MP4 on Fedora 30 after a dnf update.

### ISSUE THREAD

**Issue by supcom234** [phw/peek#497]
Peek: 1.3.1
GTK: 3.24.8
GLib: 2.60.3

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
Please see the [FAQs](https://github.com/phw/peek#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors) and https://github.com/phw/peek/issues/267
