### ISSUE TITLE
Show this bug when saving in any format.

### ISSUE THREAD

**Issue by ricardosantosdev** [phw/peek#498]
Peek: 1.3.1
GTK: 3.22.29
GLib: 2.56.0

Details:
```
Missing output file after post processing.
```

**Comment by phw** [comment]
This does not give enough details to see what the issue is. Can you run peek with debug output and post the result here:

```
G_MESSAGES_DEBUG=all peek
```

Also please have a look at the output of journalctl if there is some issue reported there.

**Comment by ricardosantosdev** [comment]
I uninstalled the build snap and installed it by apt and the bug is gone.
