### ISSUE TITLE
GIF recording as webm

### ISSUE THREAD

**Issue by Jared-Sprague** [phw/peek#499]
Hello!

I just built the latest code from source on Sep 21st 2019 using Fedora 30 Kernel 5.2.15-200.  Everything looks like it works fine while recording a GIF and rendering.  But when I try to open the `.gif` it rendered I get this error message:

![Screenshot from 2019-09-21 10-47-02](https://user-images.githubusercontent.com/3926730/65374919-2ad23800-dc5d-11e9-9bb3-fb43d03c12d6.png)

Interesting.  So looking at the console output I see this:

`Recording to file /home/jaredsprague/.cache/peek/peekTLHU8Z.webm`

So I try renaming the `.gif` file to `.webm` and presto it opens fine as a webm!

Conclusion:  Even through Peek says it's recording and rendering as GIF it's really outputing a `.webm`

![bug](https://user-images.githubusercontent.com/3926730/65374965-87355780-dc5d-11e9-9e6d-3b37848ce86e.png)

**Comment by phw** [comment]
That's pretty strange. The `Recording to file /home/jaredsprague/.cache/peek/peekTLHU8Z.webm` is correct, because it will record to webm as intermediary format. But that means something goes wrong when ffmpeg gets called to convert to a GIF. That's probably Fedora again with a FFmpeg that is missing something. I just wonder why it does not flat out fail.

Can you run peek with:

```
G_MESSAGES_DEBUG=all peek
```

**Comment by Jared-Sprague** [comment]
Here is the full Debug output of doing a quick gif recording then saving it.  From looking at the output I think the issue may be that I'm missing ffmpeg.  ffmpeg is not included in the default Fedora repos.  So if it is a dependancy for peek to work,  then maybe a warning message if it's not found should be added

---
[jaredsprague@localhost src]$ 
[jaredsprague@localhost src]$ 
[jaredsprague@localhost src]$ G_MESSAGES_DEBUG=all ./peek
(peek:4316): GLib-GIO-DEBUG: 18:03:49.737: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(peek:4316): Gtk-DEBUG: 18:03:49.758: Connecting to session manager
** (peek:4316): DEBUG: 18:03:49.759: desktop-integration.vala:168: Desktop: GNOME
(peek:4316): GLib-GIO-DEBUG: 18:03:49.759: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(peek:4316): dconf-DEBUG: 18:03:49.759: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(peek:4316): dconf-DEBUG: 18:03:49.759: unwatch_fast: "/org/gnome/desktop/interface/" (active: 0, establishing: 1)
** (peek:4316): DEBUG: 18:03:49.760: application.vala:282: GTK theme: Adwaita
** (peek:4316): DEBUG: 18:03:49.760: desktop-integration.vala:168: Desktop: GNOME
(peek:4316): dconf-DEBUG: 18:03:49.760: watch_fast: "/com/uploadedlobster/peek/" (establishing: 0, active: 0)
** (peek:4316): DEBUG: 18:03:49.760: application.vala:217: Changed keybinding_toggle_recording  => <Ctrl><Alt>R

(peek:4316): dconf-DEBUG: 18:03:49.760: watch_established: "/org/gnome/desktop/interface/" (establishing: 0)
(peek:4316): dconf-DEBUG: 18:03:49.761: watch_established: "/com/uploadedlobster/peek/" (establishing: 1)
** (peek:4316): DEBUG: 18:03:49.761: desktop-integration.vala:168: Desktop: GNOME
Using screen recorder backend gnome-shell
** (peek:4316): DEBUG: 18:03:49.802: application-window.vala:882: Decoration layout: menu:close
** (peek:4316): DEBUG: 18:03:49.812: recording-area.vala:38: Absolute recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:49.812: recording-area.vala:45: Screen w: 2560, h: 1080
** (peek:4316): DEBUG: 18:03:49.812: recording-area.vala:58: Clipped recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:49.812: recording-area.vala:69: Scaled recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:49.828: recording-area.vala:38: Absolute recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:49.828: recording-area.vala:45: Screen w: 2560, h: 1080
** (peek:4316): DEBUG: 18:03:49.828: recording-area.vala:58: Clipped recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:49.828: recording-area.vala:69: Scaled recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:56.385: desktop-integration.vala:168: Desktop: GNOME
** (peek:4316): DEBUG: 18:03:56.386: application-window.vala:639: freeze_window_size w: 944, h: 733
** (peek:4316): DEBUG: 18:03:56.393: recording-area.vala:38: Absolute recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:56.393: recording-area.vala:45: Screen w: 2560, h: 1080
** (peek:4316): DEBUG: 18:03:56.394: recording-area.vala:58: Clipped recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:56.394: recording-area.vala:69: Scaled recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:57.933: recording-area.vala:38: Absolute recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:57.933: recording-area.vala:45: Screen w: 2560, h: 1080
** (peek:4316): DEBUG: 18:03:57.933: recording-area.vala:58: Clipped recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:57.933: recording-area.vala:69: Scaled recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:58.934: recording-area.vala:38: Absolute recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:58.934: recording-area.vala:45: Screen w: 2560, h: 1080
** (peek:4316): DEBUG: 18:03:58.934: recording-area.vala:58: Clipped recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:58.934: recording-area.vala:69: Scaled recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:59.934: recording-area.vala:38: Absolute recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:59.934: recording-area.vala:45: Screen w: 2560, h: 1080
** (peek:4316): DEBUG: 18:03:59.934: recording-area.vala:58: Clipped recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:59.934: recording-area.vala:69: Scaled recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:59.934: application-window.vala:533: Recording area: 741, 100, 890, 632

** (peek:4316): DEBUG: 18:03:59.934: gnome-shell-dbus-recorder.vala:169: Using GStreamer pipeline vp9enc min_quantizer=0 max_quantizer=0 cq_level=0 cpu-used=5 deadline=1000000 threads=%T ! queue ! webmmux
** (peek:4316): DEBUG: 18:03:59.934: utils.vala:23: Cache directory does already exist /home/jaredsprague/.cache/peek

** (peek:4316): DEBUG: 18:03:59.934: utils.vala:38: Temp file: /home/jaredsprague/.cache/peek/peekVE9F8Z.webm

Recording to file /home/jaredsprague/.cache/peek/peekVE9F8Z.webm
** (peek:4316): DEBUG: 18:03:59.952: recording-area.vala:38: Absolute recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:59.952: recording-area.vala:45: Screen w: 2560, h: 1080
** (peek:4316): DEBUG: 18:03:59.952: recording-area.vala:58: Clipped recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:03:59.952: recording-area.vala:69: Scaled recording area x: 741, y: 100, w: 890, h: 632
** (peek:4316): DEBUG: 18:04:05.038: base-screen-recorder.vala:55: Recording stopped
** (peek:4316): DEBUG: 18:04:05.443: base-screen-recorder.vala:67: Started post processing
(peek:4316): GLib-DEBUG: 18:04:05.443: posix_spawn avoided (fd close requested) 
** (peek:4316): DEBUG: 18:04:05.444: utils.vala:68: Looking for executable ffmpeg (256): which: no ffmpeg in (/home/jaredsprague/.local/bin:/home/jaredsprague/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin)

Error: Child process exited with code 1
(peek:4316): dconf-DEBUG: 18:04:05.493: watch_fast: "/org/gtk/settings/file-chooser/" (establishing: 0, active: 0)
(peek:4316): dconf-DEBUG: 18:04:05.493: watch_established: "/org/gtk/settings/file-chooser/" (establishing: 1)
** (peek:4316): DEBUG: 18:04:05.495: application-window.vala:695: Showing file chooser (GtkFileChooserDialog)
** (peek:4316): DEBUG: 18:04:05.511: base-screen-recorder.vala:70: Finished post processing
** (peek:4316): DEBUG: 18:04:08.495: application-window.vala:697: Selected file file:///home/jaredsprague/Videos/Peek%202019-09-25%2018-04.gif
(peek:4316): dconf-DEBUG: 18:04:08.496: change_fast
(peek:4316): dconf-DEBUG: 18:04:08.496: change_notify: /org/gtk/settings/file-chooser/
** (peek:4316): DEBUG: 18:04:08.511: application-window.vala:724: File saved true: file:///home/jaredsprague/Videos/Peek%202019-09-25%2018-04.gif
** (peek:4316): DEBUG: 18:04:08.511: desktop-integration.vala:39: File URI: file:///home/jaredsprague/Videos/Peek%202019-09-25%2018-04.gif

** (peek:4316): DEBUG: 18:04:08.512: desktop-integration.vala:44: Launching org.freedesktop.FileManager1 for URI: file:///home/jaredsprague/Videos/Peek%202019-09-25%2018-04.gif

** (peek:4316): DEBUG: 18:04:08.512: desktop-integration.vala:168: Desktop: GNOME
** (peek:4316): DEBUG: 18:04:08.512: application-window.vala:653: unfreeze_window_size w: 944, h: 733
** (peek:4316): DEBUG: 18:04:08.513: application-window.vala:582: Deleting temp file file:///home/jaredsprague/.cache/peek/peekVE9F8Z.webm

** (peek:4316): DEBUG: 18:04:08.517: application-window.vala:586: Temp file deleted: true

** (peek:4316): DEBUG: 18:04:23.644: application-window.vala:217: delete_event: recorder.is_recording=false, window.is_postprocessing=false
(peek:4316): dconf-DEBUG: 18:04:23.644: change_fast
(peek:4316): dconf-DEBUG: 18:04:23.644: change_notify: /com/uploadedlobster/peek/persist-window-geometry
** (peek:4316): DEBUG: 18:04:23.646: application.vala:112: Application got shutdown signal
(peek:4316): dconf-DEBUG: 18:04:23.652: sync
[jaredsprague@localhost src]$ 
[jaredsprague@localhost src]$ 
[jaredsprague@localhost src]$ 
---

**Comment by phw** [comment]
Yes, ffmpeg is a dependency. You are right, a warning makes sense here.

In the majority of cases this is not a real issues since most users install Peek via package management, which takes care of this.
