### ISSUE TITLE
Remembering window position and size broken in Gnome and/or GTK 3.20

### ISSUE THREAD

**Issue by phw** [phw/peek#5]
On Gnome 3.20 Peek always starts up in the upper left corner. Also the window size is not correctly restored, it is always a bit larger than what was saved (in my tests always 30 pixels wider and 70 pixels higher).

I am not yet sure whether those changes are caused by Gtk 3.20 itself or by the also updated window manager.

**Comment by phw** [comment]
Likely related to the issue reported at https://bbs.archlinux.org/viewtopic.php?id=211166 (see also the linked upstream bug).

That should at least fix the window position. As for the size i will switch to a mechanism that persists the recording window size / position instead of the main window. This way we will get consistent sizes even when somebody e.g. switches themes (with different border widths etc.).

**Comment by cedlemo** [comment]
For saving the window size : 
>  gtk_window_set_default_size() must now be combined with gtk_window_get_size(). See https://wiki.gnome.org/HowDoI/SaveWindowState for up-to-date best-practice for saving window size

from https://wiki.gnome.org/ThreePointNineteen/ReleaseNotes in the What's new for developpers > Gtk + part .

 Regards
