### ISSUE TITLE
Animation not recording in Kali Linux

### ISSUE THREAD

**Issue by GeneralBison** [phw/peek#51]
Peek doesn't seem to be working correctly in Kali Linux (as root), the gif that is output does not seem to be animating.
![peek 2016-11-22 17-27](https://cloud.githubusercontent.com/assets/2755919/20599135/7a14b9ce-b244-11e6-970c-2351ead0e354.gif)

This may be related to the hardened nature of Kali. Anyone had experience using it?

**Comment by phw** [comment]
Sorry, I have no experience with Kali. What desktop environment and window manager is used here?

Why are you running it as root? Is the whole WM running as root? Does running it as a normal user make any difference?

**Comment by phw** [comment]
Closing this as there is not enough information to pin this down. Feel free to re-open with additional details.
