### ISSUE TITLE
Crashes when I press Stop button

### ISSUE THREAD

**Issue by ilius** [phw/peek#524]
As soon as I press Stop button, it shows "Rendering..." and then the program exits, showing this message in terminal:

    (peek:16086): GLib-GIO-ERROR **: 07:47:05.458: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap

I compiled the latest master (54861e925a2c00efca5a7cb1cc89d4d81a88f499) with meson.
Same problem with version 1.4.0 from ppa.

I'm using Debian sid.
Version of package `libgtk-3-dev`: `3.24.12-1`
Version of `valac`: `0.46.3`

`.webm` files are created in `~/.cache/peek/`, and seem to be okay.
But I want `.gif` files

**Comment by gort818** [comment]
Can you post the output of this 

`gsettings list-keys org.gtk.Settings.FileChooser`

**Comment by ilius** [comment]
```
last-folder-uri
show-size-column
show-hidden
date-format
window-size
sidebar-width
clock-format
window-position
sort-column
expand-folders
location-mode
sort-directories-first
startup-mode
sort-order
```

**Comment by gort818** [comment]
This is not a peek bug.. looks like a gtk schema issue.

check this thread and see if it helps you.

https://askubuntu.com/questions/820733/firefox-hangs-because-sort-directories-first-setting-missing

**Comment by ilius** [comment]
Thanks, it was solved by resetting `$XDG_DATA_DIRS`

Although there is another error:
```(peek:27391): GLib-GIO-WARNING **: 18:52:38.291: unable to send notifications through org.freedesktop.Notifications: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```
It doesn't cause a problem for now for me.

**Comment by gort818** [comment]
Yeah no problem, you seem to be missing the systemd service file.

https://wiki.archlinux.org/index.php/Desktop_notifications#Standalone
