### ISSUE TITLE
Unrecognized option 'lossless'.Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by anastasiadubrovina** [phw/peek#533]
Peek: 1.3.1
GTK: 3.18.9
GLib: 2.48.2

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 566x589 -i :0+409,256 -filter:v scale=iw/1:-1 -codec:v libvpx-vp9 -lossless 1 -r 10 -y /home/lyft/.cache/peek/peekOT17B0.webm" failed with status 256 (received signal 0).

Output:
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1)  configuration: --prefix=/home/edwards/Downloads/FFmpeg-release-4.1/build --enable-pic --enable-shared --enable-cuda --enable-hardcoded-tables --extra-cflags=' -march=native '  libavutil      56. 22.100 / 56. 22.100  libavcodec     58. 35.100 / 58. 35.100  libavformat    58. 20.100 / 58. 20.100  libavdevice    58.  5.100 / 58.  5.100  libavfilter     7. 40.101 /  7. 40.101  libswscale      5.  3.100 /  5.  3.100  libswresample   3.  3.100 /  3.  3.100Unrecognized option 'lossless'.Error splitting the argument list: Option not found
```

**Comment by gort818** [comment]
You need ffmpeg built with xcb. build ffmpeg with ``--enable-libxcb``.

What OS are you using?

**Comment by anastasiadubrovina** [comment]
Ubuntu 16.04. I saw other tickets that state that I need ffmpeg built with xcb. However, building ffmpeg from scratch seems to be not straightforward. I've used apt-get to install it. Do you have a pre-built version with the right ffmpeg included?

**Comment by gort818** [comment]
I believe the author is no longer supporting 16.04.
You can try this guide https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
Here you can find some prebuilt static binaries https://johnvansickle.com/ffmpeg/

**Comment by phw** [comment]
I'm sorry, but I can't provide support for 16.04. it should work with the ffmpeg from later Ubuntu versions.

**Comment by xekon** [comment]
I am on ubuntu 20.04 and I installed: `sudo apt install ffmpeg`
I am getting this error of unrecognized option lossless.

**Comment by yunginnanet** [comment]
`ffmpeg version N-107285-g804bf898da Copyright (c) 2000-2022 the FFmpeg developers  built with gcc 11 (Debian 11.3.0-4)  configuration: --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --enable-libxcb  libavutil      57. 27.100 / 57. 27.100  libavcodec     59. 35.100 / 59. 35.100  libavformat    59. 25.100 / 59. 25.100  libavdevice    59.  6.100 / 59.  6.100  libavfilter     8. 41.100 /  8. 41.100  libswscale      6.  6.100 /  6.  6.100  libswresample   4.  6.100 /  4.  6.100Unrecognized option 'lossless'.Error splitting the argument list: Option not found`

Note that within the error message is `--enable-libxcb` which I explicitly just recompiled ffmpeg for to try and attack this exact issue.

**Comment by jxqhhh** [comment]
> `ffmpeg version N-107285-g804bf898da Copyright (c) 2000-2022 the FFmpeg developers built with gcc 11 (Debian 11.3.0-4) configuration: --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --enable-libxcb libavutil 57. 27.100 / 57. 27.100 libavcodec 59. 35.100 / 59. 35.100 libavformat 59. 25.100 / 59. 25.100 libavdevice 59. 6.100 / 59. 6.100 libavfilter 8. 41.100 / 8. 41.100 libswscale 6. 6.100 / 6. 6.100 libswresample 4. 6.100 / 4. 6.100Unrecognized option 'lossless'.Error splitting the argument list: Option not found`
> 
> Note that within the error message is `--enable-libxcb` which I explicitly just recompiled ffmpeg for to try and attack this exact issue.

I have encountered the same problem. The cause of such problem is that I forgot to  use "--enable-libvpx" while executing "configure".
