### ISSUE TITLE
Mp4 recording not functional

### ISSUE THREAD

**Issue by levenhagen** [phw/peek#534]
Peek: 1.4.0
GTK: 3.24.11
GLib: 2.62.0
Desktop: GNOME
Display server: X
FFmpeg version:
```
Failed to execute child process “ffmpeg” (No such file or directory)
```

Output format: mp4
gifski enabled: false

Error details:
```
Could not start GNOME Shell recorder.

Make sure you have the GStreamer ugly plugins installed for MP4 recording.

Please see the FAQ at https://github.com/phw/peek#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors
```

**Comment by gort818** [comment]
> Failed to execute child process “ffmpeg”

do you have ffmpeg installed?
do you have GStreamer ugly plugins installed?

**Comment by phw** [comment]
No response, closing as I assume the issue is solved by.installing the required dependencies
