### ISSUE TITLE
Crashing when using "Use gifski for high quality GIFs" option

### ISSUE THREAD

**Issue by LarnuUK** [phw/peek#538]
When the option "Use gifski for high quality GIFs" is enabled, Peek crashes when rendering. The GIF appears to have been recorded successfully, and for longer recording, the time to error does *appear* to take little longer. 

When launching peek from the terminal, and recording, the below output is provided:
```
:~$ peek
Using screen recorder backend ffmpeg
free(): double free detected in tcache 2
Aborted (core dumped)
```

**Comment by phw** [comment]
This had been fixed in Peek 1.4.0, see #419
