### ISSUE TITLE
not working in Ubuntu Gnome 14.04.5

### ISSUE THREAD

**Issue by csrgxtu** [phw/peek#54]
peek not working in Ubuntu Gnome 14.04.5, due to the gtk problem, but if i upgrade gtk, means i update the desktop enviroment, that is a little risky.

**Comment by phw** [comment]
My first reaction on this was that I won't fix it, since I have no interest in doing workarounds for an old version that is hard to test for me. But the commit that raised the required version was https://github.com/phw/peek/commit/5ca016bb7185ebc438103de4753a38969e52d464 , and the reason stated here would be easy to work around. Not really a blocker.

I will see if this really is the only place I used a Gtk 3.14 function. If it is I will try to get back to 3.10 as a minimum. If I provide you a test build, could you try it?

**Comment by csrgxtu** [comment]
yep, i will try it if you can build one. just paste the link here.

**Comment by phw** [comment]
@csrgxtu Took me longer to find the time due to the year suddenly ending and everybody being surprised by it :)

But here we go, a special build just for you: https://drive.google.com/open?id=0B4YQhIuWC-gcRDc5Q09ySmthVW8

Can you try whether this works for you?

**Comment by csrgxtu** [comment]
i am using ubuntu 14.04, and peek depends on libgtk-3-0, my current window environment is lower than that.
```bash

archer@ThinkPad:~/Downloads$ sudo dpkg -i peek-0.8.0-issue-54-Linux.deb 
Selecting previously unselected package peek.
(Reading database ... 207303 files and directories currently installed.)
Preparing to unpack peek-0.8.0-issue-54-Linux.deb ...
Unpacking peek (0.8.0) ...
dpkg: dependency problems prevent configuration of peek:
 peek depends on libgtk-3-0 (>= 3.14); however:
  Version of libgtk-3-0:amd64 on system is 3.10.8-0ubuntu1.6.

dpkg: error processing package peek (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for libglib2.0-0:amd64 (2.40.2-0ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Errors were encountered while processing:
 peek


```

**Comment by phw** [comment]
Ok, I gave that a try, but it turns out to require more changes than I am comfortable with. Trusty is out of luck sorry.

**Comment by phw** [comment]
People who want to use this on Ubuntu 14.04 "Trusty" could try using the development Snap package. I haven't tried this and don't know whether this is fully supported on Trusty, but give it a try:

First install Snap with (requires trusty-updates repository to be enabled):

    sudo apt-get install snapd

Then install Peek snap:

    sudo snap install peek --edge --devmode

**Comment by tylercollier** [comment]
Peek is awesome and I'm so happy it works on Ubuntu 14.04.5.

The only tricky part for me, since this was my first time using a snap package, was that the executable was not found. [This article](https://insights.ubuntu.com/2017/03/30/snaps-are-now-available-for-ubuntu-14-04-lts-desktop-and-server/) helped:

> However, the first time you try to run a snap on 14.04, you might experience the error “The command cannot be found”. This is due to the fact that “/snap/bin” has not been added to the $PATH environment variable. To do so, a script called “apps-bin-path.sh” has been added to /etc/profile.d. It will automatically run after you reboot or re-login and add snaps launchers to your path. When this is done, snaps should launch as expected

So, running `$ /snap/bin/peek` worked for me.

**Comment by Tusharsb** [comment]
@phw when I try
```
sudo snap install peek --edge --devmode
``` 
I get this warning
```
error: This revision of snap "peek" was published using classic confinement and
       thus may perform arbitrary system changes outside of the security
       sandbox that snaps are usually confined to, which may put your system at
       risk.

       If you understand and want to proceed repeat the command including
       --classic.
```
Hesitatingly when I try
```
sudo snap install peek --edge --devmode --classic
``` 
snap tells me
```
error: cannot install "peek": cannot use classic and devmode flags together
```
I didn't tried removing `devmode` flag with only `classic` flag. Should I? Kindly suggest

**Comment by phw** [comment]
Yes, you should :) This changed recently

**Comment by Kukanani** [comment]
Unfortunately, I'm having some trouble running the classic snap:

```
/snap/peek/222/command-peek.wrapper: 2: exec: desktop-launch: not found
```
This issue does is not isolated to peek, it seems to affect other classic snaps as well

**Comment by phw** [comment]
@Kukanani First, please don't comment on old closed threads, when new issues arise just open a new issue. I don't look at closed threads usually.

For your issue: Snap handling is currently changing a lot as I want to get this finally released to the stable channel. At the moment please try installing with:

    sudo snap install peek --beta

Would be great if you could leave feedback on https://github.com/phw/peek/issues/84 with your experience using it.
