### ISSUE TITLE
Recording canceled when I move a Peek window

### ISSUE THREAD

**Issue by Nresun** [phw/peek#542]
**When I start recording (gif, mp4 or any other) and move a peek window, recording stops.**

Gif with the bug:

![Peek Bug](https://user-images.githubusercontent.com/60029529/72660532-4c281280-3a0a-11ea-88bc-2d172f8f95bc.gif)

The gif recorded on second Peek window _(so this artifacts are made also by Peek)_. And in the gif I showed Peek that starts by console command "peek" to demonstrate console output, but this bug happens at any program start: "peek" in console and at simple starting from Mint menu.

Peek installed from _ppa:peek-developers/stable_
Peek version: 1.4.0

My system:
- Linux Mint 19.3
- Cinnamon: 4.4.8
- Linux core: 5.0.0-32-generic
- ffmpeg version: 3.4.6-0ubuntu0.18.04.1

Full ffmpeg information (from command "ffmpeg -version"):
```
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
```

**Comment by phw** [comment]
This is by design. I could probably change it to allow one to save the recording when the window gets moved. But the recording would still show parts of the peek window moved into the recorded area.

**Comment by Nresun** [comment]
I need it. Can I download older version, where this is allowed? When I long ago used Peek on Ubuntu, I could move window and keep record.

**Comment by phw** [comment]
I think I added this cancelling very early. For what do you need this, what exactly is your use case?

**Comment by Nresun** [comment]
I record small instructions, demonstrations and sometimes jokes for my customers, friends, colleagues and sites. It's very habitually for me and for them :)

**Comment by phw** [comment]
Yes, that's what peek is typically used for. But you said you need to move peek's window, why?

All that will happen is that you will move Peek's window frame into the recording area. Moving the recording area together with the window is technically not possible, if that is what you want to do.

**Comment by Nresun** [comment]
Not possible on Linux? It's a pity. On Windows I use LICEcap and it can this.
So thank you for quick answers :)

**Comment by phw** [comment]
Not possible the way Peek is implemented (as a normal window managed by the window manager and off-loading the screen recording to a separate tool).

It would be possible to implement this on X11 with a custom client window. It would be more difficult or likely not possible on Wayland unless implemented by the compositor itself.

**Comment by szmarczak** [comment]
> But you said you need to move peek's window, why?

Sometimes you just want to show different parts of the screen and you don't want to record the whole screen, because there's no need to. E.g. when coding - compiling fails, so you record the console and move Peek to point at the invalid code.

**Comment by fiLLLip** [comment]
Would much prefer if you got the option to save, or at least a question to cancel or save. I was a little baffled about where my recording went when I tried to move it, and soon realized it was gone. After first time you know, but from a usability perspective it's not super nice. Locking the window so it cannot be moved could be another way, if possible :+1:
