### ISSUE TITLE
Ubuntu 18.04 LTS Install Configurartion Problem

### ISSUE THREAD

**Issue by gricn** [phw/peek#547]
When I follow https://github.com/phw/peek#ubuntu tutorial install peek in ubuntu  , something went wrong:

```
➜  ~ sudo add-apt-repository ppa:peek-developers/stable
Cannot add PPA: 'ppa:~peek-developers/ubuntu/stable'.
ERROR: '~peek-developers' user or team does not exist.
```

But just `sudo apt install peek` , peek install is OK and also run perfectly. So I wonder what happen.

**Comment by phw** [comment]
I just tried it, it works for me on Ubuntu 18.04. Maybe there was some network issue or some temporary problem on launchpad.net?

**Comment by gricn** [comment]
It's my fault. I used socks5 proxy. Sorry to bother you.
