### ISSUE TITLE
Coordinating peek in Ubuntu 20.04 LTS release

### ISSUE THREAD

**Issue by hosiet** [phw/peek#548]
Dear Peek developers,

Ubuntu 20.04 LTS will be released in April 2020. It is expected to be an important release for Ubuntu.

Peek has been in Ubuntu's universe section for quite some time. The package comes directly from upstream Debian so I am able to influence Ubuntu's package from upstream Debian as a Debian Developer. Even though you are likely to provide a PPA for the new LTS Ubuntu, some users may still prefer the one in the official repo so it is still important to some extent.

However, Ubuntu's package import will freeze soon by the end of February to prepare for 20.04 LTS release. Before that, I'm wondering if there's anything I could do to change the source code of peek so that those changes can be reflected in Debian and Ubuntu 20.04.

If you prepare a bugfix release on top of 1.4.0, or prepare a new stable release, or point out which commits should be backported on top of 1.4.0 tag: I will be happy to push them onto Debian's peek source code (and have changes migrated to Ubuntu) before 2020-02-20.

**Comment by phw** [comment]
Thanks for the heads up. Yes, that's a good reason to push a release out. I wanted to get back to peek anyway soon, now I just have to hurry up a bit. I should be able to tackle this till end of next week I think.

Off topic to peek, but I'm also involved in [MusicBrainz Picard](https://github.com/metabrainz/picard) development and we are about to release version 2.3, which is an important release for us with a lot of improvements and polishing. It would be great to get this into a Ubuntu LTS as well. Who do I have to bug about this if I want to see this happen?

**Comment by hosiet** [comment]
@phw Thanks for the info. In Debian, you can find the status of package picard as well as its maintainer information at https://tracker.debian.org/pkg/picard . Feel free to submit a bug for this package or you may directly contact its maintainers (the [debian-multimedia](https://lists.debian.org/debian-multimedia/) mailing list and the direct maintainer [Sebastian Ramacher](https://qa.debian.org/developer.php?email=sramacher%40debian.org)).

**Comment by phw** [comment]
@hosiet I have tagged release 1.5.0, see https://github.com/phw/peek/releases/tag/v1.5.0

I hope it's still in time. How exactly is the sync from Debian unstable to Ubuntu working? Will this get pulled automatically by Ubuntu once it is in Debian unstable?

**Comment by hosiet** [comment]
The sync (as well as the freeze of which) is described in https://wiki.ubuntu.com/DebianImportFreeze . For Ubuntu 20.04 LTS, the freeze date is [Feb. 27, 2020](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule).

I have uploaded peek 1.5-1 onto Debian Unstable. It is supposed to be autosync-ed to Ubuntu within 24 hours. I will let you know and close this issue when that happens.

**Comment by hosiet** [comment]
The progress in Ubuntu can be monitored here: https://launchpad.net/ubuntu/+source/peek . Looks like everything is going on well and it should be in the repo now. Closing this issue.
