### ISSUE TITLE
Countdown gets recorded sometimes

### ISSUE THREAD

**Issue by sketchbuch** [phw/peek#551]
Sometimes when making a gif recording the countdown appears in the final gif.

See https://raw.githubusercontent.com/sketchbuch/vsc-packages/master/docs/images/vsc-packages-ani.gif as an example.

This was made with version 1.3.1-6 on Ubuntu Linux 19.04 installed via the Ubuntu software centre.

Can you make sure the countdown has finished before starting to record?

**Comment by phw** [comment]
Yes, this was already reported at https://github.com/phw/peek/issues/208 . It's a tricky issue to solve as hiding the countdown is not always happening instantly due to the asynchronous nature of the UI. Maybe a workaround is to hide it a tiny bit too early.
