### ISSUE TITLE
Theme parsing error on KDE

### ISSUE THREAD

**Issue by Alchez** [phw/peek#559]
**System Information:**

- **Peek:** 1.4.0
- **GTK:** 3.22.30
- **OS:** Ubuntu 18.04.4 LTS x86_64
- **Resolution:** 2560x1080
- **Shell:** zsh 5.4.2
- **DE:** KDE Plasma
- **Theme:** Breeze Dark [KDE], Breeze [GTK2/3]

<hr>

When I start Peek through the terminal, it gives me the following error:

```
(peek:5661): WARNING **: 12:28:54.927: Binding '<Ctrl><Alt>R' failed!
Using screen recorder backend ffmpeg

(peek:5661): Gtk-WARNING **: 12:28:54.944: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(peek:5661): Gtk-WARNING **: 12:28:54.944: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
```

Trying to start GIF recording in the window (any screen size) causes the recorder to stop as soon as the countdown is done.

I'm not sure if it's a compatibility issue with Peek, or if my environment is somehow misconfigured. Creating an issue anyway to log this issue.

**Comment by phw** [comment]
I don't think the Gtk theme warning is related to the recording not happening. That's some issue with the used theme (Breeze). It's also just a deprecation warning.

But it's strange that there is no error message. Does it show the error dialog or just silently stops? Are you using KDE with Wayland probably?

Can you try if directly recording WebM works? If not, please try if a command like this works:

ffmpeg -f x11grab -i $DISPLAY+100,100 -video_size 100x100 ~/test.webm

Just to verify ffmpeg screen recording works in general.

**Comment by Alchez** [comment]
> But it's strange that there is no error message. Does it show the error dialog or just silently stops? Are you using KDE with Wayland probably?

It just silently fails, no errors in the terminal. I'm not completely sure if I'm using Wayland, but from a [quick search](https://askubuntu.com/questions/904940/how-can-i-tell-if-i-am-running-wayland), the output of `echo $XDG_SESSION_TYPE` is `x11` and the output of `echo $DESKTOP_SESSION` is `plasma`.

> Can you try if directly recording WebM works? If not, please try if a command like this works:
> 
> ffmpeg -f x11grab -i $DISPLAY+100,100 -video_size 100x100 ~/test.webm
> 
> Just to verify ffmpeg screen recording works in general.

I ran this command, and this works for me. I ran it for a minute, and it created a `.webm` file for me without any errors.
