### ISSUE TITLE
Use libav or ffmpeg 

### ISSUE THREAD

**Issue by khurshid-alam** [phw/peek#56]
Ubuntu uses libav by default. It would be nice if peek can depend on either of of them.

I don't want to install ffmpeg as it creates problems in some players (mpv, smplayer) when both of them are installed.

**Comment by fbruetting** [comment]
Make no sense since almost every other distro on the planet uses FFmpeg (some switched back to FFmpeg in the past years). Further FFmpeg seems better for the future, because they got the fastest AV1 encoder on the planet and should provide better overall performance.

**Comment by khurshid-alam** [comment]
@fbruetting Distro doesn't choose which one is default. It's the application that depends on it forces distro to ship it by default. Also it doesn't matter which one is the future. As of now, libav hasn't deprecated and Ubuntu and all other Ubuntu based distros (Elementary, Mint etc) use it as default. If peek can work with libav there is no need to pull another dependency. And about encoder....libav works just fine with AV1.

**Comment by fbruetting** [comment]
Yes, and the contrary is true for me (Fedora / RHEL / most other distros): Depending on libav would pull a (superfluous) dependency for us. We don't have libav shipped, but FFmpeg. I read some articles last year and came to the point that FFmpeg seems to be better than libav, so I prefer the current situation.

**Comment by phw** [comment]
I had actually been working on libav support already, but as I thought it would be straight forward at first it had some unexpected differences to ffmpeg. The idea was of course to support both.

I will see if I can finish the work on it, but my problem is currently that I currently hardly find the time to do tasks that take a bit longer.

**Comment by khurshid-alam** [comment]
@fbruetting 

>Depending on libav would pull a (superfluous) dependency for us.

You misunderstood. See @phw comment. It will depend either on ffmpeg **OR** libav whichever available.

**Comment by fbruetting** [comment]
You're right, sorry!

**Comment by phw** [comment]
I have implemented libav support. Currently this is automatic, if ffmpeg is available that is used, avconv is second choice.

I would be happy if somebody could test this. For Ubuntu there is now a daily built PPA at https://code.launchpad.net/~peek-developers/+archive/ubuntu/daily

**Comment by khurshid-alam** [comment]
@phw 

I think you need to change dependency under debian/control. Assuming avconv is your run time dependency it should be

```diff
Package: peek
Architecture: any
Depends: ${misc:Depends},
 ${shlibs:Depends},
- ffmpeg,
+ livav-tools | ffmpeg,
+ libavcodec57
 imagemagick
Description: create animated GIF screencasts
```

**Comment by phw** [comment]
@khurshid-alam Indeed, thanks for the heads up. Fixed and packages updated (currently building, should be read in a few minutes).
