### ISSUE TITLE
Could not start recording (org.gnome.Shell.Screencast)

### ISSUE THREAD

**Issue by bartoszkoper** [phw/peek#562]
Peek: 1.3.1
GTK: 3.24.8
GLib: 2.60.0

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
Please see https://github.com/phw/peek#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors

If this does not answer or solve your issue please provide more details here, especially any output in journalctl.
