### ISSUE TITLE
Ninja makes no executable on Manjaro linux

### ISSUE THREAD

**Issue by ColdSpirit0** [phw/peek#568]
Hi! I followed by [instruction](https://github.com/phw/peek#from-source) and after 'ninja' command dont see any executable. What I can do to fix it?

Also I cant install [AUR package](https://aur.archlinux.org/packages/peek-git) because it contains CRLF symbols and yay throws error on it.

**Comment by gort818** [comment]
It should be located in builddir/src/

**Comment by ColdSpirit0** [comment]
Found it, thanks! Im think need to change ./peek to ./src/peek in the instruction.
