### ISSUE TITLE
Just saving the background when using i3wm 

### ISSUE THREAD

**Issue by NikosEfthias** [phw/peek#57]

**Comment by djmaze** [comment]
Duplicate of #57

**Comment by phw** [comment]
Sorry, missed this somehow. This sounds a lot like #12.

Do you have compositing enabled? Please note that there is a known issue with i3 which will not allow you to ineract with the UI inside the recording area.

**Comment by phw** [comment]
Closing this as there is not enough information to pin this down. My best guess is that compositing was not enabled, see #12 and https://github.com/phw/peek#the-recording-area-is-all-black-how-can-i-record-anything . Feel free to re-open with additional details if compositing does not solve the issue.
