### ISSUE TITLE
Issue with screencap on Ubuntu 20.04 (Regolith)

### ISSUE THREAD

**Issue by tobalr** [phw/peek#595]
Hi.
First of all. Thank you for this great piece of FOSS. 
I have updated to the latest version of Ubuntu and have run into some trouble. 
I'm running regolith (i3), but this issue seems unrelated.

Application opens and I can select the area i want to capture. When the count down has completed it fails with this error.

I can that libsndio7.0 is installed
`libsndio7.0/focal,now 1.5.0-3 amd64 [installed,automatic]`

Please get in touch if there is any more information that could help shed some light on the issue :)

## Following part is the content of the error report from the crash:

Peek: 1.5.1
GTK: 3.24.13
GLib: 2.63.5
Desktop: Regolith:GNOME-Flashback:GNOME
Display server: X
FFmpeg version:
```

```

Output format: webm
gifski enabled: false

Error details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 950x174 -i :0+1,884 -filter:v scale=iw/1:-1 -codec:v libvpx-vp9 -qmin 10 -qmax 50 -crf 13 -b:v 1M -pix_fmt yuv420p -r 10 -y /home/tobalr/.cache/peek/peek1J83J0.webm" failed with status 32512 (received signal 0).

Output:
ffmpeg: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory
```

**Comment by gort818** [comment]
Looks like it is expecting  libsndio6 but you have version 7. Can you try building peek yourself?

**Comment by phw** [comment]
The packages are built for Ubuntu. Depending on the changes Regolith makes they might or might not be compatible.

However, in your case this is an incompatibility of ffmpeg with libsndio. If you are using any third-party repositories which include either ffmpeg or libsndio this is probably the cause. If not I would recommend you to report the issue of ffmpeg not working to Regolith.

**Comment by tobalr** [comment]
Hi Thank you for your fast and precise response.
This was a self inflicted issue. I had an old ffmpeg binary compiled from another system to show up in my path due to a restore from backup and an error on my part.
Sorry for the inconvenience. 

Again, thank you for creating a great piece of software!
