### ISSUE TITLE
Desktop flash when using Peek on Linux Mint 18.3

### ISSUE THREAD

**Issue by grimmer-std** [phw/peek#604]
I'm not sure how to reproduce it yet, but you can see an example here 
![Peek 2020-05-28 16-38](https://user-images.githubusercontent.com/12690999/83156502-c9733a80-a102-11ea-8e07-05667a5665c0.gif) 
**but** it also happens when I recorded as *.webm format.

Peek version: 1.3.1 (from Ubuntu PPA)
GTK: 3.18.9
GLib: 2.23
gifski enabled: true
OS: Linux Mint 18.3 Cinnamon 64-bit
```
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
```

**Comment by phw** [comment]
This is usually caused by graphic driver issues. It's nothing that can be solved by Peek.

If you are using Intel graphics switching between UXA and SNA acceleration methods can help. See e.g. https://wiki.archlinux.org/index.php/Intel_graphics#AccelMethod

For Nvidia or other drivers I don't have much experience, but it was reported that changing the "Allow Flipping" setting in the NVIDIA control panel can help.

See also https://github.com/phw/peek#my-recorded-gifs-flicker-what-is-wrong

Apart from that updating your OS to a newer release can help, Mint 18 is rather old. There have been many fixes in graphics drivers since then.

**Comment by Ashutosh-Kukreti** [comment]
I fixed it:
>sudo nano /etc/X11/xorg.conf.d/20-intel.conf

>Section "Device"
  >Identifier "Intel Graphics"
  >Driver "intel"
>Option      "AccelMethod"  "uxa"
>EndSection

>Save it and reboot or logout

**Comment by Ashutosh-Kukreti** [comment]
@grimmer-std is this option available in peek or linux mint because I'm using manajro kde

**Comment by grimmer-std** [comment]
@Ashutosh-Kukreti it is available in Nvidia X Server Settings, not in peek. I never used Manjaro but if you have a **Nvidia GPU** it should be similar. phw already linked potential solution for issue related to built-in Intel graphics.

**Comment by Ashutosh-Kukreti** [comment]
@grimmer-std Thank you :)
