### ISSUE TITLE
Running peek -> nothing happends (Ubuntu 20.04)

### ISSUE THREAD

**Issue by vvmspace** [phw/peek#611]
It worked (

```
 ~ peek
 ~  
```

Can not record gif of this action)

**Comment by flyfy1** [comment]
I experience the same issue: open the app, nothing happens

**Comment by lucasmaurice** [comment]
Same here :rip:

**Comment by fabiobm** [comment]
I had the same problem and in my case at least it seems to be the same thing described on #512, no permanent fix yet though. Some useful comments on #544 too.

**Comment by NavyCoat** [comment]
Same issue. Notebook with one external screen, Nvidia MX350 GPU.

**Comment by vvmspace** [comment]
It was gnome bug. Peek loaded in invisible part of disabled monitor.

**Comment by SethFalco** [comment]
Ran into this problem too, vvmspace is correct! Thank you very much!

Quick fix if you encounter this problem would be:
1. Go to "Settings" → "Displays"
2. Place your monitors in a way that it forms a rectangle. (for example, stack them all on-top of each other)
3. Select "Apply" at the top-right.
4. Launch Peek
5. Drag the Peek window to your primary monitor.
6. Revert your display settings back.

In the future, Peek will start at a location you left it. (As in, a location that's actually visible to you.)
