### ISSUE TITLE
Difficult to resize in bspwm

### ISSUE THREAD

**Issue by miguelmota** [phw/peek#628]
Is there a setting in peek to make border thicker or is this a problem with bspwm?

![Peek 2020-07-22 15-17](https://user-images.githubusercontent.com/168240/88234845-85964080-cc2e-11ea-83d2-a0ea978cd0d0.gif)

**Comment by ericdallo** [comment]
@miguelmota Take a look here: https://github.com/phw/peek/issues/199

I use bspwm too and for me, using <kbd>super<kbd> + <kbd>Right click</kbd> seems to help on resizing

**Comment by miguelmota** [comment]
@ericdallo thanks for the tip! works good enough
