### ISSUE TITLE
Save dialog doesn't show up

### ISSUE THREAD

**Issue by foo4foo** [phw/peek#63]
I'm just installed Peek 0.8 on Xubuntu 16.04 but dialog just doesn't show up.

**Comment by hottwaj** [comment]
Not sure if this is exactly the same issue, but on Linux Mint 16.04 recording doesn't work and the save dialog doesn't appear - I get the following in the console:

```
ffmpeg: error while loading shared libraries: libx264.so.146: cannot open shared object file: No such file or directory
Error: Child process exited with code 127
Recording stopped unexpectedly with return code 32512
Error: Broken pipe
Recording stopped unexpectedly with return code 0

(peek:13094): GLib-WARNING **: Error flushing string: Broken pipe
```

Strangely if I run peek under sudo everything works fine - maybe I've got a bad setup?

Cheers

**Comment by phw** [comment]
@hottwaj This second issue looks a lot like a broken setup, as ffmpeg cannot find some libraries.

the information given in the original report really does not help in finding the issue. Please try the latest release 0.9.1 and see if this fixes the issue. If start Peek from the command line and post the output here.

**Comment by phw** [comment]
Closing this as there is not enough information to pin this down. Feel free to re-open with additional details if you can reproduce this with the latest release.
