### ISSUE TITLE
How to debug this "not recording" problem?

### ISSUE THREAD

**Issue by orschiro** [phw/peek#64]
Dear all, 

I am using the latest release on Ubuntu 16.10.

It is just counting down but not actually recording. 

How do I debug this?

Yours,

-Robert

![output](https://cloud.githubusercontent.com/assets/170947/21899673/69f8f806-d8f1-11e6-82ad-f5319f540260.gif)

**Comment by phw** [comment]
Best thing probably would be to start it from command line and look at the console output.

One suspicion, since you are on Ubuntu: Peek currently requires ffmpeg to be installed (the real thing), it does not work with avconv, see also #56

**Comment by orschiro** [comment]
I found the problem! 

```
[x11grab @ 0x5591d90c3d20] Capture area 390x613 at position 1079.120 outside the screen size 1366x768
:0+1079,120: Invalid argument
Error: Child process exited with code 1
Recording stopped unexpectedly with return code 256
```

Two ideas:

1. Can Peek record despite being outside the screen?
2. Can we easily prevent Peek from going outside the screen?

**Comment by phw** [comment]
I have committed a fix for this. The new behavior will clip the recording area if Peek is partially outside the screen. That way you record exactly what you see.

This probably works best with a single monitor or multiple monitors of equal resolution that form a nice rectangular area. On my setup with a large and a small monitor I can still get some weird cases of recorded noise or no recording at all when placing peek on the edges, but this gets arbitrarily complex and I will leave it as is for now.

**Comment by orschiro** [comment]
Thank you so much for this fix!

I cannot wait to receive it on my Ubuntu 16.10 and test it. :-)
