### ISSUE TITLE
Window tearing when recording an OpenGL window

### ISSUE THREAD

**Issue by mehcode** [phw/peek#65]
![pong_c8_normal](https://cloud.githubusercontent.com/assets/753919/21915334/241a9356-d8ee-11e6-81cc-65ceb4fbfa9d.gif)

![pong_c8_delay_10](https://cloud.githubusercontent.com/assets/753919/21915383/741bebac-d8ee-11e6-82e7-5d8981de886b.gif)

I recorded that on Arch Linux with Peek 0.8.0 (60 FPS). The window doesn't actually tear .. it seems to be an artifact of the recording. Any ideas?

**Comment by phw** [comment]
Yes, most likely a video driver  issue. Please see my answer at https://github.com/phw/peek/issues/42#issuecomment-258705832

**Comment by mehcode** [comment]
I'm actually using the NVIDIA binary drivers. Hmm. Darn. I was hoping for an easy solution. Heh. I can try seeing if the OSS drivers fare better here.

**Comment by phw** [comment]
I have no experience with Nvidia drivers and possible fixes.

You can try with other screen recording software if it makes a difference, maybe this gives us some clue.

**Comment by phw** [comment]
Closing this as I don't think this is inside the issues I can fix. I have added this problem to the new FAQ section in the readme.
