### ISSUE TITLE
Recording area won't go above 888x542 pixels when resizing window

### ISSUE THREAD

**Issue by Jetroid** [phw/peek#661]
Hi, 

I'm able to resize fine, but I'm restricted to a maximum recording area of 888x542 pixels. I can reduce this in either direction (eg 888x300, or 300x542), but cannot increase width past 888 pixels nor height past 542 pixels.

Using the Set window size function works perfectly, but if I try to resize the window manually it snaps back to 888x542. 

I'm using i3wm.

Regards,
Jet

**Comment by j0hnmeow** [comment]
I have the opposite, I can't make it smaller than 227x40 (`Set window size` doesn't help). Using GNOME.

**Comment by Jetroid** [comment]
@j0hnmeow, I'd guess that your issue is related to https://github.com/phw/peek/issues/580

**Comment by j0hnmeow** [comment]
I think both issues are related to each other

**Comment by Jetroid** [comment]
Hi all, found out that this was not a bug in peek. My i3wm was configured to with a "floating_maximum_size 900 x 600". Upping those numbers let me record more of the screen.

User error!
