### ISSUE TITLE
Can't seem to get crisp recordings

### ISSUE THREAD

**Issue by itmecho** [phw/peek#665]
I'm trying to record a simple demo for my project but I can't seem to get crisp recordings. I've tried both GIF with gifski installed and the quality slider at max as well as WebM but they both come out blurry. I've also tried with the default 10fps as well as 24fps but the quality doesn't change. Am I doing something wrong?

GIF: https://raw.githubusercontent.com/itmecho/bufterm.nvim/master/demo.gif
WebM: https://raw.githubusercontent.com/itmecho/bufterm.nvim/master/demo.webm

### My system:
**OS:** Arch Linux
**`uname -a`:** `Linux precision 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64 GNU/Linux`
**WM:** `bspwm`
**`peek --version`:** `Peek 1.5.1`
**`gifski --version`:** `gifski 1.2.2`
**`ffmpeg -version`:**
```
ffmpeg version n4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.1.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

**Comment by MarcelRobitaille** [comment]
Same for me. The preview is also blurry for me, so I think it's just recording blur. Is the preview also blurry for you?

**Comment by itmecho** [comment]
I completely forgot I opened this!

I actually figured out what was causing it for me. Turns out it was picom applying blur to peek. I fixed it by adding the following to my `picom.conf`

```
blur-background-exclude = [
	"name ~= 'Peek'",
  ...
];
```

[Here's the link to the file](https://github.com/itmecho/dotfiles/blob/master/picom/.config/picom/picom.conf)

If you have the same setup and this fixes it, let me know and I'll close the issue

**Comment by MarcelRobitaille** [comment]
That makes sense. I also use picom. I will try it. Thank you.

**Comment by MarcelRobitaille** [comment]
That worked for me too! Thanks!

Should this be closed then?

**Comment by itmecho** [comment]
I think so! People should be able to use it as a solution if they find it while searching!
