### ISSUE TITLE
Put Close button to the left

### ISSUE THREAD

**Issue by orschiro** [phw/peek#67]
Dear all, 

What do you think of putting the Close button to the left to have consistency with the default position on Ubuntu?

Yours,

-Robert

![selection_016](https://cloud.githubusercontent.com/assets/170947/21976182/e4e3d784-dbd0-11e6-8356-fc3c4a4c9f3c.png)
![workspace 1_015](https://cloud.githubusercontent.com/assets/170947/21976181/e4e37f50-dbd0-11e6-922d-bbb0508168a5.png)

**Comment by phw** [comment]
Thanks for the suggestion, Robert. I had already thought about this when testing on Ubuntu.

I honestly think that needing Ubuntu / Unity specific patches for everything is a pain in the ass. But given the popularity of Ubuntu I will probably look into this and make it work somehow :)

**Comment by orschiro** [comment]
Wow, I really appreciate your efforts!

And I guess I am not the only Ubuntu user who will like that. :-)

-R

**Comment by orschiro** [comment]
This is fantastic, thank you so much @phw!
