### ISSUE TITLE
ScreencastArea method is not implemented in GNOME Flashback!

### ISSUE THREAD

**Issue by jfernandz** [phw/peek#677]
Peek: 1.5.1
GTK: 3.24.21
GLib: 2.64.4
Desktop: GNOME
Display server: X
FFmpeg version:
```
ffmpeg version n4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.1.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

Output format: gif
gifski enabled: false

Error details:
```
GDBus.Error:org.freedesktop.DBus.Error.NotSupported: ScreencastArea method is not implemented in GNOME Flashback!
```

Is there any alternative to use peek with Gnome Flashback?

**Comment by bytedicer** [comment]
+1
Just ran into the same problem. Also: will there be a groovy repo soon?

**Comment by jfernandz** [comment]
@bytedicer I'm not sure, cause peek devs could argue that this problem is from Gnome Flashback, but of course I'd like to use an alternative method in the case that Gnome Flashback wont implement the method.

**Comment by jfernandz** [comment]
A good workaround is disabling Screencast for Gnome Flashback to force `peek` to use a different method.

So if you use `dconf` editor or just run `gsettings set org.gnome.gnome-flashback screencast false` you will have a good workaround.

You can see this in the [issue report for Gnome Flashback](https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/70#note_1003572)

**Comment by eduncan911** [comment]
Work-around still required, and still working today!  Pop-os 22.04 LTS
