### ISSUE TITLE
Support new recording interface for GNOME 3.38

### ISSUE THREAD

**Issue by eminfedar** [phw/peek#681]
There is only black screen on Debian Testing, Gnome Wayland, 1.5.1 version. Can't record anything.

**Comment by Santinell** [comment]
Have the same problem. My system Manjaro Gnome
Looks like Wayland became default for Gnome DE

**Comment by adrm** [comment]
Same in Fedora Silverblue 33 with the flatpak version. It only records a black screen and the mouse pointer.

**Comment by emanuelhfarias** [comment]
same with Fedora 33 installed via RPM. Fedora 33 uses wayland by default.

**Comment by plowpath** [comment]
i have the same issue with ffmpeg backend. i would recommend people here to use ```peek --backend=gnome-shell``` in the meantime

**Comment by adrm** [comment]
@plowpath wow, I didn't know about that issue. That means it's working when launching from the terminal with that command. Is there a way to set that backend as the default? Peek's preferences do not allow that setting. I suppose editing the desktop file would work, but is there anything GUI-user-friendly?

**Comment by phw** [comment]
The problem is that the latest GNOME release ditched the old DBus interface for screen recording and provides a new one. This is not yet reported. The only workaround currently would be to run with Xorg instead of Wayland and use the ffmpeg backend.

**Comment by digitalethics** [comment]
> i have the same issue with ffmpeg backend. i would recommend people here to use `peek --backend=gnome-shell` in the meantime

What is the default recording backend on Wayland? Is there a terminal command to check for what recording backend peek was configured by a particular distro?

**Comment by openscript** [comment]
I ran in the same issue on Arch with Wayland. Only the cursor is recorded.

**Comment by bphd** [comment]
> i have the same issue with ffmpeg backend. i would recommend people here to use `peek --backend=gnome-shell` in the meantime

`Failed to initialize recorder: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`

**Comment by taoqf** [comment]
even record mp4 with `peek --backend=gnome-shell` will blocked before recording.  fedora 33

**Comment by cbix** [comment]
Might be an idea to send a feature request to ffmpeg to support the Wayland / PipeWire / xdg-desktop-portal way of screencapture and/or this custom GNOME interface.

For those who want to set `--backend=gnome-shell` for the desktop launchers, do
`cp /usr/share/applications/com.uploadedlobster.peek.desktop ~/.local/share/applications/; cp /usr/share/dbus-1/services/com.uploadedlobster.peek.service ~/.local/share/dbus-1/services/`
and then change these local files adding `--backend=gnome-shell` to the `Exec=...` line.
- - -
> `Failed to initialize recorder: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
> 
> And without arguments I only got the cursor at recording

@bphd do you have `gst-plugin-gtk` and `gst-plugins-ugly` installed? What's your gnome-shell version?

**Comment by mattwelke** [comment]
Works for me on Ubuntu 20.10 with GNOME 3.38. Just recorded a GIF after installing and the saved GIF looks good.

```
~ > cat /usr/share/gnome/gnome-version.xml
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>38</minor>
 <micro>3</micro>
 <distributor>Ubuntu</distributor>
 <!--<date></date>-->
```

**Comment by Gotterbild** [comment]
`peek --backend=gnome-shell` doesn't work for me on Manjaro with Gnome 41.3 on Wayland

App starts fine. But as soon as recording starts, it just hangs. In some time the dialog appears with info that app is not responding.

That is for both app versions from official Manjaro repositories and Flatpak.

**Comment by bphd** [comment]
From what I've understood it's not "not planned". It's not for WayLand but for Gnome, so planned for that issue

**Comment by openscript** [comment]
Maybe an alternative: https://github.com/SeaDve/Kooha
