### ISSUE TITLE
Black gif

### ISSUE THREAD

**Issue by pakhomchik** [phw/peek#7]
First, is black area in peek's window:
![_015](https://cloud.githubusercontent.com/assets/668493/14627507/b2ffc46e-0627-11e6-91d0-3ec3dce7a1b4.png)
Second, only cursor is recorded:
![peek 2016-04-19 12-07](https://cloud.githubusercontent.com/assets/668493/14627492/9c2aac36-0627-11e6-9a32-9b491b50ad8c.gif)

kernel: 4.4.5-1
video: Radeon HD 6530D
driver: xf86-video-ati
DE: mate 1.12.1

*peek's output:*
```
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdcadec --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, x11grab, from ':0+993,560':
  Duration: N/A, start: 1461039448.329935, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 440x276, 15 fps, 15 tbr, 1000k tbn, 15 tbc
Output #0, avi, to '/tmp/peekCGO6FY.avi':
  Metadata:
    ISFT            : Lavf57.25.100
    Stream #0:0: Video: huffyuv (HFYU / 0x55594648), rgb24, 440x276, q=2-31, 200 kb/s, 15 fps, 15 tbn, 15 tbc
    Metadata:
      encoder         : Lavc57.24.102 huffyuv
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> huffyuv (native))
Press [q] to stop, [?] for help
Recording stopped15 q=-0.0 size=    8671kB time=00:00:06.46 bitrate=10983.9kbits/s speed=1.01x    
frame=  105 fps= 15 q=-0.0 Lsize=    9385kB time=00:00:07.00 bitrate=10982.8kbits/s speed=1.01x    
video:9377kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.086569%

**Comment by phw** [comment]
Your window manager needs to support compositing in order for the cut-out area of the Peek window to work. I have no idea of Mate's default window manager, but according to https://wiki.archlinux.org/index.php/MATE#Enabling_compositing it should support compositing, but it is disabled by default. 

Can you verify whether enabling compositing solves the issue?

**Comment by pakhomchik** [comment]
installing  xcompmgr and running `xcompmgr -c` solved the problem.
Thanx.

**Comment by phw** [comment]
Glad this solved it for you :)

Since I see no way to support Windows with "holes" in it with Gtk3 without composition and I have no plans to implement any workaround I close this issue.

**Comment by freddii** [comment]
in mate 1.8.1 i had to enable software-composing-windowmanager:
system > settings > window > enable [x] software-composing-windowmanager

**Comment by phw** [comment]
Thanks for the info. I could maybe detect whether compositing is enabled or not and issue a warning in the application. And probably add short instructions for different desktop environment to the README

**Comment by freddii** [comment]
For xfce 4.12:

English:
Applications > Settings > Windows Manager Tweaks > Compositor > Enable Display Compositing

German:
Menü > Einstellungen > Feineinstellung der Fensterverwaltung > Komposit [x]Anzeigenkomposit aktivieren

**Comment by chteuchteu** [comment]
Nice! Yet another thing to be put in our F.A.Q.!

**Comment by phw** [comment]
Recording without compositor will be enabled by https://github.com/phw/peek/pull/148
