### ISSUE TITLE
Ubuntu 16.10 - installation

### ISSUE THREAD

**Issue by MartyIX** [phw/peek#71]
Hi,

to install on Ubuntu 16.10 I did:

```
sudo apt-get install libsdl1.2debian ffmpeg libavdevice57  libvdpau1
```

instead of:

```
sudo apt-get install libsdl1.2debian ffmpeg libavdevice-ffmpeg56
```

Otherwise, it works great. 

Thanks

**Comment by phw** [comment]
Thanks a lot for this. I have now added a Ubuntu PPA which should simplify things.

See https://code.launchpad.net/~peek-developers/+archive/ubuntu/stable and https://code.launchpad.net/~peek-developers/+archive/ubuntu/daily
