### ISSUE TITLE
How to use with a compositor

### ISSUE THREAD

**Issue by scrouthtv** [phw/peek#719]
Hello, 

I am using i3wm together with picom. picom is a compositor that blurs the transparent background of windows:
![image](https://user-images.githubusercontent.com/23227405/112746217-c3ade600-8fad-11eb-9df4-b2cf0354e62c.png)

When I open peek, the recording window also gets blurred:
![image](https://user-images.githubusercontent.com/23227405/112746252-e93aef80-8fad-11eb-899c-d95ffccda317.png)

Even though I have picom configured to not blur peek. Should I report this to them?

The recording is also blurred.

Thanks for any help in advance.

**Comment by scrouthtv** [comment]
Nvm, I had a typo in the window class name, it's `Peek` not `peek`.

**Comment by curi0usJack** [comment]
Mind posting your picom config please? I added Peek to blur-background-exclude and am still having your issue.

**Comment by scrouthtv** [comment]
<details>
<summary>picom.conf</summary>

```javascript
log-level = "info";
log-file = "/home/lenni/compton.log";

experimental-backends = false;
backend = "glx";
vsync = false;
//refresh-rate = 60;
unredir-if-possible = false;

corner-radius = 4;
round-borders = 1;
round-borders-rule = [
	"2:class_g = 'Termite'"
];

shadow = true;
shadow-radius = 16;
shadow-offset-x = -16;
shadow-offset-y = -16;
shadow-red = .03;
shadow-green = .03;
shadow-blue = .03;

blur: {
	method = "dual_kawase";
	strength = 7;
	background = false;
}

// for exclude read
// https://github.com/yshui/picom/blob/next/man/picom.1.asciidoc

shadow-exclude = [
	"class_g = 'i3-frame'",
	"class_i = 'tray'",
	"class_g = 'Peek'"
];

blur-background-exclude = [
	"class_g = 'i3-frame'",
	"class_g = 'Peek'",
	"class_g = 'firefoxdeveloperedition'",
	"class_g = 'discord'",
	"class_g = 'jetbrains-idea-ce'",
	"class_g = 'Pavucontrol'"
];

opacity-rule = [
	"92:class_g = 'MuPDF'"
];
```
</details>

this is with ibhagwan's fork of picom.

**Comment by johnzzon** [comment]
Had the same issue with compton as my compositor. Figured I'd put the config here for other googlers. I put it in `~/.config/compton.conf`

```
shadow-exclude = [
  "class_g ?= 'Peek'"
];
```
