### ISSUE TITLE
Support MP4 and/or WEBM

### ISSUE THREAD

**Issue by dAnjou** [phw/peek#73]
Original title: Why GIF? Why not MP4 and/or WEBM?

This is an honest question. To my knowledge and for the use cases of this tool GIF seems to be far inferior to MP4 and WEBM both of which can be played back natively by most browsers.

**Comment by phw** [comment]
No particular reason other than GIF is still more universal usable and it is what I needed. Having said that I want to make MP4 an option. Haven't thought about WEBM yet, but I don't see a reason against it.

But just to be clear: the focus of Peek is definitely in making short screen recordings of parts of the screen, and the support for proper video formats won't mean that changes :) I have no intentions of turning Peek into a feature packed general purpose screen recording solution.

**Comment by phw** [comment]
I took the freedom to update the title of this feature request, I hope you don't mind.

**Comment by phw** [comment]
I have committed WebM support. Not yet sure about MP4, but if needed it should be easy to add now.
