### ISSUE TITLE
Failed to execute child process "convert" on Fedora 25

### ISSUE THREAD

**Issue by hoto** [phw/peek#75]
Hi

I followed this https://github.com/phw/peek/issues/41 tutorial how to install `peek` on fedora (mine is fedora 25, kernel 4.9.6-200.fc25.x86_64) and `peek` is starting and recording (i can see the `avi` file growing) but then when I want to save the file it just hangs indefinitely.
Error is in the screen.
It pretty much says `Error: Failed to execute child process "convert" (No such file or directory)`

![screenshot from 2017-02-04 21-49-05](https://cloud.githubusercontent.com/assets/3105832/22621464/a62ea718-eb24-11e6-812d-27e8662481d3.png)

My installation procedure is here (I also tried doing it manually but same result):
https://github.com/hoto/ansible-home-fedora/blob/master/roles/peek/tasks/peek_installer.yml

Btw I use `peek` on ubuntu and love it, thanks for creating and maintaining it.

**Comment by hoto** [comment]
#41

**Comment by phw** [comment]
The imagemagick convert command is a dependency, I think that is missing for you. Try if installing imagemagick helps to solve this.

**Comment by hoto** [comment]
Thanks @phw for help :)
I'm stupid not to read the `actual` project Readme in the first place ;)

I've installed `ImageMagic` and `ImageMagic-devel` (just to be sure).
Gifs are now being saved but they are black (sometimes mouse is visible).
I've checked the `avi` files and they are also black.

Here is a sample gif with just a cursor:
![peek 2017-02-05 13-36](https://cloud.githubusercontent.com/assets/3105832/22626229/33d5e534-eba9-11e6-83c1-61f86e22d3d4.gif)

The only thing I'm not sure I have is `Window manager with compositing enabled`.
But after googling it I gave up as I don't want to break something on my fedora...

Output from the console:
![screenshot from 2017-02-05 13-45-48](https://cloud.githubusercontent.com/assets/3105832/22626244/72d6395a-eba9-11e6-9c58-b46265b0a8b0.png)

I'm closing this one as I won't be making changes to window composition as I find it too risky.

Thanks for help!

**Comment by hoto** [comment]
i finally found out why it did not work, I was using the default Wayland instead of Xorgs. After switching to Xorgs peek is working on my Fedora 25.

To change to Xorgs (got the screenshot from the internet, it's not mine) select the one that says `Xorgs`:
![wayland-login](https://cloud.githubusercontent.com/assets/3105832/23581807/9d0e12dc-011c-11e7-8d34-57fc35d8e041.png)

It works!
![peek 2017-03-04 20-51](https://cloud.githubusercontent.com/assets/3105832/23581812/b352cd58-011c-11e7-87d3-9c287d9f731a.gif)

**Comment by phw** [comment]
Thanks for letting me know. As you are using Gnome there is good news: the current development version can be run under a Gnome Wayland session, it is using the built-in screen recording of Gnome Shell. The only requirement is that you have to run it as an X app with XWayland, fully native Wayland is not yet possible.
