### ISSUE TITLE
Redundant options "Show in File Manager - Cancel - OK"

### ISSUE THREAD

**Issue by dandv** [phw/peek#76]
![image](https://cloud.githubusercontent.com/assets/33569/22918170/ce5754a4-f23d-11e6-9d04-96741f38ee0a.png)

Can we have just "Show in File Manager" and "OK"? Also, the wording of the dialog shouldn't mention the "Click here" part. The second line can be removed. #ux

**Comment by phw** [comment]
This has already been reported in #55 and is fixed in master, I just haven't come around to make a proper release.

This is actually some Ubuntu Unity specific notification stupidity, where the notification turns into a dialog box as soon as actions are involved.

**Comment by dandv** [comment]
I see, thanks.

BTW, I've been considering ditching Ubuntu, in large part because of their stubborn pigheadedness in not giving any shit on user requests such as [making the close button location configurable](https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1622043) or moving the stupid top panel (which is empty 99% of the time and just wastes space) to [the bottom](https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1627394).

What other distro/DE do you recommend? Not [KDE/Plasma - way too broken](https://forum.kde.org/viewtopic.php?f=289&t=135101&p=363293#p363293).

**Comment by phw** [comment]
Really depends. If you want a bottom panel and want to have a distribution that is technical close to Ubuntu, maybe give Linux Mint a try with the Cinnamon desktop. I used it for a while after my Ubuntu times and actually liked the interface. Downside for me was, that they depend on Ubuntu packages, which depends on Debian packages and all three do their share of patching. So if you encounter a bug it can be hard to see who is to blame (and it is often not upstream).

Personally I use Arch Linux with the Gnome 3 desktop. Reasons for me are the up-to-date packages, no or minimal patching of upstream releases and full control over what gets installed and which service activated. Downside is probably a higher technical involvement required.

If I wouldn't be using Arch I would likely give Fedora a try. Have not really used it myself, but heard much good.

Also I like and use Gnome 3, but if you dislike mostly empty top panels that cannot be moved to the bottom probably not for you 😉 On the other hand there are plenty of extensions for Gnome 3 that allow you to fill that panel with useful and useless stuff.
