### ISSUE TITLE
Allow Mouse Events to underlying window

### ISSUE THREAD

**Issue by bit101** [phw/peek#77]
I'm trying to record some interaction on a web page, moving the mouse on the page, clicking items on the page. But when I move the mouse over the area that is being recorded, the underlying window does not receive mouse move events. And mouse clicks and drags are, of course, intercepted by Peek. This makes it impossible to capture what I want to capture.

**Comment by phw** [comment]
This is already implemented. If it is not working for you I am not sure I can do something.

What desktop environment / window manager and hat version of Gtk are you using?

It is already known that this does not work in all window managers, notably i3 and awesome. See issue #52

**Comment by bit101** [comment]
Ah, OK. Looks to be an i3 issue. I had a look through the other issues before I posted, but missed that one.

**Comment by bit101** [comment]
Verified it's working well enough under a different wm. Thanks.
