### ISSUE TITLE
Black recording under wayland

### ISSUE THREAD

**Issue by djdevin** [phw/peek#778]
Works under X11 but just records black under Wayland. The cursor is the only thing recorded.

**Comment by djdevin** [comment]
Sorry, just saw the project page note about Wayland.

**Comment by opadilla** [comment]
I was seeing this also on my new 21.04 install.   Looks like it defaults to Wayland out of the box.   Starting peek with that env var setting specified in the project page note did nothing for me.  Fortunately, there is an icon on the login screen in the bottom right that lets you run in X11.  No more black recording after that.
