### ISSUE TITLE
Add to Debian main repository

### ISSUE THREAD

**Issue by turicas** [phw/peek#78]
First of all, thanks for creating this project! :-)

I'd like to suggest to add this package on Debian -- since you're already generating deb packages on the PPA, I think it won't be that hard. I friend of mine is a Debian Maintainer and I think he can help here.

@kretcheu, could you please package this software?

**Comment by phw** [comment]
Yes, I would love to see this packaged in Debian :) So if somebody can make this happens this would be awesome.

**Comment by phw** [comment]
Just a heads up that I have released Peek 0.9 and updated the Debian build files in https://github.com/phw/peek/tree/debian-packaging, so this is probably the right time to do more packaging.

Also some review of the Debian packaging files by a real packager would be good, my Debian packaging fu is not very good. Given that I have just "stolen" the packaging from http://main.mepis-deb.org/mx/testrepo/pool/test/p/peek/ and done only little changes they are probably good, though :)

**Comment by kretcheu** [comment]
Hi,
I just did the ITP (Intent to package) thats the first step for package can enter in Debian.
I will try to make a deb package according Debian policies and then send to my sponsor to verification and aproval. 
To see what happends:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855666

regards.

**Comment by phw** [comment]
Just a heads up that Peek 1.0 is out. Dependencies changed a bit, it now need libkeybinder3 to build and run. Also I added gstreamer-plugins as recommended to the Ubuntu packages as they are needed when using the new native Gnome Shell recording.

see https://github.com/phw/peek/blob/debian-packaging/debian/control

**Comment by kyodev** [comment]
news about package in debian repo by @kretcheu?

**Comment by kretcheu** [comment]
Debian now is in Full-freeze, so no new packages is allowed.
stretch is almost ready, when it is released I will can upload to news packages.

**Comment by kyodev** [comment]
ok, boring, then we must wait...
thanks for this new package in Debian

**Comment by phw** [comment]
@kretcheu I recently added the debian control files to the main repo, due to #144 (package for Elementary OS) . Now I know this is discouraged as it makes it harder for Debian to override those files and package. How bad is it really? As #144 is currently going nowhere I could remove it again, but later it could be required to add it again. What is your suggestion?

**Comment by kretcheu** [comment]
On page: https://wiki.debian.org/UpstreamGuide#Initial_Packaging 
you can find some instructions.
I think that if you want to put debian recipe use a separate directory for this like:
packaging/debian
packaging/arch

**Comment by phw** [comment]
@kretchau Thanks for your opinion. Having a completely separate directory wouldn't work for Elementary, as they have very strict and limited technical limitations and expect a debian sub-directory on the top level. But I will just remove that again for now, since I can't use the Elementary build service anyway as of now.

**Comment by kretcheu** [comment]
@phw when you tag another version without debian directory I will make a package and send to my sponsor to aprove.

thanks

**Comment by yangfl** [comment]
@kretcheu hi, are you still working on this? Or do you need help? I'm looking forward to this package in Debian. :)

**Comment by phw** [comment]
@kretcheu I have put out a new release 1.1.0 ready for packaging :)

**Comment by phw** [comment]
@kretcheu Ping?

**Comment by hosiet** [comment]
I came across this project days before and believe it is worthwhile to push peek into Debian repository. Unfortunately we've already missed the deadline for Ubuntu 18.04 LTS but it could appear in future versions of Debian and Ubuntu.

As a Debian Maintainer, I've set up a packaging repository on Debian's GitLab instance: https://salsa.debian.org/hosiet-guest/peek

Previous work by @kretcheu is evaluated and merged into this packaging repository. I'm looking to push it into Debian Archive recently.

@kretcheu , is it okay if I just "hijack" your ITP report and continue with the work?

**Comment by phw** [comment]
@hosiet Very cool, thanks a lot. Let me know if there is anything that needs tweaking on my side

**Comment by phw** [comment]
@hosiet FYI, I plan to do a new release later this week or early next week, so all your changes will be available there. Ping me, if there is anything else I should tweak.

One thing in your packaging: You can remove the `Suggest: imagemagick` after the new release, all ImageMagick related code is finally gone for good.

**Comment by hosiet** [comment]
Uploaded and being reviewed on Debian side: https://ftp-master.debian.org/new/peek_1.3.1-1.html , it may take days or months.
See also previous package review at https://bugs.debian.org/895580

If accepted, the package information will be available at https://tracker.debian.org/pkg/peek .

**Comment by luzpaz** [comment]
@phw this ticket can be closed

**Comment by turicas** [comment]
Thanks!
