### ISSUE TITLE
Please add some screenshots (or casts ;) to README.md

### ISSUE THREAD

**Issue by jnachtigall** [phw/peek#81]
I came here from http://askubuntu.com/a/833995/40498 Would be super useful if the README had some kind of screenshot or, hey, screencast ;) So I can see if this fits my needs without having to add a ppa and the software :)

Anyway, I'll install now and hopefully not waste the 15min trying it out. Thanks for the software 👍

**Comment by phw** [comment]
Agreed, wanted to add one anyway. Just have to do a nice recording again.

Hope you enjoy Peek and it fits your needs.
