### ISSUE TITLE
App image file not exist

### ISSUE THREAD

**Issue by asifulmamun** [phw/peek#862]
I have tired to donwload appimage file from release page with readme.md file. But, there was only the souce code not, donwloaded then unzip but can not found any appimage, also other source code same.

**Comment by pythonmaxi** [comment]
I can confirm that the `.AppImage` is missing in newer releases.

**Comment by justDabuK** [comment]
Should we assign a maintainer to this, or how does it happen that this is still unnoticed (and uncommented) by a maintainer? 🤔
