### ISSUE TITLE
All gifs are turning black when recorded

### ISSUE THREAD

**Issue by coabr** [phw/peek#865]
![Peek 2021-08-30 16-03](https://user-images.githubusercontent.com/50220493/131392115-57c8b27b-f5f5-4e82-bea5-9ebaa6466396.gif)
The window is normal, but when the gif is finalized, it's all black. Tried some workaround but didn't work. This started happening when nI change ubuntu to version 21.04

ps: 
![image](https://user-images.githubusercontent.com/50220493/131392949-5cee6f00-26bb-447b-9ebe-2f37db4cdd58.png)
Window appears normally

**Comment by mikromel** [comment]
I noticed the same behavior. Furthermore, it is not possible to work with items under the peek window. Imho both issues are related

**Comment by FullBinaryAlchemist** [comment]
Same issue on Arch Gnome 40.4 wayland

**Comment by JuanVqz** [comment]
I'm having the same issue, Gnome 40.4 
![image](https://user-images.githubusercontent.com/7331511/135338897-b2821580-41a9-4106-b20b-9ee28e13fe60.png)

**Comment by JuanVqz** [comment]
the env key in the readme didn't really helped me, but this does the trick for me

![change to x11](https://www.maketecheasier.com/assets/uploads/2018/03/ubuntu-on-xorg-option.jpg.webp)

source:
https://www.maketecheasier.com/switch-xorg-wayland-ubuntu1710

**Comment by michael-hart-github** [comment]
Same problem on Fedora 35 with Peek 1.5.1. Followed the install guide from the [ReadMe](https://github.com/phw/peek#fedora). No joy.

Note: This project might see a bit of bump after a [recent HN post about GIF making](https://news.ycombinator.com/item?id=29348328). Peek is listed as [a good alternative to LICEcap](https://github.com/justinfrankel/licecap/issues/28#issuecomment-418061123).

**Comment by nafanz** [comment]
A similar problem.

```
nafanz@nafanz-desktop:~$ neofetch
            .-/+oossssoo+/-.               nafanz@nafanz-desktop 
        `:+ssssssssssssssssss+:`           --------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 21.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.13.0-22-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 5 hours, 19 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 3121 (dpkg), 24 (snap) 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.1.8 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 1920x1200 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 40.5 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Yaru [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel Celeron G530 (2) @ 2.400GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: AMD ATI Radeon HD 7750/8740 / R7 250E 
    .ossssssssssssssssssdMMMNysssso.       Memory: 4359MiB / 7935MiB 
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`                                   
            .-/+oossssoo+/-.
```

**Comment by phw** [comment]
This will be fixed in the next release, the fixes are in #910

**Comment by YurkinPark** [comment]
I guess, untill task #33 is not resolved, you could try to uncomment `WaylandEnable=false` string in `/etc/gdm/custom.conf`.

**Comment by kuba-orlik** [comment]
> This will be fixed in the next release, the fixes are in #910

I'm using 1.5.1 and also experiencing this issue on Gnome 41.4

**Comment by Logstor** [comment]
Using 1.5.1 on Fedora 38 with Gnome 44, and it seems like this is still an issue :disappointed:

**Comment by dejanmilo-dev** [comment]
Same here. Manjaro Linux 23.1.2 (Wayland)

**Comment by larinius** [comment]
It records only cursor, game window is black screen.

> Operating System: Manjaro Linux 
> KDE Plasma Version: 5.27.10
> KDE Frameworks Version: 5.113.0
> Qt Version: 5.15.12
> Kernel Version: 6.6.10-1-MANJARO (64-bit)
> Graphics Platform: Wayland
> Graphics Processor: Mesa Intel® UHD Graphics 630

Now 2024, 3 years is not enough to make it work.

**Comment by phw** [comment]
Recording on KDE in a Wayland session is unsupported

**Comment by kuba-orlik** [comment]
I think it would be neat to get a warning at the start of the application that notifies the user that they are on Wayland and the app is not gonna work

**Comment by Gruffyy** [comment]
Agreed with Kuba, seems to be an issue still. Therefore, shitty documentation => unsupported app from my behalf.
