### ISSUE TITLE
Hang linux on save

### ISSUE THREAD

**Issue by rajinder-yadav** [phw/peek#94]
I usually have my system hang when I use this.

OS: `Linux flash 4.4.0-64-generic #85-Ubuntu SMP`
Peek: `0.8.0`

Step to repro, just create a long clip and save it.

* It will usually hang my system on saving.
* Last time I hit cancel when the save dialog box came up, a little while later my system hung.

This is a good tool, but useless if I am going to lose all session each time I use it. Please fix this, I really love this tool.

**Comment by rajinder-yadav** [comment]
I just updated, still same problem on saving!
I was quick this time and keep the process before my system went foobar!

**Comment by phw** [comment]
The most likely explanation is, that your system runs out of RAM and starts swapping. Do you have /tmp mounted as a RAM disk? How much RAM do you have?

If this is the issue, try using a temporary directory somewhere else, e.g. create "tmp" in your home and run Peek with:

    TMPDIR=$HOME/tmp peek

Also can you give some more detail on what you are recording? How large is the area you record? How long do you record? What framerate is set in options?

**Comment by rajinder-yadav** [comment]
Thanks @phw that helped.

I do not have /tmp mounted anywhere special. The only thing I noticed is my /var folder was low, other than this everything else seem fine space wise.

This is what I have, other than the tmpfs do you see anything off? FYI: I did clean up /var just now.

```sh
var: $ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           799M  9.6M  789M   2% /run
/dev/sdb2        47G  7.2G   38G  17% /
tmpfs           3.9G  118M  3.8G   3% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sdb1       226M  142M   69M  68% /boot
/dev/sdb6        29G  2.9G   24G  11% /opt
/dev/sdb5       4.6G  1.8G  2.6G  42% /var
/dev/sdd6       165G   55G  102G  35% /mnt/karma-home
/dev/sdb7       170G  133G   29G  83% /home
tmpfs           799M     0  799M   0% /run/user/118
tmpfs           799M   16K  799M   1% /run/user/1000
```

**Comment by phw** [comment]
I don't see anything off. Not entirely sure, but as the `TMPDIR=$HOME/tmp` workaround helped the most likely explanation is that the temp dir used was actually on one of those tmpfs mounts you see above. Maybe you can check if `TMPDIR` is set to something special.

799 MB temp dir available would not be much, and the really bad thing for `convert` is that temp space would compete with RAM available. And convert uses both.
