### ISSUE TITLE
After update I will see old version 0.8.0

### ISSUE THREAD

**Issue by rajinder-yadav** [phw/peek#95]
I just updated on ubuntu using the PPA, Peek about shows version as 0.8.0

**Comment by phw** [comment]
Did you run "apt update" after adding the PPA? Can you give the output of "dpkg -s peek"?

**Comment by rajinder-yadav** [comment]
Yes I did.

```sh
$ dpkg -s peek
Package: peek
Status: install ok installed
Priority: optional
Section: video
Installed-Size: 380
Maintainer: Philipp Wolfer <ph.wolfer@gmail.com>
Architecture: amd64
Version: 0.8.0
Depends: libgtk-3-0 (>= 3.14), libglib2.0-0 (>= 2.38), ffmpeg, imagemagick
Description: Peek - an animated GIF recorder
```

**Comment by rajinder-yadav** [comment]
I purged the PPA and went with the Ubuntu PPA from the readme, I not have peek 0.9.1, will see if it still hangs my systems.

**Comment by phw** [comment]
Yes, the PPA from the README should be used.
