### ISSUE TITLE
peek launchpad error in pop-os

### ISSUE THREAD

**Issue by apicgg** [phw/peek#956]
The below error is coming whenever trying to update the installed packages with <code>sudo apt update</code>. 

Err:14 http://ppa.launchpad.net/peek-developers/stable/ubuntu hirsute Release      
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/peek-developers/stable/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by willhubs** [comment]
http://ppa.launchpad.net/peek-developers/stable/ubuntu/dists/
Probably because there is no directory for hirsute
Peek is in the universe repositories.

**Comment by apicgg** [comment]
Thanks! I am now using the .deb package built from source which seems to be fine now.

**Comment by max-pod** [comment]
I've also run into the same issue while running pop os. It might be worthwhile to update the docs, or does this issue not occur for standard ubuntu?

**Comment by apicgg** [comment]
> I've also run into the same issue while running pop os. It might be worthwhile to update the docs, or does this issue not occur for standard ubuntu?

Seems to be only for Ubuntu derived Linux os. You can try installing from pop shop! That works as well.
